@startuml

title US01: As an Administrator, I want to configure teacher categories in the system \n (Process View - Level 2 Granularity)

skinparam componentStyle component
skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

actor Administrator as admin

participant "Frontend" as frontend <<component>>
participant "Backend" as backend <<component>>
participant "Database" as db <<component>>

admin -> frontend: I want to configure teacher categories!
activate frontend #E1F5FE

frontend --> admin: What teacher category name?
deactivate frontend

admin -> frontend: Enter teacher category name!
activate frontend #E1F5FE

frontend --> admin: Sure?
deactivate frontend

admin -> frontend: Yes!
activate frontend #E1F5FE

frontend -> backend: (POST) Request configure a TeacherCategory (name)
activate backend #E1F5FE

backend -> db: (INSERT) Persist TeacherCategory (name)
activate db #E1F5FE
db --> backend: teacherCategory
deactivate db

backend --> frontend: (201, Created) TeacherCategory configurated!
deactivate backend

frontend --> admin: Ok!
deactivate frontend

@enduml