@startuml

title US01: As an Administrator, I want to configure teacher categories in the system \n (Process View - Level 3 - Backend)

skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

participant ":Router" as router <<Component>>
participant ":RESTController" as controller <<Component>>
participant ":Service" as service <<Component>>
participant ":Domain" as domain <<Component>>
participant ":Repository" as repository <<Component>>
participant ":Drivers" as drivers <<Component>>

[o-> router: **POST** /teacher-categories + body {"name": "Assistant"}
activate router #E1F5FE

router -> controller: configureTeacherCategory (tcRequestDTO)
activate controller #E1F5FE

controller -> service: configureTeacherCategory (nameVO)
activate service #E1F5FE

service -> repository: existsByName (nameVO)
activate repository #E1F5FE

repository --> service: True
deactivate repository

service -> domain: createTeacherCategory (nameVO)
activate domain #E1F5FE

domain --> service: teacherCategory
deactivate domain

service -> repository: save (teacherCategory)
activate repository #E1F5FE

repository -> drivers: save (teacherCategoryDataModel)
activate drivers #E1F5FE

drivers ->o]: **INSERT INTO** teacherCategory (id, name) \n VALUES ('123e4567-e89b-12d3-a456-426614174000', 'Assistant')

drivers <--o]: teacherCategorySavedDataModel

drivers --> repository: teacherCategorySavedDataModel
deactivate drivers

repository --> service: teacherCategorySaved
deactivate repository

service --> controller: teacherCategorySavedDTO
deactivate service

controller --> router: 201 + body {teacherCategoryResponseDTO + hypermedia}
deactivate controller

[o<-- router: 201 + body {teacherCategoryResponseDTO + hypermedia}
deactivate router

@enduml