@startuml

title US01: As an Administrator, I want to configure teacher categories in the system \n (Process View - Level 1 - System)

skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

actor Administrator as admin
participant ":SystemPAI" as System <<System>>

admin -> System: I want to configure teacher categories!
activate System #E1F5FE

System --> admin: What teacher category name?
deactivate System

admin -> System: Enter teacher category name!
activate System #E1F5FE

System --> admin: Sure?
deactivate System

admin -> System: Yes!
activate System #E1F5FE

System --> admin: Ok!
deactivate System
@enduml