@startuml

title US01: As an Administrator, I want to configure teacher categories in the system \n (Process View - Level 1 Granularity)

skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

actor Administrator as admin
participant ":System \n PAI" as System

admin -> System: I want to configure teacher categories!
activate System #E1F5FE

System --> admin: What category name?
deactivate System

admin -> System: Enter category name!
activate System #E1F5FE

System --> admin: Sure?
deactivate System

admin -> System: Yes!
activate System #E1F5FE

System --> admin: Ok!
deactivate System
@enduml