@startuml

title US01: As an Administrator, I want to configure teacher categories in the system \n (Process View - Level 2 - Containers)

skinparam componentStyle component
skinparam defaultTextAlignment center
skinparam shadowing true

autonumber


participant ":Frontend" as frontend <<Container>>
participant ":Backend" as backend <<Container>>
participant ":Database" as db <<Container>>


-> frontend: Yes!

frontend -> backend: (POST) Request configure a TeacherCategory (tcJSON)
activate backend #E1F5FE

backend -> db: (INSERT) Persist TeacherCategory (teacherCategory)
activate db #E1F5FE

db --> backend: teacherCategory
deactivate db

backend --> frontend: (201, Created) TeacherCategory configurated!
deactivate backend

<-- frontend : Ok!
deactivate frontend

@enduml