@startuml

autonumber

title As an ASC, I want to get the number of students enrolled in a course edition \n (Level 3 - getCourseEditions)

participant "<<Component>>\n:Router" as Router #lightblue
participant "<<Component>>\nCEC:CourseEditionRestController" as C #lightpink
participant "<<Component>>\nCES:CourseEditionService" as S #lightyellow
participant "<<Component>>\nCER:CourseEditionRepository" as R #lightgreen
participant "<<Component>>\n:Drivers" as D #strategy

 -> Router ++: **GET** /course-editions
Router -> C ++: findAllCourseEditions()
C -> S ++: findAll()
S -> R ++: findAll()
R -> D ++: findAll()
D -> : **SELECT** findAll()
D <-- : List<CourseEditions>
D --> R --: List<CourseEditions>
R --> S --: List<CourseEditions>
S --> C --: List<CourseEditions>
C --> Router --: List<CourseEditions
<-- Router --: (OK, 200) List<CourseEditions>

@enduml