@startuml
autonumber

title As an ASC, I want to get the number of students enrolled in a course edition \n (Level 1)
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor #lightblue

actor ASC as Admin
participant "<<System>>\n:SystemPAI" as System #lightblue

activate Admin
Admin -> System ++ #lightblue: I want to get the number of students \nenrolled in a course edition
System --> Admin --: Which course edition?
Admin -> System ++ #lightblue: courseEdition
System --> Admin --: There are [studentCount] students \nenrolled in courseEdition.
@enduml