@startuml
title US02: As an Administrator, I want to configure degree access methods in the system. \n (Process View - Level 3 Granularity)

skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

participant ":Router" as RT <<component>> #LightBlue
participant ":Controller" as CT <<component>>#LightGreen
participant ":Service" as SV <<component>>#LightGray
participant ":Domain" as DM <<component>>#LightYellow
participant ":Repository" as RP <<component>>#white

-> RT: configureAccessMethod (name)
activate RT #LightBlue


RT -> CT: configureAccessMethod\n (accessMethodRequestDTO)
activate CT #LightGreen

CT -> SV: registerAccessMethod\n (nameWithNumbersAndSpecialCharsVO)
activate SV #LightGray

SV -> DM: createAccessMethod\n (nameWithNumbersAndSpecialCharsVO)
activate DM #LightYellow

DM --> SV: accessMethod
deactivate DM
SV -> RP: save (accessMethod)
activate RP

RP --> SV: accessMethod
deactivate RP

SV --> CT: accessMethod
deactivate SV

CT --> RT: (201, Created)\n accessMethodResponseDTO
deactivate CT

<-- RT : (201, Created) accessMethodJSON
deactivate RT

@enduml