@startuml

title US02: As an Administrator, I want to configure degree access methods in the system.\n(Process View - Level 3 - Backend)

skinparam defaultTextAlignment center
skinparam shadowing true


autonumber

participant ":Router" as router <<Component>>
-> router: configureAccessMethod(JSON)
activate router #LightBlue
note over router: The conversion from JSON to DTO is done\n automatically through the Spring Boot Framework

participant ":AccessMethodRESTController" as Controller <<Component>>
router -> Controller: configureAccessMethod(accessMethodRequestDTO)
activate Controller #LightBlue

ref over Controller
    Convert accessMethodRequestDTO to accessMethodCommand
end

participant ":IAccessMethodService" as Service <<Component>>
Controller -> Service: configureAccessMethod\n (accessMethodCommand)
activate Service #LightBlue


participant ":Domain" as Domain <<Component>>
Service -> Domain: createAccessMethod (nameVO)

activate Domain #LightBlue

Domain --> Service: accessMethodCreated


participant ":IAccessMethodRepository" as Repository <<Component>>
Service -> Repository: getAccessMethodByName (am.name)
activate Repository #LightBlue 
Repository --> Service: Optional.empty
deactivate Repository

Service -> Repository: saveAccessMethod (am)
activate Repository #LightBlue 

ref over Repository
    Convert am to DataModel
end




participant ":IAccessMethodRepositorySpringData" as springDataRepository <<Component>>
Repository -> springDataRepository: save (amDataModel)
activate springDataRepository #LightBlue
springDataRepository --> Repository : amDataModelSaved
deactivate springDataRepository



ref over Repository
    Convert amDataModelSaved to Domain
end

Repository --> Service: amSaved
deactivate Repository


ref over Service
    Convert amSaved to amServiceDTO
end

Service --> Controller: amServiceDTO

deactivate Service

ref over Controller
    Convert amServiceDTO to amRequestDTO
end

Controller --> router: (201, Created) amResponse
deactivate Controller

note over router: The conversion from DTO to JSON is done\n automatically through the Spring Boot Framework

<-- router: (201, Created) JSON
deactivate router

@enduml
