@startuml

title US02: As an Administrator, I want to configure degree access methods in the system. \n(Process View - Level 1 Granularity)

skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

actor Administrator as admin #DeepSkyBlue


participant SystemPAI as System <<Component>> #LightBlue

admin -> System: I want to configure a degree access methods!
activate System #LightBlue

System --> admin: What access method name?
deactivate System

admin -> System: Enter access method name!
activate System #LightBlue

System --> admin: Sure?
deactivate System

admin -> System: Yes!
activate System #LightBlue

System --> admin: Ok!
deactivate System

@enduml