@startuml
actor ProgrammeDirector
participant ":UI" as UI
participant ":IWantToKnowTheAverageGradeInACourseEdition" as KA
participant ":GradeStudentRepository" as GR


ProgrammeDirector -> UI ++ #application : I want to know the average grade in a course edition
UI -> KA ++ #application : knowTheAverageGrade(courseEdition)
KA -> GR ++ #application : knowTheAverageGrade(courseEdition)
GR -> GR :validate

GR --> KA --: knowAverageGrade
KA --> UI --: knowAverageGrade
UI --> ProgrammeDirector --: knowAverageGrade

@enduml