@startuml
actor ProgrammeDirector
participant ":UI" as UI
participant ":IWantToKnowTheAverageGradeInACourseEdition" as KA
participant ":GradeStudentRepository" as GR


ProgrammeDirector -> UI ++ #application : I want to know the average grade in a course edition
UI -> KA ++ #application: getCourseEditions()
KA --> UI -- : List<CourseEditions>
UI --> ProgrammeDirector -- : which courseEdition??

ProgrammeDirector -> UI ++ #application : courseEdition 1!
UI -> KA ++ #application : knowTheAverageGrade(ce1)
KA -> GR ++ #application : knowTheAverageGrade(ce1)
GR -> GR :validate

GR --> KA --: knowAverageGrade
KA --> UI --: knowAverageGrade
UI --> ProgrammeDirector --: knowAverageGrade

@enduml