@startuml

!pragma layout smetana
'left to right direction

class US15_UpdateTeacherWorkingPercentageController {
    +US15_UpdateTeacherWorkingPercentageController()
    +getTeacherByNIF(NIF: String)
    +updateWorkingPercentageInTeacherCareerProgression(date: String, workingPercentage: int)
}

class Teacher {
     -_acronym:String
     -_name:String
     -_email:String
     -_nif:String
     -_phoneNumber:String
     -_academicBackground:String
     -_address:Address
     -_department:Department
     +Teacher(acronym: String, name: String, email: String, nif: String, phoneNumber: String,
     academicBackground: String, street: String, postalCode: String, location: String, country: String,
     date: String, category: TeacherCategory, workingPercentage: int, department: Department)
     +hasSameNif(teacher: Teacher)
     +hasThisNIF(NIF: String)
     +updateWorkingPercentageInTeacherCareerProgression(date: String, workingPercentage: int)
     +updateTeacherCategoryInTeacherCarrerProgression(date: String, teacherCategory: TeacherCategory)
}

class TeacherListFactory {
     +newArrayList
}

class TeacherFactory {
    +createTeacher(acronym: String, name: String, email: String, nif: String, phoneNumber: String, \n academicBackground: String, street: String, postalCode: String, location: String,country: String, \n addressFactory: AddressFactory, date: String, category: TeacherCategory, workingPercentage: int,
department: Department)
}

class TeacherCareerProgression {
    -_date: LocalDate
    -_workingPercentage: int
    +TeacherCareerProgression(date: String, workingPercentage: int)
    +getWorkingPercentage()
    +getCategory()
    +getDate()
    +isDateAfter(tcp: TeacherCareerProgression)
}

class TeacherRepository {
    +TeacherRepository()
    +registerTeacher(acronym: String, name:String, email: String, nif: String, phoneNumber:String,
                          address: Address, department: Department)
    +compareTeacherAcronymAndNifInList(Teacher: teacher)
    +getAllTeachers()
    +getTeacherByNIF(NIF: String)
}

class TeacherCategory {
    -_name:String
    + TeacherCategory(name:String)
}

class TeacherCareerProgressionFactory {
    +createTeacherCareerProgression(date: String, category: TeacherCategory, workingPercentage: int)
}

interface TeacherCareerProgressionFactoryInterface {
    +createTeacherCareerProgression(date: String, category: TeacherCategory, workingPercentage: int)
}

class TeacherCareerProgressionListFactory {
    +createTeacherCareerProgressionList()
}

interface TeacherCareerProgressionListFactoryInterface {
    +createTeacherCareerProgressionList()
}

US15_UpdateTeacherWorkingPercentageController "1" ....> "_teacherRepository \n 1" TeacherRepository
Teacher "_teachers \n 1..*" <---- "1" TeacherRepository
Teacher "1" ----> "\n 1..*" TeacherCareerProgression
TeacherFactory "1" ....> "1..*" Teacher
TeacherFactory "1" ....> "   1      _teachercareerprogression" TeacherCareerProgressionFactory
TeacherFactory "1" ....> "    _teachercareerprogressionlist 1   " TeacherCareerProgressionListFactory
TeacherRepository "1" ....> "_teacherFactory 1" TeacherFactory
TeacherCareerProgression "*" ----> "_category \n 1" TeacherCategory
Teacher "1" ....> " _teacherCareerProgressionFactory 1" TeacherCareerProgressionFactory
TeacherCareerProgressionFactory "1" ....> "1..*" TeacherCareerProgression
Teacher "1" ....> "  1 _teacherCareerProgressionList \n" TeacherCareerProgressionListFactory
TeacherCareerProgressionFactory ....|> TeacherCareerProgressionFactoryInterface
TeacherCareerProgressionListFactory ....|> TeacherCareerProgressionListFactoryInterface
TeacherCareerProgressionListFactory "1" ....> " * " TeacherCareerProgression: creates List of TeacherCareerProgression
TeacherRepository "1" ....> "1 _teacherListFactory" TeacherListFactory
US15_UpdateTeacherWorkingPercentageController "1"....> " 1 _teacher" Teacher

@enduml