@startuml

!pragma layout smetana
'left to right direction

class US15_UpdateTeacherWorkingPercentageController {
    +US15_UpdateTeacherWorkingPercentageController()
    +getTeacherByNIF(NIF: String)
    +updateWorkingPercentageInTeacherCareerProgression(date: String, workingPercentage: int)
}

class Teacher {
     -_acronym:String
     -_name:String
     -_email:String
     -_nif:String
     -_phoneNumber:String
     -_academicBackground:String
     -_address:Address
     -_department:Department
     +Teacher(acronym: String, name: String, email: String, nif: String, phoneNumber: String,
     academicBackground: String, street: String, postalCode: String, location: String, country: String,
     date: String, category: TeacherCategory, workingPercentage: int, department: Department)
     +validateAcronym(teacherAcronym:String)
     +validateName(name: String)
     +validateEmail(email: String)
     +validateNif(nif: String)
     +validatePhoneNumber(phoneNumber: String)
     +validateAcademicBackground(academicBackground: String)
     +hasSameAcronym(teacher: Teacher)
     +hasSameNif(teacher: Teacher)
     +isInDepartment(department: Department)
     +hasThisNIF(NIF: String)
     +updateWorkingPercentageInTeacherCareerProgression(date: String, workingPercentage: int)
     +updateTeacherCategoryInTeacherCarrerProgression(date: String, teacherCategory: TeacherCategory)
}

class TeacherFactory {
    +createTeacher(acronym: String, name: String, email: String, nif: String, phoneNumber: String,
   academicBackground: String, street: String, postalCode: String, location: String,
   country: String, addressFactory: AddressFactory, date: String, category: TeacherCategory, workingPercentage: int,
   department: Department, careerProgressionfactory: TeacherCareerProgressionFactory
}

class TeacherCareerProgression {
    -_date: LocalDate
    -_workingPercentage: int
    +TeacherCareerProgression(date: String, workingPercentage: int)
    +getWorkingPercentage()
    +getCategory()
    +getDate()
    +isDateAfter(tcp: TeacherCareerProgression)
}

class TeacherRepository {
    +TeacherRepository()
    +registerTeacher(acronym: String, name:String, email: String, nif: String, phoneNumber:String,
                          address: Address, department: Department)
    +compareTeacherAcronymAndNifInList(Teacher: teacher)
    +getAllTeachers()
    +getTeacherByNIF(NIF: String)
}

class TeacherCategory {
    -_name:String
    + TeacherCategory(name:String)
}

class TeacherCareerProgressionFactory {
    +createTeacherCareerProgression(date: String, category: TeacherCategory, workingPercentage: int)
}

interface TeacherCareerProgressionFactoryInterface {
    +createTeacherCareerProgression(date: String, category: TeacherCategory, workingPercentage: int)
}

class TeacherCareerProgressionListFactory {
    +createTeacherCareerProgressionList()
}

interface TeacherCareerProgressionListFactoryInterface {
    +createTeacherCareerProgressionList()
}

US15_UpdateTeacherWorkingPercentageController "1" ....> "_teacherRepository \n 1" TeacherRepository
Teacher "_teachers \n 1..*" <---- "1" TeacherRepository
Teacher "1" ----> "\n 1..*" TeacherCareerProgression
TeacherFactory "1" ....> "1..*" Teacher
TeacherFactory "1" ....> "1 \n" TeacherCareerProgressionFactory
TeacherFactory "1" ....> "1" TeacherCareerProgressionListFactory
TeacherRepository "1" ....> "_teacherFactory 1" TeacherFactory
TeacherCareerProgression "*" ----> "_category \n 1" TeacherCategory
Teacher "1" ....> "1" TeacherCareerProgressionFactory: _teacherCareerProgressionFactory
TeacherCareerProgressionFactory "1" ....> "1..*" TeacherCareerProgression
Teacher "1" ....> "_teacherCareerProgressionList \n           1" TeacherCareerProgressionListFactory
TeacherCareerProgressionFactory ....|> TeacherCareerProgressionFactoryInterface
TeacherCareerProgressionListFactory ....|> TeacherCareerProgressionListFactoryInterface
TeacherCareerProgressionListFactory "1" ....> " * " TeacherCareerProgression: creates List of

@enduml