@startuml

title Validate Grading Business Rules and Create StudentGrade - (Interaction Use #3)
skinparam sequencemessagealign center

participant ":CourseEditionRESTController" as ctrlrREST #business
participant ":GradeAStudentServiceImpl" as service #motivation
participant ":CourseEditionEnrolmentRepositorySpringData" as ceer #physical
participant ":CourseEditionEnrolmentMapperImpl" as ceemp #strategy
participant ":StudentGradeFactoryImpl" as sgf #technology
participant "sg1:StudentGrade" as gs #skyblue


ctrlrREST -> service : gradeAStudent (grade, date, studentID, courseEditionID)
activate service
service -> ceer : isStudentEnrolledInCourseEdition (studentID, courseEditionID)
activate ceer

ceer ->  : findAll()
ceer <--  :  courseEditionEnrolmentDataModel
ceer -> ceemp : toDomain
activate ceemp
ceemp --> ceer : List <CourseEditionEnrolment>
deactivate ceemp
ceer --> service : true
deactivate ceer

service -> service : isDateGradeInRangeWithSchoolYear()
service -> service : hasStudentAlreadyGradeAtThisCourseEdition()

service -> sgf : newGradeStudent (Grade,Date, StudentID, CourseEditionID)
activate sgf
create gs
sgf -> gs : <Create> (Grade,Date, StudentID, CourseEditionID)
activate gs
gs --> sgf : sg1
deactivate gs
sgf --> service : sg1
deactivate sgf


@enduml