@startuml
!pragma layout smetana
'left to right direction

class Department {
    -_acronym:String
    -_name:String
    -_director:Teacher
    -_departmentTeachers:List<Teacher>
    -_departmentProgramme:List<Programme>
    +Department(departmentAcronym: String, departmentName: String)
    +Department(departmentAcronym: String, departmentName: String,director: Teacher)
    +hasSameAcronym(department: Department)
    +hasSameName(department: Department)
    +changeDirector(furtherDirector: Teacher)

}

class DepartmentRepository {
    -_departments: List<Department>
    +departmentRepository()
    +registerDepartment(departmentAcronym: String, departmentName: String)
    +getDepartmentsList()
    +departmentExists(department: Department)
}

class TeacherCategory {
    -_name:String
    + TeacherCategory (name:String)
}

class CourseEditionEnrollment {
    -_student: Student
    -_courseEdition: CourseEdition
    -_enrollmentDate: LocalDate
    +CourseEditionEnrollment(student:Student, courseEdition: CourseEdition,
     enrollmentDate: LocalDate)
    +equals (obj: Object)
    +findStudentInCourseEditionEnrollment ()
    +findCourseEditionInEnrollment ()
    +knowStudent ()
    +knowCourseEdition ()
}

class CourseEditionEnrollmentRepository {
    -_courseEditionEnrollments: ArrayList<CourseEditionEnrollment>
    +CourseEditionEnrollmentRepository ()
    +enrollStudentInACourseEdition (student: Student, courseEdition: CourseEdition,
    enrollmentDate: LocalDate)
    +isStudentEnrolledInCourseEdition (student: Student, courseEdition: CourseEdition)
    +findByStudentAndEdition (student: Student, courseEdition: CourseEdition)
    +numberOfStudentsEnrolledInCourseEdition (courseEdition: CourseEdition)
}

class ProgrammeEditionEnrollment {
    -_student: Student
    -_programmeEdition: ProgrammeEdition
    -_enrollmentDate: LocalDate
    +ProgrammeEditionEnrollment(student:Student, programmeEdition: ProgrammeEdition,
     enrollmentDate: LocalDate)
    +isEnrollmentAssociatedToDepartmentAndSchoolYear(department: Department, schoolYear: SchoolYear)
    +getStudentUniqueNumber()
    +equals (obj: Object)
    +findProgrammeEditionInEnrollment ()
    +findStudentInProgrammeEdition ()
}

class ProgrammeEditionEnrollmentRepo {
    -_programmeEditionEnrollments: List<ProgrammeEditionEnrollment>
    +ProgrammeEditionEnrollmentRepo()
    +enrollStudentInProgrammeEdition (student: Student, programmeEdition: ProgrammeEdition,
    localDate: LocalDate)
    +isStudentEnrolledInThisProgrammeEdition(student: Student, programmeEdition: ProgrammeEdition)
    +checkIfThisEnrollmentAlreadyExists(programmeEditionEnrollment: ProgrammeEditionEnrollment)
    +countStudentsInProgrammesFromDepartmentInSchoolYear(department: Department, schoolYear: SchoolYear)
    +getTheNumberOfStudentsEnrolledInAProgrammeEdition(programmeEdition: ProgrammeEdition)
}


class TeacherCategoryRepository {
    -_teacherCategoryRepository:ArrayList<TeacherCategory>
    +TeacherCategoryRepository()
    +registerTeacherCategory (teacherCategoryName: String)
    +isTeacherCategoryRegistered(teacherCategory: TeacherCategory)
    +getTeacherCategoriesList()
}

class Programme {
     - name: string
     - acronym: string
     - quantityOfEcts: int
     - quantityOfSemesters: int
     - degreeType: DegreeType
     - department: Department
     - programmeDirector: Teacher
     -_courseList: List <Course>
     -_programmeEnrolment: List<Enrolment>
     -StudyPlan: _studyPlan

     + equals()
     + addCourseToProgramme (course: Course)
     + newProgrammeDirector(): boolean
     +enrolStudentInProgramme(Student: student, accessMethod: AccessMethod, amr: AccessMethodRepository)
     +isStudentEnrolled(student: Student)
     +isInDepartment(department: Department)
     +getCourseList()
     +getQuantityOfSemester()
     +getQuantityOfEcts()
 }

 class ProgrammeList {
     -_programmeList: List<Programme>
     +registerProgramme(String : name, String : acronym, int : quantityOfEcts, int quantityOfSemesters, int degreeType: DegreeType; Department : department, Teacher programmeDirector)
     +changeProgrammeDirector(Programme programme, Teacher newDirector)
     +getAllProgrammes()
 }

class ProgrammeEdition {
    -_programme: Programme
    -_schoolYear: SchoolYear
    +programmeEdition(programme: Programme,schoolYear: SchoolYear)
    +equals(object: Object)
    +findProgrammeInProgrammeEdition()
    +findSchoolYearInProgrammeEdition()
    +isEditionAssociatedToDepartmentAndSchoolYear(department: Department, schoolYear: SchoolYear)
}

class DegreeType {
    - name: string
    - maxEcts: int
    + nameIsInvalid(): boolean
    + maxEctsIsInvalid(): boolean
}

class Teacher {
     -_acronym:String
     -_name:String
     -_email:String
     -_nif:String
     -_phoneNumber:String
     -_academicBackground:String
     -_address:Address
     -_department:Department
     -_teacherCareerProgression:List<TeacherCareerProgression>
     +Teacher(acronym: String, name: String, email: String, nif: String, phoneNumber: String,
     academicBackground: String, street: String, postalCode: String, location: String, country: String,
     date: String, category: TeacherCategory, workingPercentage: int, department: Department)
     +hasSameAcronym(teacher: Teacher)
     +hasSameNif(teacher: Teacher)
     +isInDepartment(department: Department)
     +hasThisNIF(NIF: String)
     +updateWorkingPercentageInTeacherCareerProgression(date: String, workingPercentage: int)
     +updateTeacherCategoryInTeacherCarrerProgression(date: String, teacherCategory: TeacherCategory)
}

class TeacherCareerProgression {
    -_date: LocalDate
    -_category: TeacherCategory
    -_workingPercentage: int
    +TeacherCareerProgression(date: String, category: TeacherCategory, workingPercentage: int)
    +getCategory()
    +getWorkingPercentage()
    +isDateAfter(tcp: TeacherCareerProgression)
}

class TeacherRepository {
    -_teachers: List<Teacher>
    +teacherRepository()
    +registerTeacher(acronym: String, name:String, email: String, nif: String, phoneNumber:String,
                          address: Address, teacherCategory: TeacherCategory, department: Department)
    +getTeacherByNIF(NIF: String)
    +updateTeacherCategory(date: String, teacher: Teacher, teacherCategory: TeacherCategory)
    +getAllTeachers()
}


class SchoolYear {
    -_description:String
    -_startData:String
    -_endDate:String
    +SchoolYear(description: String, StartDate: String, EndDate: String)
    +isSameSchoolYear(otherSchoolYear: SchoolYear)
    +equals(Object: o)
}

class SchoolYearRepository {
    -_schoolYearList: List<SchoolYear>
    +schoolYearRepository()
    +addSchoolYear(description: String, StartDate: String, EndDate: String)
    +schoolYearExists(schoolYear: SchoolYear)
    +getLatestSchoolYear()
    +getAllSchoolYears()
}

class Enrolment {
    -_student: Student
    -_accessMethod: AccessMethod
    +Enrolment(Student: student, AccessMethod: accessMethod)
    +isSameStudent(Student: student)
    +findStudentInEnrollments()
}

class Student {
    -_uniqueNumber:int
    -_name:String
    -_NIF:String
    -_phone:String
    -_email:String
    +Student(uniqueNumber: int, name: String, NIF: String, phone: String, email: String, address: Address)
    +isStudentRepeated(students: List<Student>)
    +hasSameUniqueNumber(Student student)
}

class StudentRepository {
    -_students: List<Student>
    +registerStudent(uniqueNumber: int, name: String, NIF: String, phone: String, email: String, address: Address)
    +isStudentEnrolledInProgramme(Student student, Programme programme)
}

class AccessMethod {
    -_name:String
    +AccessMethod(name:String)
}

class AccessMethodRepository {
    -_accessMethodRepository:ArrayList<AccessMethod>
    +AccessMethodRepository()
    +registerAccessMethod (accessMethodName: String)
    +isAccessMethodRegistered(accessMethod: AccessMethod)
}

class Address {
     -_street:String
     -_postalCode: String
     -_location: String
     -_country: String
     +Address(street: String, postalCode: String, location: String, country: String)
}

class Course {
    -_name: String
    -_acronym: String
    -_quantityCreditsEcts: double
    -_durationCourseInSemester: int

    +Course(name: String, acronym: String, quantityCreditsECTS: double, durationCourseInSemester: int)
    +getQuantityCreditsEcts()
    +getDurationInSemester()
    +getName()
    +getAcronym()
}

class CourseRepository {
    -_courseRepository:ArrayList<Course>
    +CourseRepository()
    +registerCourse (courseName: String, acronym: String, quantityCreditsECTS: double, durationCourseInSemester: int)
    +isCourseRegistered (course: Course)
}

class CourseEdition {
    -_programmeEdition: ProgrammeEdition
    -_course: Course
    -_Teacher: Ruc
    +CourseEdition(programmeEdition: ProgrammeEdition, course: Course)
    +Equals(objectToCompare: Object)
    +setRuc(Teacher: ruc)
    +whatProgrammeEditionBelongsThisCourseEdition ()
}

class CourseEditionRepository {
    -_courseEditionRepository: ArrayList<CourseEdition>
    +CourseEditionRepository()
    +createCourseEdition(course: Course, programmeEdition: ProgrammeEdition)
    +isCourseEditionAlreadyInRepository (courseEdition: CourseEdition)
    +findWhichProgrammeEditionBelongsToACourseEdition(courseEdition: CourseEdition)
    +setRucInACourseEdition(CourseEdition: courseEdition,Teacher: ruc)
    +getCourseEdition()
    +findCourseEditionsByProgrammeEdition(ProgrammeEdition programmeEdition)
}

class GradeStudent {
    -grade: double
    -date: String
    +knowGrade()
}

class GradeStudentRepository {
    -gradeStudentList: List<GradeStudent>
    +addGradeToStudent()
    +KnowAverageGrade()
    +knowApprovalRate()
}
class StudyPlan {

    +addCourseToStudyPlan()

}

class CourseInStudyPlan {
    -semester: int
    -curricularYear: int
    +equals()
    +getCourse()
    +getSemester()
    +getCurricularYear()
    +getProgramme()
}

class ProgrammeEditionRepository {
    -_programmeEditionRepository: ArrayList<ProgrammeEdition>
    +ProgrammeEditionRepository()
    +createProgrammeEdition(programme: Programme, schoolYear: SchoolYear)
    +findProgrammeEditionBySchoolYearAndProgramme(programme: Programme, schoolYear: SchoolYear)
    +getAllProgrammeEditions()
}

Teacher "1" --> "1" Address: has
Student "1" --> "1" Address: has
Programme "1..*" --> "1" Teacher : has a Programme Director
Teacher "1..*" --> "*" Course: teaches
Programme "*" -u-> "1*" Department: assigned to
Course "*" -- "1" Programme : aggregates
DegreeType "1" <-- "*" Programme
Enrolment "*" --> "1" AccessMethod: is registered
Programme "1"  -u-> "*" Enrolment: has
Student "1" <-- "*" Enrolment: enrols
StudentRepository "1" --> "*" Student
SchoolYearRepository "1" --> "*" SchoolYear: stores
ProgrammeEdition "*" -l-> "1" SchoolYear: relates to
Teacher "1" <-r- "1" Department: is Department Director
Teacher "1..*" <-- "1" Department: aggregates
Teacher "1..*" <-- "1" TeacherRepository: stores
Teacher "1" --> "1..*" TeacherCareerProgression: comprises
TeacherCareerProgression "*" --> "1"TeacherCategory: comprises
Department "1..*" <-- "1" DepartmentRepository: stores
AccessMethod "1..*" -- "1" AccessMethodRepository
TeacherCategory "1..*" <-- "1" TeacherCategoryRepository: stores
Course "1..*" -- "1" CourseRepository
Course "1..*" --> "1..*" CourseEdition: organised in
GradeStudent "*" --> "1" Student: belongs
GradeStudent "*" --> "1" CourseEdition: refers to
StudyPlan "1" <-- "1..*" CourseInStudyPlan: belongs
CourseInStudyPlan "*" --> "1" Programme: belongs
CourseInStudyPlan "0..1" <-- "1" Course: happens
CourseEdition "*" --> "1" ProgrammeEdition: belongs to
CourseEdition "*" -- "1" CourseEditionRepository
CourseEdition "1" --> "1" TeacherRepository
Student "1" --- "*" CourseEditionEnrollment : > enrols
CourseEditionEnrollment "*" -- "1" CourseEdition : > relates to
CourseEditionEnrollment "*" -- "1" CourseEditionEnrollmentRepository
ProgrammeEdition "1" -- "*" ProgrammeEditionEnrollment : < happens
ProgrammeEditionEnrollment "*" -- "1" Student : < enrols
ProgrammeEditionEnrollment "*" -- "1" ProgrammeEditionEnrollmentRepo
ProgrammeEdition "1..*" -- "1" ProgrammeEditionRepository
ProgrammeList "1" -- "1..*" Programme
GradeStudentRepository "1" --> "*" GradeStudent

@enduml
