@startuml
autonumber

participant "pCtrl:ProgrammeRestController" as C #implementation
participant "pMapper:ProgrammeMapper" as PM #lightgreen
participant "programmeResponseDTO:ProgrammeResponseDTO" as PDTO

activate C
C -> PM ++: fromDomainToDTO(Programme)
PM -> PDTO**: new ProgrammeResponseDTO (name, acronym, quantECTS \nquantSemesters, degreeTypeName, departmentName, teacherName)
activate PDTO
PDTO --> PM--: programmeResponseDTO
PM --> C--: programmeResponseDTO

@enduml