@startuml
scale 0.8
skinparam ranksep 20
skinparam nodesep 150
skinparam linetype ortho
skinparam classBackgroundColor #E1F5FE

title US04:As an Administrator, i want to register a Teacher in the System.
package "Controller Aggregates" {
class US04_IWantToRegisterATeacherInTheSystemController #lightblue{
    +US04_IWantToRegisterATeacherInTheSystemController\n(iTeacherRepository:ITeacherRepository,\n iDepartmentRepository:IDepartmentRepository)
    +registerATeacherInTheSystem\n(acronym:TeacherAcronym, name:Name, email:Email,\n nif:NIF, phoneNumber:PhoneNumber,\n academicBackground:AcademicBackground,\n street:Street, postalCode:PostalCode,\n location:Location, country:Country,\n departmentID:DepartmentID)
}
}
package "Factory"{
class TeacherFactoryImpl #lightblue{
    +createTeacher(TeacherID:TeacherID,\n name:Name, email:Email, nif:NIF,\n phoneNumber:PhoneNumber, academicBackground:AcademicBackground,\n street:Street, postalCode:PostalCode,\n location:Location, country:Country,\n teacherCategory:TeacherCategory,\n department:Department):Teacher
    +createAddress(street:Street,\n postalCode:PostalCode,\n location:Location, country:Country)
}
interface ITeacherFactory #lightblue{
    +createTeacher(acronym:Acronym, TeacherID:TeacherID,\n name:Name, email:Email, nif:NIF,\n phoneNumber:PhoneNumber, academicBackground:AcademicBackground,\n street:Street, postalCode:PostalCode,\n location:Location, country:Country,\n \n departmentAcronym:DepartmentAcronym):Optional<Teacher>
}
}
package "Service"{
class TeacherServiceImpl{
   +registerTeacher(acronym:Acronym, TeacherID:TeacherID,\n name:Name, email:Email, nif:NIF,\n phoneNumber:PhoneNumber, academicBackground:AcademicBackground,\n street:Street, postalCode:PostalCode,\n location:Location, country:Country,\n departmentAcronym:DepartmentAcronym):Optional<Teacher>
 }
 interface ITeacherService{
    +registerTeacher(acronym:Acronym, TeacherID:TeacherID,\n name:Name, email:Email, nif:NIF,\n phoneNumber:PhoneNumber, academicBackground:AcademicBackground,\n street:Street, postalCode:PostalCode,\n location:Location, country:Country,\n departmentAcronym:DepartmentAcronym):boolean
 }
 }
 package "Mapper Aggregates" {
class TeacherMapperImpl{
+ ToDomain(teacherDataModel:TeacherDataModel)Teacher
+toDataModel(teacher:Teacher)TeacherDataModel
}
interface ITeacherMapper{
+ ToDomain(teacherDataModel:TeacherDataModel)Teacher
+toDataModel(teacher:Teacher)TeacherDataModel
}
}
package "DataModel" {
class TeacherDataModel{
-_acronym:TeacherAcronym
        -_name:String
        -_email:String
        -_nif:String
        -_street:String
        -_postalCode:PostalCode
        -_location:Location
        -_country:Country
        -_phoneNumber:PhoneNumber
        -_academicBackground:AcademicBackground
        -_departmentID:DepartmentID
}
}
package "Repository"{
class TeacherRepositorySpringDataImpl{
+addTeacher (acronym:String, TeacherID:String,\n name:String, email:String, nif:String,\n phoneNumber:String, academicBackground:String,\n street:String, postalCode:String,\n location:String, country:String,\n \n departmentID:String):Teacher

}

interface IDepartmentRepository #lightblue{
    +departmentExists(department:Department):boolean
    +FindDepartmentByID(departementID:DepartmentID):\n Optional<Department>
}

interface ITeacherRepository #lightblue{
    +save(teacher: Teacher):teacher

}
interface JPARepository{}

interface ITeacherRepositorySpringData{
+save(teacher: Teacher)teacher
+existsByTeacherIdOrNif(TeacherID teacherID, NIF nif) boolean
}
}
package "Teacher Aggregates" #CornflowerBlue {
    entity "<<Root>>Teacher" #lightblue{
        -_acronym:TeacherAcronym
        -_name:Name
        -_email:Email
        -_nif:NIF
        -_street:Street
        -_postalCode:PostalCode
        -_location:Location
        -_country:Country
        -_phoneNumber:PhoneNumber
        -_academicBackground:AcademicBackground
        -_departmentID:DepartmentID
     }
}



US04_IWantToRegisterATeacherInTheSystemController ..> ITeacherService
ITeacherService <|.."Implements" TeacherServiceImpl
TeacherServiceImpl ..> ITeacherRepository
TeacherServiceImpl ..> IDepartmentRepository

TeacherServiceImpl"1" ..>"1" ITeacherFactory
ITeacherFactory <|..TeacherFactoryImpl
"<<Root>>Teacher" "1"..>"1" TeacherFactoryImpl
ITeacherRepositorySpringData ..|> "extends"JPARepository
TeacherRepositorySpringDataImpl "1"..|> ITeacherRepositorySpringData
ITeacherRepositorySpringData <|.. ITeacherRepository

TeacherRepositorySpringDataImpl"1" ->"*" TeacherDataModel
ITeacherMapper "1"<.. "1"TeacherRepositorySpringDataImpl
ITeacherMapper ..> ITeacherFactory
TeacherMapperImpl ..|> ITeacherMapper
TeacherMapperImpl..>"maps to" TeacherDataModel
TeacherMapperImpl..>"maps to""<<Root>>Teacher"



@enduml


