@startuml
title: US19_CREATE A COURSE EDITION_SEQUENCE DIAGRAM
autonumber

actor ASC
participant ":UI" as UI
participant ":CreateACourseEditionController" as CT
participant ":ProgrammeEditionRepository" as PER
participant "pE1:ProgrammeEdition" as PE
participant "pEL1:List<ProgrammeEdition>" as PEL
participant "p1:Programme" as PG
participant "cL1:List<Course>" as CL
participant ":CourseEditionRepository" as CER

ASC -> UI ++ #application :  I want to create a Course Edition
UI -> CT ++ #application: getAllProgrammeEditions()
CT -> PER ++ #application: getAllProgrammeEditions()
PER --> CT -- : pEL1
CT --> UI -- : pEL1
UI --> ASC -- : which programme edition??


ASC -> UI ++ #application : programme edition 1!
UI -> CT ++ #application: getCoursesInProgramme(pE1)
CT -> PE ++ #application: findProgrammeInProgrammeEdition(pE1)
PE --> CT -- : p1

CT -> PG ++ #application: getCourseList(p1)

PG --> CT -- : cL1
CT --> UI -- : cL1
UI --> ASC -- : which course??


ASC -> UI ++ #application : course 1!
UI -> CT ++ #application : createCourseEdition(c1,pE1)
CT -> CER ++ #application : createCourseEdition(c1,pE1)


create "cE1:CourseEdition" as CE #lightblue
CER -> CE ++ #application : <create> (c1, pE1)
CE --> CER -- : cE1
CER -> CER : isCourseEditionAlreadyInRepository (cE1)
CER -> CER : addCourseEdition (cE1)

CER --> CT --: true
CT --> UI --: true
UI --> ASC --: true

@enduml