@startuml
actor RUC
participant ":UI" as UI
participant ":Controller" as ctr
participant ":GradeStudentRepository" as GR
participant ":CourseEditionEnrollmentRepository" as CEER

RUC -> UI ++ #application: I want to grade a Student in a Course Edition
UI --> RUC --: Grade, Date, CourseEdition, Student?
RUC -> UI ++ #application: Grade, Date, CourseEdition, Student!
UI -> ctr ++ #application : IWantToGradeStudent (Grade, Date, Student, CourseEdition)
ctr -> CEER ++ #application : isStudentEnrolledInCourseEdition (Student, CourseEdition)
CEER --> ctr -- : true


ctr -> GR ++ #application : addGradeToStudent (Grade, Date, Student, CourseEdition)


create ":GradeStudent" as GS
GR -> GS ++ #application : <Create> (Grade, Date, Student, CourseEdition)
GS -> GS : isGradeValid()
GS -> GS : isDateValid()
GS --> GR -- : gs1

GR -> GR : addGrade(gs1)
GR --> ctr --: gs1
ctr --> UI --: gs1
UI --> RUC --: Succeed

@enduml