@startuml
actor RUC
participant ":UI" as UI
participant ":Controller" as ctr
participant ":gs1:GradeStudentRepository" as GR
participant ":CourseEditionEnrollmentRepository" as CEER
participant ":gs1:GradeStudent" as GS

RUC -> UI ++ #application: I want to grade a Student in a Course Edition
UI --> RUC --: Grade, Date, CourseEdition, Student?
RUC -> UI ++ #application: Grade, Date, CourseEdition, Student!
UI -> ctr ++ #application : IWantToGradeStudent (Grade, Date, Student, CourseEdition)
ctr -> GR ++ #application : addGradeToStudent (Grade, Date, Student, CourseEdition)

' Verificação de inscrição no curso (assumindo que sempre retorna true)
GR -> CEER ++ #application : isStudentEnrolledInCourseEdition(Student, CourseEdition)
CEER --> GR -- : true

' Criação da nota do estudante
create ":gs1:GradeStudent" as gs
GR -> gs ++ #application : <Create> (Grade, Date, Student, CourseEdition)
gs -> gs : isGradeValid()
gs -> gs : isDateValid()
gs --> GR -- : gs1

' Adiciona a nota ao repositório
GR -> GR : addGrade(gs1)
GR --> ctr --: gs1
ctr --> UI --: gs1
UI --> RUC --: Succeed

@enduml
