@startuml
title US21: As an ASC, I want to get the number of students enrolled in a programme edition\n(References in Scenario View - Level 4 Full Backend Flow)

autonumber
skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}

participant ":ProgrammeEditionRESTController" as restController <<component>> <<RESTController>> #teal
participant ":IProgrammeEditionControllerAssembler" as assembler <<component>> <<Assembler>> #teal

activate restController #LightBlue
restController -> assembler: toServiceDTO (List<programmeEditionRequestDTO>\n programmeEditionRequestDTO)
activate assembler #LightBlue
create "programmeEdition: ProgrammeEdition"
assembler -> "programmeEdition: ProgrammeEdition": createProgrammeEdition (\n programmeEditionServiceDTO.programmeId,\n programmeEditionServiceDTO.schoolYearId)

@enduml