@startuml
title: Find Course Editions By Programme Edition ID\n(Code View - Level 4)

autonumber

participant ":CourseEditionController" as ceCtrl
activate ceCtrl
participant ":CourseEditionService" as ceService
participant ":CourseEditionRepository" as ceRepo
participant ":CourseEditionAssembler" as ceAssembler
participant ":CourseEditionMapper" as ceMapper
participant ":CourseEditionFactory" as ceFactory
database DB

ceCtrl -> ceService ++: getCourseEditionsByProgrammeEditionId(programmeEditionId)
ceService -> ceRepo ++: findByProgrammeEditionId(programmeEditionId)
ceRepo -> DB ++: SELECT * FROM course_editions WHERE programme_edition_id = programmeEditionId
DB --> ceRepo --: List<CourseEditionDataModel>

loop for CourseEditionDataModel[i]
ceRepo -> ceMapper ++: toDomain(CourseEditionDataModel[i])
ceMapper -> ceFactory ++: newCourseEditionID(id, courseId, programmeEditionId)
note over of ceFactory
    Creates a new
    CourseEditionID object
end note
ceFactory --> ceMapper --: CourseEditionID
ceMapper --> ceRepo --: List<CourseEditionID>
end

ceRepo -> ceService: List<CourseEditionID>
ceService -> ceAssembler ++: toDtoList(List<CourseEditionID>)

loop for CourseEditionID[i]
    note over of ceAssembler
        Invokes CourseEditionResponseDTO
             to construct object
    end note
end
ceAssembler --> ceService --: List<CourseEditionResponseDTO>
ceService --> ceCtrl --: List<CourseEditionResponseDTO>

legend right
  DTO = Data Transfer Object
  Mapper = Convert DataModel to Domain
  Assembler = Convert Domain to DTO
end legend

@enduml 