@startuml
title: Find Course Editions By Search Criteria\n(Code View - Level 4)

autonumber

participant ":Router" as router
participant ":CourseEditionRestController" as ceCtrl
activate ceCtrl
participant ":CourseEditionAssembler" as ceAssembler
participant ":CourseEditionHateoasAssembler" as ceHateoasAssembler
participant ":CourseEditionService" as ceService
participant ":CourseEditionRepository" as ceRepo
participant ":CourseEditionMapper" as ceMapper
participant ":CourseEditionFactory" as ceFactory
database DB

router -> ceCtrl: GET /courseeditions/programmeditions
ceCtrl -> ceAssembler ++: toProgrammeEditionID(courseEditionRequestDTO)
ceAssembler --> ceCtrl --: programmeEditionID
ceCtrl -> ceAssembler ++: toCourseInStudyPlanID(courseEditionRequestDTO)
ceAssembler --> ceCtrl --: courseInStudyPlanID

ceCtrl -> ceService ++: findCourseEditionByProgrammeEditionIdAndCourseInStudyPlanId(programmeEditionID, courseInStudyPlanID)
ceService -> ceRepo ++: findCourseEditionByProgrammeEditionIdAndCourseInStudyPlanId(programmeEditionID, courseInStudyPlanID)

ceRepo -> ceMapper ++: toProgrammeEditionIdDataModel(programmeEditionID)
ceMapper --> ceRepo --: programmeEditionIdDataModel
ceRepo -> ceMapper ++: toCourseInStudyPlanIDDataModel(courseInStudyPlanID)
ceMapper --> ceRepo --: courseInStudyPlanIDDataModel

ceRepo -> DB ++: SELECT * FROM course_editions \nWHERE programme_edition_id = :programmeEditionIdDataModel \nAND course_in_study_plan_id = :courseInStudyPlanIdDataModel
DB --> ceRepo --: List<CourseEditionDataModel>

loop for CourseEditionDataModel[i]
ceRepo -> ceMapper ++: toDomain(CourseEditionDataModel[i])
ceMapper -> ceFactory ++: newCourseEditionID(id, courseId, programmeEditionId)
note over of ceFactory
    Creates a new
    CourseEditionID object
end note
ceFactory --> ceMapper --: CourseEditionID
ceMapper --> ceRepo --: List<CourseEditionID> 
end

ceRepo -> ceService: List<CourseEditionID>  //TODO: Check if this is correct
ceService --> ceCtrl --: List<CourseEditionID>
ceCtrl -> ceAssembler ++: toResponseDTOList(List<CourseEditionID>)
ceAssembler --> ceCtrl --: List<CourseEditionResponseDTO>
ceCtrl -> ceHateoasAssembler ++: toCollectionModel(List<CourseEditionResponseDTO>)
note right of ceHateoasAssembler
  Create CollectionModel with:
  - Self link for collection
  - EntityModel for each CourseEdition
  - Links for each CourseEdition:
    - Self
    - Enroll student
    - View details
end note
ceHateoasAssembler --> ceCtrl --: CollectionModel<CourseEditionResponseDTO>
ceCtrl --> router: CollectionModel<CourseEditionResponseDTO>

legend right
  DTO = Data Transfer Object
  Mapper = Convert DataModel to Domain
  Assembler = Convert Domain to DTO
  HATEOAS Assembler = Convert Domain to EntityModel with links
end legend

@enduml 