@startuml
title: Get Programme Edition Enrollments By Student ID\n(Code View - Level 4)

autonumber

participant ":ProgrammeEditionEnrolmentController" as peeCtrl
activate peeCtrl
participant ":ProgrammeEditionEnrolmentService" as peeService
participant ":ProgrammeEditionEnrolmentRepository" as peeRepo
participant ":ProgrammeEditionEnrolmentAssembler" as peeAssembler
database DB

peeCtrl -> peeService ++: getProgrammeEditionEnrollmentsByStudentID(StudentID)
peeService -> peeRepo ++: findProgrammeEditionsThatStudentIsEnrolled(StudentID)
peeRepo -> DB ++: SELECT programme_edition_id FROM programme_edition_enrollments\nWHERE student_id = StudentID
DB --> peeRepo --: List<ProgrammeEditionID>

peeRepo --> peeService --: List<ProgrammeEditionID>
peeService --> peeCtrl --: List<ProgrammeEditionID>

peeCtrl -> peeAssembler ++: toDtoList(List<ProgrammeEditionID>, StudentID)

loop for ProgrammeEditionID[i]
    note over of peeAssembler
        Invokes ProgrammeEditionEnrolmentDetailDTO
             to construct object using
             ProgrammeEditionID and StudentID
            
    end note
end
peeAssembler --> peeCtrl --: List<ProgrammeEditionEnrolmentDetailDTO>

legend right
  DTO = Data Transfer Object
  Assembler = Convert Domain to DTO
end legend

@enduml 