@startuml
title <size:30>"REF 3 | FindLastest() StudyPlanID"</size>
|||
participant ":StudyPlan\nService" as Service
participant ":StudyPlanRepository\nSpringData" as Repository
database "Database" as DT #application
participant ":StudyPlan\nMapper" as SM
participant ":StudyPlan\nIDMapper" as SIM
participant ":StudyPlan\nFactory" as F
participant "newListDomain\n:List<StudyPlan>" as NL #application
participant "StudyPlan" as SP

skinparam sequenceLifeLineBackgroundColor #application
|||
Service -> Service ++ : getStudyPlansByProgrammeID(ProgrammeID)

Service -> Repository ++  : findAll()
Repository -> DT ++ :findAll()
DT --> Repository --: listDataModel
|||
Repository --> SM ++: toDomain(listDataModel)

create "listDomain\n:List<StudyPlan>" as DomainList #application
SM -> DomainList : listDomain = newArrayList<>
SM --> Repository -- :listDomain


Repository --> Service --: listDomain

group#application for (studyPlan : listDomain)
    alt#application studyPlan.identity().getProgrammeID().equals(programmeID)
        Service -> NL : result.add(studyPlan)
    end
end
Service -> NL ++: getLast()
NL -> SP ++: identify()
SP -> NL --: StudyPlanID
NL -> Service --: StudyPlanID

@enduml