@startuml
actor ASC
autonumber


ASC -> System ++ #application: I want to add course to a programme
System --> ASC: Which Programme? List of Programmes
ASC -> System: Programme P1
System --> ASC : sure?
ASC -> System: yes!
System --> ASC: Which Study Plan? List of StudyPlan
ASC -> System: StudyPlan SP1
System --> ASC: sure?
ASC -> System: yes!
System --> ASC : Which Course? List of Courses
ASC -> System: Course C1
System --> ASC: sure?
ASC -> System: yes!
System --> ASC --: C1 was added to SP1 of P1


@enduml