@startuml
actor ASC
autonumber

ASC -> UI ++ #application : I want to add Course to a Programme

UI -> ":AddCourseToAProgrammeController" ++ #application: getAllProgrammes()

":AddCourseToAProgrammeController" -> ProgrammeRepository ++ #application: findAll()

ProgrammeRepository --> ":AddCourseToAProgrammeController" -- #application: programmeList

":AddCourseToAProgrammeController" --> UI --:  programmeList

UI --> ASC : Which Programme?

ASC -> UI  #application: programme1!

UI -> ":AddCourseToAProgrammeController" ++  #application:  getAllStudyPlansByProgrammeID(programme1ID)

":AddCourseToAProgrammeController" -> StudyPlanRepository ++ #application: getAllStudyPlansByProgrammeID(programme1ID)

StudyPlanRepository --> ":AddCourseToAProgrammeController" -- #application: studyPlanList

":AddCourseToAProgrammeController" --> UI -- : studyPlanList

UI --> ASC: Which Study Plan?

ASC -> UI: studyPlan1!



UI -> ":AddCourseToAProgrammeController" ++ #application: getAllCourses()

":AddCourseToAProgrammeController" -> CourseRepository ++ #application: findAll()

CourseRepository --> ":AddCourseToAProgrammeController" -- #application: courseList

":AddCourseToAProgrammeController" --> UI  -- : courseList

UI --> ASC : Which Course?

ASC -> UI #application: course1!

UI --> ASC : Which Curricular Year?

ASC -> UI #application: 2nd!

UI --> ASC : Which Semester?

ASC -> UI #application: 1st!

UI -> ":AddCourseToAProgrammeController" ++ #application : addCourseToProgramme (Semester, CurricularYear, CourseDDD, StudyPlanDDD)

":AddCourseToAProgrammeController" -> ":AddCourseToAProgrammeController" : getCourseID()
":AddCourseToAProgrammeController" -> ":AddCourseToAProgrammeController" : getStudyPlanID()
":AddCourseToAProgrammeController" -> ":CourseInStudyPlanRepository" ++ #application : registerCourseInStudyPlan(course1ID, studyPlan1ID, CurricularYear, Semester)

create "cisp1:CourseInStudyPlan" as CISP #lightblue
":CourseInStudyPlanRepository" --> CISP : <create> (Semester, CurricularYear,  course1ID, studyPlan1ID)
":CourseInStudyPlanRepository" -> ":CourseInStudyPlanRepository": isCourseInStudyPlanInRepository()
":CourseInStudyPlanRepository" -> ":CourseInStudyPlanRepository": addCourseInStudyPlan(cisp1)
":CourseInStudyPlanRepository" --> ":AddCourseToAProgrammeController" --: true

":AddCourseToAProgrammeController" --> UI -- : true

UI --> ASC: true

participant "programmeList:List<Programme>"
participant "courseList:List<Course>"
participant "studyPlanList:List<StudyPlan>"
participant "programme1:Programme"
participant "studyPlan1:StudyPlan"
participant "course1:Course"
@enduml