@startuml

title Convert Access Method Saved to ResponseDTO

autonumber
skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam defaultTextAlignment center
skinparam shadowing true

participant ":ConfigureAccessMethodRESTController" as Controller
participant ":IAccessMethodAssembler" as amAssembler
activate Controller #lightBlue
Controller -> amAssembler: toDTO (accessMethod)
activate amAssembler #lightBlue

create "amResponseDTO: AccessMethodResponseDTO"
amAssembler -> "amResponseDTO: AccessMethodResponseDTO": create (acessMethod.identity().toString, \n accessMethod.getName().getNameWithNumbersAndSpecialChars());
deactivate amAssembler
deactivate Controller

@enduml