@startuml
skinparam linetype ortho

title US11:  I want to register a programme in the system.

class US11_RegisterAProgrammeInTheSystem {
   }


package "DegreeType Aggregate" {
    entity "<<root>>\nDegreeType" {
    }
}

package "Programme Aggregate" {
    entity "<<root>>\nProgramme" {
    }
}


package "Teacher Aggregate" {
    entity "<<root>>\nTeacher" {
    }
}

package "Department Aggregate" {
    entity "<<root>>\nDepartment" {
    }
}

US11_RegisterAProgrammeInTheSystem ..> "<<root>>\nProgramme"

"<<root>>\nDegreeType" "1" <-- "*" "<<root>>\nProgramme"
"<<root>>\nTeacher" "1" <-- "*" "<<root>>\nProgramme"
"<<root>>\nDepartment" "1" <-- "*" "<<root>>\nProgramme"

@enduml