@startuml

title US26_getNumberOfStudentsInProgrammesFromSpecifiedDepartmentInGivenSchoolYear.puml
/'left to right direction'/

class US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController {
    +US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController( ProgrammeEditionEnrollmentRepo PEERepo,SchoolYearRepository schoolYearRepository,DepartmentRepository departmentRepository
    +countStudentsInProgrammeFromDepartmentInSchoolYear(department: Department, schoolYear: SchoolYear): int
}

class Department {
    -_name: String
    -_acronym: String
    +Department(acronym: String, name: String)
    + equals(obj: Object): boolean
}

class DepartmentRepository {
    +DepartmentRepository(departmentFactory: DepartmentFactory)
    +departmentExists(department: Department): boolean
}

class ProgrammeEditionEnrollmentRepo {
    +ProgrammeEditionEnrollmentRepo(programmeEditionEnrollmentFactory: ProgrammeEditionEnrollmentFactory)
    +countStudentsInProgrammesFromDepartmentInSchoolYear(department: Department, schoolYear: SchoolYear): int
}

class ProgrammeEditionEnrollment {
    _enrollmentDate: LocalDate
    +ProgrammeEditionEnrollment(student: Student, programmeEdition: ProgrammeEdition, _enrollmentDate: LocalDate)
    +isEnrollmentAssociatedToDepartmentAndSchoolYear(department: Department, schoolYear: SchoolYear): boolean
    +getStudentUniqueNumber(): int
}

class SchoolYearRepository {
    +SchoolYearRepository(schoolYearFactory: SchoolYearFactory)
    +schoolYearExists(schoolYear: SchoolYear): boolean
}

class SchoolYear {
    -_description: String
    -_startDate: LocalDate
    -_endDate: LocalDate
    +SchoolYear(description: String, startDate: String, endDate: String)
    +isSameSchoolYear(newSchoolYear: SchoolYear): boolean
}

class ProgrammeEdition {
    +ProgrammeEdition(programme: Programme, schoolYear: SchoolYear)
    +isEditionAssociatedToDepartmentAndSchoolYear(department: Department, schoolYear: SchoolYear): boolean
}

class Programme {
    -_name: String
    -_acronym: String
    -_quantityOfEcts: int
    -_quantityOfSemesters: int
    +Programme(name: String, acronym: String, quantityOfEcts: int, quantityOfSemesters: int, degreeType: DegreeType, department: Department, programmeDirector: Teacher)
    +isInDepartment (department: Department): boolean
}

Class Student {
    -_uniqueNumber: String
    -_name: String
    -_NIF: String
    -_phone: String
    -_email: String
    -_institutionalEmail: String
    +Student(uniqueNumber: String, name: String, NIF: String,phone: String, email: String, address: Address)
    +getUniqueNumber(): String
}

Department "*\n _departmentsList " <-- " 1  " DepartmentRepository
US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController "1" ..> "        1\n_departmentRepository " DepartmentRepository
US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController "1" ..> "                      _schoolYearRepository 1  " SchoolYearRepository
US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController "1"   ..> "      1\n_peeRepo"  ProgrammeEditionEnrollmentRepo
ProgrammeEditionEnrollmentRepo "1" --> "_programmeEditionEnrollmentList  * " ProgrammeEditionEnrollment
SchoolYearRepository "1" --> "_schoolYearList\n                       *" SchoolYear
ProgrammeEdition "           *\n_programme" <-- "1" Programme
ProgrammeEdition "_schoolYear\n1..*" <-- "1" SchoolYear
Programme"*\n_department"-->"1" Department
ProgrammeEdition"1\n_programmeEdition"<--"*" ProgrammeEditionEnrollment
ProgrammeEditionEnrollment"*\n_student "<--"1 " Student
@enduml
