@startuml

autonumber

title As a Programme Director, I want to know the Average Grade of a Course Edition of my Programme. \n(Process View lvl 4)

actor ProgrammeDirector as Admin #lightblue

participant ":UI" as UI #lightblue
participant "ceCtrl:CourseEditionRestController" as C #lightblue
participant "sgService:StudentGradeService" as S #lightblue
participant "ceRepo:CourseEditionRepository" as RCE #lightblue
participant "sgRepo:StudentGradeRepository" as SGR #lightblue
participant "sg[i]:StudentGrade" as SG

activate Admin #lightblue
Admin -> UI ++ #lightblue: I want to know the average grade in a Course Edition

UI -> C ++ #lightblue: getAllCourseEditions()
C -> S ++ #lightblue: getAllCourseEditions()
S -> RCE ++ #lightblue: findAllCourseEditions()

ref over RCE
    Query database for all CourseEditions
end ref

RCE --> S --: List<CourseEdition>
S --> C --: List<CourseEdition>

ref over C
    Convert domain objects to CourseEditionDTOs
end ref

C --> UI --: List<CourseEditionDTO>
UI --> Admin --: Please select a Course Edition from the list

Admin -> UI ++ #lightblue: selected courseEditionID

UI -> C ++ #lightblue: getAverageGrade(courseEditionID)
C -> S ++ #lightblue: getAverageGrade(courseEditionID)

S -> SGR ++ #lightblue: findAll()
SGR --> SGR : findAll()
SGR --> S --: List<StudentGrade>

group Loop for each StudentGrade
    loop for each studentGrade in List<StudentGrade>
        S -> SG ++ #lightblue: hasThisCourseEditionID(courseEditionID)
        SG --> S --: True!
        alt if studentGrade.hasThisCourseEditionID(courseEditionID) is true
            S -> SG ++ #lightblue: get_grade()
            SG --> S --: (Grade) grade[i]
            S -> SG ++ #lightblue: grade[i].knowGrade()
            SG --> S --: (double) grade
        end
    end
end

S -> S : Calculate Average Grade (sumGrade / numOfStudent)
S --> C --: average grade!
C --> UI --: average grade!
UI --> Admin --: average grade!

@enduml