@startuml
title: US19_CREATE COURSE EDITION_SEQUENCE DIAGRAM
autonumber

actor ASC
participant ":UI" as UI
participant ":CreateCourseEditionController" as CT
participant ":DegreeTypeRepository" as DTR
participant ":ProgrammeRepository" as PR
participant ":ProgrammeEditionRepository" as PER
participant ":StudyPlanRepository" as SPR
participant ":CourseInStudyPlanRepository" as CSPR
participant ":CourseEditionRepository" as CER
participant ":CourseEditionFactory" as CEF


ASC -> UI ++ #application :  I want to create a Course Edition
UI -> CT ++ #application: getAllDegreeTypes()
CT -> DTR ++ #application: getAllDegreeTypes()
DTR --> CT -- : dTL1
ref over CT
    Convert DregreeTypeList to DegreeTypeListDTO
end ref
CT --> UI -- : dTL1_DTO
UI --> ASC -- : which degree type??

ASC -> UI ++ #application :  degree Type 1!
UI -> CT ++ #application: getAllProgrammes(dTDTO1)
ref over CT
    Convert DegreeTypeDTO to DegreeTypeID
end ref
CT -> PR ++ #application: getAllProgrammes(degreeTypeID1)
PR --> CT -- : pL1
ref over CT
    Convert ProgrammeList to ProgrammeListDTO
end ref
CT --> UI -- : pLDTO1
UI --> ASC -- : which programme??

ASC -> UI ++ #application : programme 1!
UI -> CT ++ #application: getAllProgrammeEditions(pDTO1)
ref over CT
    Convert ProgrammeDTO to ProgrammeID
end ref
CT -> PER ++ #application: getAllProgrammeEditions(pID1)
PER --> CT -- : pEL1
ref over CT
    Convert ProgrammeEditionList to ProgrammeEditionListDTO
end ref
CT --> UI -- : pELDTO1
UI --> ASC -- : which programmeEdition??


ASC -> UI ++ #application : programme edition 1!
UI -> CT ++ #application: getLatestStudyPlanId(programmeDTO1)
ref over CT
    Convert ProgrammeEditionDTO to ProgrammeEditionID
end ref
CT -> SPR ++ #application: getLatestStudyPlanId(programmeID1)
SPR --> CT -- : studyPlanID1
CT -> CSPR ++ #application: getCoursesInStudyPlan(studyPlanID1)
CSPR --> CT -- : cSPL1
ref over CT
    Convert CourseInStudyPlanList to CourseInStudyPlanListDTO
end ref
CT --> UI -- : cSPLDTO1
UI --> ASC -- : which course from the study plan??


ASC -> UI ++ #application : course in study plan 1!
UI -> CT ++ #application : createCourseEdition(cSPDTO1,pEID1)
ref over CT
    Convert CourseInStudyPlanDTO to CourseInStudyPlanID
end ref
CT -> CER ++ #application : createAndSaveCourseEdition(cSpID1,pEID1)
CER -> CEF ++ #application : createCourseEdition(cSpID1,pEID1)


create "cE1:CourseEdition" as CE #lightblue
CEF --> CE : <create> (cSpID1,pEID1)
CE -> CE : isCourseInStudyPlanValid (cSpID1,pEID1)
CEF --> CER -- : cE1
CER -> CER : isCourseEditionAlreadyInRepository (cE1)
CER -> CER : addCourseEdition (cE1)

CER --> CT --: true
CT --> UI --: true
UI --> ASC --: true

participant "dTL1:List<DegreeType>" as dTL1
participant "pL1:List<Programme>" as PL
participant "p1:Programme" as PG
participant "pID1:ProgrammeID" as PG
participant "ciSPL1:List<CourseInStudyPlan>" as CSPL
participant "pL1:List<Programme>" as PL
participant "pE1:ProgrammeEdition" as PE


@enduml