@startuml
actor Admnistrator as Adm
participant ":DegreeTypeList" as DTL #lightgreen

Adm -> DTL : Register DegreeType (name, maxEcts)
activate DTL
create "DT1:DegreeType" as DT #yellow
DTL -> DT : Create DegreeType (name, maxEcts)
activate DT
DT -> DT : nameIsInvalid(name)
DT -> DT : maxEctsIsInvalid(maxEcts)
DT --> DTL : DegreeType Object
deactivate DT
DTL -> DTL : add DegreeType
DTL --> Adm : Registration Successful
deactivate DTL
@enduml
