@startuml
title US10: Configure a DegreeType in System

class US10_IWantToConfigureDegreeTypesLevelsController {
    -_degreeTypeRepository: DegreeTypeRepository
    +US10_IWantToConfigureDegreeTypesLevelsController(degreeTypeRepository : DegreeTypeRepository, degreeTypeFactory : DegreeTypeFactory)
    +registerDegreeType(name: String, maxEcts: int): boolean
}

package "DegreeType" {
entity "<<root>>\nDegreeType"  {
    -degreeTypeId: DegreeTypeID
    -name: Name
    -maxEcts: MaxECTS
    + nameIsInvalid(): boolean
    + maxEctsIsInvalid(): boolean

    }
}

class DegreeTypeID <<ValueObject>> {
    id: Long
        }

class Name <<ValueObject>> {
            Name: String
                }

class MaxECTS <<ValueObject>> {
            maxEcts: int
                }

class DegreeTypeRepository {
    -_degreeTypeFactoryInterface: DegreeTypeListFactoryInterface
    -_degreeTypeRepository: List<DegreeType>
    +DegreeTypeRepository()
    +registerDegreeType(name: String, maxEcts: int): boolean
}

interface IDegreeTypeRepository {
    +DegreeTypeRepository()
    +registerDegreeType(name: String, maxEcts: int)}

class DegreeTypeFactoryImpl {
    +addNewDegreeType(name: String, maxEcts: int): DegreeType
}

interface DegreeTypeFactoryInterface {
    +addNewDegreeType (name: String, maxEcts: int): DegreeType
    }

class List<DegreeType> {}

interface DegreeTypeListFactoryInterface {
    +createDegreeTypeList(): List<DegreeType>
    }

class DegreeTypeListFactoryImpl {
    +createDegreeTypeList(): List<DegreeType>
    }

US10_IWantToConfigureDegreeTypesLevelsController "1" ..> "1\n_degreeTypeRepository    " IDegreeTypeRepository
DegreeType "degreeTypesList *      " <.. "1" IDegreeTypeRepository
DegreeTypeListFactoryInterface "1" ..> "1" List
IDegreeTypeRepository "1" ..> "1" DegreeTypeFactoryInterface
DegreeTypeFactoryInterface "1" <|.. "1" DegreeTypeFactoryImpl
DegreeType "1" <.. "1" DegreeTypeFactoryInterface
List "1" --> "*" DegreeType
IDegreeTypeRepository "1" --> "1" List
IDegreeTypeRepository "1" ..> "1" DegreeTypeListFactoryInterface
DegreeTypeListFactoryImpl "1" ..|> "1" DegreeTypeListFactoryInterface
DegreeTypeRepository "1" ..|> "1" IDegreeTypeRepository
"<<root>>\nDegreeType" --> "1" DegreeTypeID
"<<root>>\nDegreeType" --> "1" Name
"<<root>>\nDegreeType" --> "1" MaxECTS



@enduml