@startuml
title US10: Configure a DegreeType in System

class US10_IWantToConfigureDegreeTypesLevelsController {
    +US10_IWantToConfigureDegreeTypesLevelsController(degreeTypeRepository : DegreeTypeRepository, degreeTypeFactory : DegreeTypeFactory)
    +registerDegreeType(name: String, maxEcts: int): boolean
}

class DegreeType {
    - name: string
    - maxEcts: int
    + nameIsInvalid(): boolean
    + maxEctsIsInvalid(): boolean
}

class DegreeTypeRepository {
    +DegreeTypeRepository()
    +registerDegreeType(degreeType: DegreeType): boolean
}

class DegreeTypeFactory {
    +addNewDegreeType(name: String, maxEcts: int): DegreeType
}

US10_IWantToConfigureDegreeTypesLevelsController "1" ..> "1\n_degreeTypeRepository    " DegreeTypeRepository
US10_IWantToConfigureDegreeTypesLevelsController "1" ..> "1\n_degreeTypeFactory    " DegreeTypeFactory
DegreeType "degreeTypesList *      " <-- "1" DegreeTypeRepository
DegreeTypeFactory ..> DegreeType

@enduml