@startuml

title Convert Teacher Category Saved to DTO

autonumber
skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam defaultTextAlignment center
skinparam shadowing true

participant ":ITeacherCategoryService" as Service
participant ":ITeacherCategoryInternalAssembler" as tcAssembler
activate Service #E1F5FE
Service -> tcAssembler: toDTO (tc)
activate tcAssembler #E1F5FE

create "tcSavedDTO: TeacherCategoryDTO"
tcAssembler -> "tcSavedDTO: TeacherCategoryDTO": create (tc.getId().getValue().toString(), \n tc.getName().getName())

tcAssembler --> Service: tcSavedDTO
deactivate tcAssembler
deactivate Service

@enduml