@startuml
actor admin
autonumber

title: US02_Sequence Diagram_Configure Access Method in System (Happy Path)

admin -> UI ++ #application : I want to configure access method
UI --> admin -- : access method name?
admin -> UI ++ #application :(accessMethodNameVO)
UI -> ":ConfigureAccessMethodController" as ConfigureAccessMethodController ++ #application : configureAccessMethod (accessMethodNameVO)


ConfigureAccessMethodController -> ":AccessMethodFactory" as AccessMethodFactory ++ #application : createAccessMethod (accessMethodNameVO)
create "ac1:AccessMethod" as AccessMethod
AccessMethodFactory -> AccessMethod  #application  : <create> (accessMethodNameVO)
AccessMethodFactory --> ConfigureAccessMethodController -- : :ac1

ConfigureAccessMethodController -> ":AccessMethodRepository" as AccessMethodRepository ++ #application : registerAccessMethod (ac1)

AccessMethodRepository -> AccessMethodRepository : isAccessMethodAlreadyRegistered (ac1)

AccessMethodRepository --> ConfigureAccessMethodController --: true

ConfigureAccessMethodController --> UI --: true
UI --> admin --: AM Created and Registered
@enduml