@startuml

skinparam ranksep 100
skinparam nodesep 100

package "AccessMethod Aggregate" as AMAggregate{
    entity "<<Root>>\n <<Entity>>\n AccessMethod"{
    + AccessMethod(accessMethodId: AccessMethodId, accessMethodName: NameWithNumbersAndSpecialChars)
    + Equals()
    }
}

class "<<Value Object>>\n NameWithNumbersAndSpecialChars" as VOName{
    - accessMethodName: String
}

class "<<Value Object>>\n AccessMethodId" as VOId{
    - id: String
}

'uses
AMAggregate "1" -> "1" VOName
AMAggregate "1" -> "1" VOId


Interface IAccessMethodFactory {
    +createAccessMethod(accessMethodID: AccessMethodID, accessMethodName: NameWithNumbersAndSpecialChars)
}

class AccessMethodFactoryImpl {
     +createAccessMethod(accessMethodID: AccessMethodID, accessMethodName: NameWithNumbersAndSpecialChars)
}
'implements
AccessMethodFactoryImpl ..|> "implements"  IAccessMethodFactory


Interface IAccessMethodListFactory {
 +createAccessMethodList() : List<AccessMethod>
}

class AccessMethodListFactoryImpl {
    +createAccessMethodList() : ArrayList<AccessMethod>
}
'implements
AccessMethodListFactoryImpl ..|> "implements" IAccessMethodListFactory


Interface IAccessMethodRepository {
    +AccessMethodRepository(IAccessMethodFactory : iAccessMethodFactory, IAccessMethodListFactory : iAccessMethodListFactory)
    +registerAccessMethod(accessMethodName: String) : boolean
    -isAccessMethodRegistered(accessMethodID: AccessMethodID) : boolean
    +getAccessMethodByName(String AccessMethodName) : AccessMethod
}

class AccessMethodRepositoryImpl {
    +AccessMethodRepository(IAccessMethodFactory : iAccessMethodFactory, IAccessMethodListFactory : iAccessMethodListFactory)
    +registerAccessMethod(accessMethodName: String) : boolean
    -isAccessMethodRegistered(accessMethod: AccessMethod) : boolean
    +getAccessMethodByName() : AccessMethod
}

'implements
AccessMethodRepositoryImpl ..|> "implements" IAccessMethodRepository
'uses
IAccessMethodRepository "1 " --> "uses 1"IAccessMethodFactory
IAccessMethodRepository "1" --> "uses 1" IAccessMethodListFactory

class US02_ConfigureAccessMethod_Controller {
    +US02_ConfigureAccessMethod_Controller(accessMethodRepository : AccessMethodRepository)
    +configureAccessMethod(accessMethodName: String) : boolean
}
'uses
US02_ConfigureAccessMethod_Controller "1" --> "uses 1" IAccessMethodRepository

'creates
IAccessMethodFactory "1" ..> " creates 1..*" AMAggregate
@enduml