@startuml

package "AccessMethod Aggregate" {
    entity "<<Root>>\n <<Entity>>\n AccessMethod" as AME{
    + AccessMethod(accessMethodId: AccessMethodId, accessMethodName: NameWithNumbersAndSpecialChars)
    + Equals(Object objectToCompare)
    }
    class "<<Value Object>>\n NameWithNumbersAndSpecialChars" as VOName{
        - accessMethodName: String
        + Equals(Object objectToCompare)
    }

    class "<<Value Object>>\n AccessMethodId" as VOId{
        - id: String
        + Equals(Object objectToCompare)
    }
}

'uses
AME "1" --> "uses 1" VOName
AME "1" --> "uses 1" VOId

interface IRepository {
}

class AccessMethodSpringDataImpl {
}

interface IAccessMethodFactory {
    createAccessMethod(accessMethodID: AccessMethodID, accessMethodName: NameWithNumbersAndSpecialChars)
}

class AccessMethodFactoryImpl {
     +createAccessMethod(accessMethodID: AccessMethodID, accessMethodName: NameWithNumbersAndSpecialChars)
}

interface IAccessMethodService {
  + registerAccessMethod (accessMethod1: AccessMethod)
}

class AccessMethodServiceImpl {
  + registerAccessMethod (accessMethod1: AccessMethod)
}

interface JpaRepository<AccessMethodDataModel, AccessMethodDataModelID>{
}

class AccessMethodDataModel {
}


interface IAccessMethodRepository {
}

interface IAccessMethodMapper{
    + toDomain()
    + toDataModel()
}

class AccessMethodMapperImpl {
}

interface IAccessMethodRepositorySpringData{
}


class US02_ConfigureAccessMethod_Controller {
    +US02_ConfigureAccessMethod_Controller(accessMethodService: IAccessMethodService)
    +createAccessMethod(accessMethodName: NameWithNumbersAndSpecialChars)
}


IAccessMethodRepositorySpringData -down-> IAccessMethodMapper: uses
AccessMethodMapperImpl -right..|> IAccessMethodMapper: implements
AccessMethodSpringDataImpl -down-> IAccessMethodRepositorySpringData: uses
IAccessMethodRepositorySpringData -up-|> JpaRepository : extends
AccessMethodSpringDataImpl ..|> IAccessMethodRepository: implements
IAccessMethodRepository -up..|> IRepository: implements
IAccessMethodFactory "1" ..> "1..*" AME : creates
US02_ConfigureAccessMethod_Controller -down-> IAccessMethodService: uses
AccessMethodServiceImpl .left.|> IAccessMethodService: implements
AccessMethodFactoryImpl .right.|> IAccessMethodFactory: implements
IAccessMethodService -down-> IAccessMethodFactory: uses
IAccessMethodRepository -down-> AccessMethodDataModel: persist
IAccessMethodMapper ..> "AccessMethod Aggregate": transforms to/from
IAccessMethodMapper ..> AccessMethodDataModel: transforms to/from
IAccessMethodService --> IAccessMethodRepository: uses
@enduml