@startuml
actor admin
autonumber

title: US02_Sequence Diagram_Configure Access Method in System (Happy Path)

admin -> UI ++ #application : I want to configure access method
UI --> admin -- : access method name?
admin -> UI ++ #application :(NameWithNumbersAndSpecialChars)
    UI -> ":ConfigureAccessMethodController" as ConfigureAccessMethodController ++ #application : configureAccessMethod (NameWithNumbersAndSpecialChars)


ConfigureAccessMethodController -> ":AccessMethodService" ++ #application : configureAccessMethod (NameWithNumbersAndSpecialChars)
":AccessMethodService" -> ":AccessMethodRepositorySpringDataImpl" ++ #application:  getAccessMethodByName(NameWithNumbersAndSpecialChars)
":AccessMethodRepositorySpringDataImpl" --> ":AccessMethodService" -- #application: Optional.empty()
":AccessMethodService" -> ":AccessMethodFactory" as AccessMethodFactory ++ #application: createAccessMethod(NameWithNumbersAndSpecialChars)
create "ac1:AccessMethod" as AccessMethod
AccessMethodFactory -> AccessMethod  ++ #application  : <create> (NameWithNumbersAndSpecialChars)
AccessMethodFactory --> ":AccessMethodService" -- : Optional<ac1>
":AccessMethodService" -> ":AccessMethodRepositorySpringDataImpl" ++ #application: save(ac1)
":AccessMethodRepositorySpringDataImpl" -> ":AccessMethodMapper" ++ #application: toDataModel(ac1)
create "ac1DM: AccessMethodDataModel" as AccessMethodDataModel
":AccessMethodMapper" -> AccessMethodDataModel ++ #application: <create>
":AccessMethodMapper" --> ":AccessMethodRepositorySpringDataImpl": Optional<ac1DM>
":AccessMethodRepositorySpringDataImpl" -> ":AccessMethodRepositorySpringDataImpl": save(ac1DM)
":AccessMethodMapper" --> ":AccessMethodRepositorySpringDataImpl": Optional<ac1>
":AccessMethodRepositorySpringDataImpl" --> ":AccessMethodService": Optional<ac1>
":AccessMethodService" --> ConfigureAccessMethodController: Optional<ac1>
ConfigureAccessMethodController --> UI: true
UI --> admin: true
@enduml