@startuml

skinparam ranksep 180
skinparam nodesep 180

package "AccessMethod Aggregate" {
    entity "<<Root>>\n <<Entity>>\n AccessMethod" as AME{
    + AccessMethod(accessMethodId: AccessMethodId, accessMethodName: NameWithNumbersAndSpecialChars)
    + Equals(Object objectToCompare)
    }
    class "<<Value Object>>\n NameWithNumbersAndSpecialChars" as VOName{
        - accessMethodName: String
        + Equals(Object objectToCompare)
    }

    class "<<Value Object>>\n AccessMethodId" as VOId{
        - id: String
        + Equals(Object objectToCompare)
    }
}

'uses
AME "1" --> "uses 1" VOName
AME "1" --> "uses 1" VOId


Interface IAccessMethodFactory {
    createAccessMethod(accessMethodID: AccessMethodID, accessMethodName: NameWithNumbersAndSpecialChars)
}

class AccessMethodFactoryImpl {
     +createAccessMethod(accessMethodID: AccessMethodID, accessMethodName: NameWithNumbersAndSpecialChars)
}
'implements
AccessMethodFactoryImpl ..|> "implements"  IAccessMethodFactory


Interface IAccessMethodListFactory {
 createAccessMethodList() : List<AccessMethod>
}

class AccessMethodListFactoryImpl {
    +createAccessMethodList() : ArrayList<AccessMethod>
}
'implements
AccessMethodListFactoryImpl ..|> IAccessMethodListFactory : implements


Interface IRepository{
}
Interface IAccessMethodRepository{
  registerAccessMethod (accessMethod1: AccessMethod)
  isAccessMethodAlreadyRegistered(accessMethod1: AccessMethod)
}

'extends
IAccessMethodRepository --|> IRepository : extends

class AccessMethodRepositoryImpl {
    +AccessMethodRepository(IAccessMethodListFactory : IAccessMethodListFactory)
    +registerAccessMethod(accessMethod1: AccessMethod) : boolean
    -isAccessMethodAlreadyRegistered(accessMethod1: AccessMethod) : boolean
}

'implements
AccessMethodRepositoryImpl ..|>  IAccessMethodRepository : implements

'uses
AccessMethodRepositoryImpl "1" --> "uses 1" IAccessMethodListFactory

class US02_ConfigureAccessMethod_Controller {
    +US02_ConfigureAccessMethod_Controller(accessMethodRepository : IAccessMethodRepository, accessMethodFactory : IAccessMethodFactory)
    +createAccessMethod(accessMethodName: NameWithNumbersAndSpecialChars)
}

'creates
IAccessMethodFactory "1" ..> "1..*" AME : creates
'dependency
IAccessMethodRepository "1"..> "*" AME
US02_ConfigureAccessMethod_Controller "1"--> "1" IAccessMethodRepository : uses
US02_ConfigureAccessMethod_Controller "1"--> "1" IAccessMethodFactory : uses
US02_ConfigureAccessMethod_Controller ..> AME
@enduml