@startuml
title US21: As an ASC, I want to get the number of students enrolled in a programme edition\n(References in Scenario View - Level 4 Full Backend Flow and Process View - Level 3 Granularity)

autonumber
skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}

participant ":IProgrammeEditionService" as Service <<component>> <<Service>> #teal
participant ":IProgrammeEditionServiceAssembler" as assembler <<component>> <<Assembler>> #teal

activate Service #LightBlue
Service -> assembler: toServiceResponseDTO\n (List<programmeEdition>programmeEdition)
activate assembler #LightBlue

create "programmeEditionServiceResponseDTO: ProgrammeEditionServiceResponseDTO"
assembler -> "programmeEditionServiceResponseDTO: ProgrammeEditionServiceResponseDTO": toServiceResponseDTOFromIDs (\n programmeId, schoolYearId)
deactivate assembler
deactivate Service

@enduml