package PAI.persistence.springdata;

import PAI.persistence.datamodel.ProgrammeEditionEnrolmentDataModel;
import PAI.persistence.datamodel.ProgrammeEditionEnrolmentIDDataModel;
import PAI.persistence.datamodel.StudentIDDataModel;
import PAI.persistence.datamodel.programmeEdition.ProgrammeEditionIdDataModel;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;
import java.util.Optional;

public interface IProgrammeEditionEnrolmentRepositorySpringData extends JpaRepository<ProgrammeEditionEnrolmentDataModel, ProgrammeEditionEnrolmentIDDataModel> {
    List<ProgrammeEditionEnrolmentDataModel> findAllById_ProgrammeEditionIdDataModel(ProgrammeEditionIdDataModel programmeEditionIdDataModel);

    Optional<ProgrammeEditionEnrolmentDataModel> findById_StudentIdDataModelAndId_ProgrammeEditionIdDataModel(StudentIDDataModel studentId, ProgrammeEditionIdDataModel programmeEditionId);
}
