@startuml
title <size:30>"REF 2 | DepartmentListDomain -> ToDTOList<DepartmentDTO>"</size>

|||
participant ":UpdateDepartmentDirector\nService" as Service
participant ":DepartmentAssembler" as Assembler
participant ":DepartmentIDMapper" as DIDM
participant ":DepartmentDTOFactory" as DTOFactory
participant "DomainList : List<Department>" as DomainList #application
participant "DTOList : List<DepartmentDTO>" as DTOList #application

skinparam sequenceLifeLineBackgroundColor #application
|||

Service -> Assembler ++ : toDTOList(DomainList)

Assembler -> DTOList : list = new ArrayList<>()

== Iterar cada Department ==

loop for each department in DomainList
    Assembler -> department : getId()
    Assembler -> department : getName()
    Assembler -> department : getAcronym()
    Assembler -> department : getDirectorId()

    Assembler -> DIDM ++ : toDTO(department.getId())
    DIDM --> Assembler -- : departmentIdDTO

    Assembler -> DTOFactory ++ : createDTO(departmentIdDTO, name, acronym, directorId)
    create "dto : DepartmentDTO" as DTO
    DTOFactory -> DTO : <create>()
    DTOFactory --> Assembler -- : dto

    Assembler -> DTOList ++ : list.add(dto)
    DTOList --> Assembler -- : list
end

Assembler --> Service -- : DTOList

Service --

|||

@enduml
