@startuml
autonumber
title US06: Update Department Director Of A Department\nProcess View - Level 3 (Happy Path, Fiel ao Código)

participant "Controller" as CTRL
participant "DepartmentAssembler" as ASM
participant "UpdateDepartmentDirectorService" as S
participant "DepartmentRepository" as DR
participant "TeacherRepository" as TR
participant "Department" as D
database    Database    as DB
participant "DepartmentWithDirectorAssembler" as DTOASM

skinparam sequenceLifeLineBackgroundColor #application

CTRL -> ASM ++ : fromRequestToCommand(departmentID, request)
ASM --> CTRL -- : DepartmentWithDirectorCommand

CTRL -> S ++ : updateDirector(departmentID, teacherID)

S -> DR ++ : findDepartmentByID(departmentID)
DR -> DB ++ : findById(departmentID)
DB --> DR -- : Department
DR --> S -- : Department

S -> TR ++ : ofIdentity(teacherID)
TR -> DB ++ : findById(teacherID)
DB --> TR -- : Teacher
TR --> S -- : Teacher

S -> D ++ : changeDirector(teacherID)
D --> S -- : updated department

S -> DR ++ : save(department)
DR --> S -- : success

S -> DTOASM ++ : toDWDDTO(department)
DTOASM --> S -- : DepartmentWithDirectorDTO

S --> CTRL -- : DepartmentWithDirectorDTO

@enduml

