@startuml

title US06: Update Department Director Of A Department\nProcess View - Level 1

actor "Administrator" as A

skinparam sequenceLifeLineBackgroundColor #application


participant "«System»\nPAI" as S
A -> S ++: I want to update the Department Director of a Department!
|||
S --> A: Which Department?
|||
A -> S: This the Department!
|||
S --> A: Which Teacher?
|||
A -> S: This the Teacher!
|||
S --> A: Done!

@enduml