@startuml

title US06: Update Department Director Of A Department\nProcess View - Level 2

actor "Administrator" as A
participant ":Frontend" as FE
participant ":Backend" as BE
participant ":DataBase" as DB

skinparam nodesep 5

skinparam sequenceLifeLineBackgroundColor #application

A -> FE ++ : I want to update the Department Director of a Department

FE --> A --: Which Department?

A -> FE ++ : This Department!

FE --> A -- : Which Teacher from this Department?

A -> FE ++ : This Teacher from this Department!
FE -> BE ++ : HTTP PUT /departments/{departmentID}/director\nbody { teacherId }
BE -> DB ++: UPDATE departments SET director_id = {teacherId} WHERE id = {id}
DB --> BE -- : Success
BE --> FE -- : 200 OK
FE --> A -- : Department director updated successfully!

@enduml
