@startuml
title US38 – Define RUC for Course Edition\n(Process View – Granularity Level 2)

skinparam titleFontName "Verdana"
skinparam defaultFontName "Verdana"
skinparam defaultTextAlignment center
skinparam shadowing true
skinparam actorBackgroundColor #lightblue
skinparam participantBackgroundColor #lightblue/white

autonumber

participant ":Frontend" as Frontend <<container>>
participant ":Backend" as Backend <<container>>
participant ":Database" as DB <<container>>

-> Frontend: I want to define the RUC for a course edition
activate Frontend #E1F5FE


' --- Select course edition ---
Frontend -> Backend: GET /courseeditions
activate Backend #E1F5FE
Backend -> DB: SELECT * FROM course_edition
activate DB #E1F5FE
DB --> Backend: courseEditions
deactivate DB
Backend --> Frontend: 200 OK + courseEditions
deactivate Backend
<-- Frontend: Display course edition selection list

-> Frontend: Select a course edition
' --- Select teachers ---
Frontend -> Backend: GET /teachers
activate Backend #E1F5FE
Backend -> DB: SELECT * FROM teacher
activate DB #E1F5FE
DB --> Backend: teachers
deactivate DB
Backend --> Frontend: 200 OK + teachers
deactivate Backend
<-- Frontend : Display teacher selection list

-> Frontend: Select a teacher
' --- Confirm selection ---
<-- Frontend: Confirm selected teacher and course edition?

-> Frontend: Yes

' --- Define RUC ---
Frontend -> Backend: PATCH /course-editions/{id}/ruc + body {...}

note over DB #E0E0E0
  Body:
    {"teacherID": "AAA","
    }}
end note

activate Backend #E1F5FE

Backend -> DB: UPDATE course_edition \n SET ruc_teacher_id = 'AAA' \n WHERE course_edition_id = (...)
activate DB #E1F5FE
DB --> Backend: RUC updated
deactivate DB

Backend --> Frontend: 200 OK + body {DefineRucResponseDTO + hypermedia}

note left of Frontend #E0E0E0
  DefineRucResponseDTO + hypermedia:
    {"teacherID": "AAA",
      "CourseEditionGeneratedID": "550e8400-e29b-41d4-a716-446655440002",

    },
    "_links": {
      "define-ruc": {
        "href": "http://localhost:8081/{id}courseeditions/ruc"
      }}}
end note
deactivate Backend

<-- Frontend: RUC successfully updated.
deactivate Frontend

@enduml
