@startuml
actor ProgrammeDirector
participant ":UI" as UI
participant ":Controller1" as KA
participant ":GradeStudentRepository" as GR
participant ":GradeStudent" as GradeStudent


ProgrammeDirector -> UI ++ #application: I want to know approval percentage of Course Edition
UI --> ProgrammeDirector -- : Course Edition?
ProgrammeDirector -> UI ++ #application: Course Edition!
UI -> KA ++ #application : IWantToKnowTheApprovalPercentageOfACourseEdition(CourseEdition)
KA -> GR ++ #application : knowApprovalRate(CourseEdition)



loop for each GradeStudent in GR
    GR -> GradeStudent : hasThisCourseEdition(courseEdition1)
    activate GradeStudent
    GradeStudent --> GR : True!
    deactivate GradeStudent

    GR -> GradeStudent : knowGrade()
    activate GradeStudent
    GradeStudent --> GR : grade
    deactivate GradeStudent
end


GR --> KA --: Know Approval Percentage of CourseEdition1
KA --> UI --: Know Approval Percentage of CourseEdition1
UI --> ProgrammeDirector --: Know Approval Percentage of courseEdition1

@enduml