@startuml
actor ProgrammeDirector
participant ":UI" as UI
participant ":US23_IWantToKnowTheApprovalPercentageOfACourseEditionController" as KA
participant ":CourseEditionRepository" as CER
participant ":GradeStudentRepository" as GR
participant ":GradeStudent" as GradeStudent


ProgrammeDirector -> UI ++ #application: I want to know approval percentage of Course Edition
UI --> ProgrammeDirector -- : Course Edition?
ProgrammeDirector -> UI ++ #application: CourseEdition1 !
UI -> KA ++ #application : IWantToKnowTheApprovalPercentageOfACourseEdition(courseEdition1)
KA -> CER ++ #application : findCourseEditionID (courseEdition1)
CER -> CER : findIdByCourseEdition (CourseEdition1)
CER -> KA :  ceIdVO1
deactivate CER
KA -> GR ++ #application : knowApprovalRate(ceIdVO1)



loop for each GradeStudent in GR
    GR -> GradeStudent : hasThisCourseEdition(ceIdVO1)
    activate GradeStudent
    GradeStudent --> GR : True!
    deactivate GradeStudent

    GR -> GradeStudent : knowGrade()
    activate GradeStudent
    GradeStudent --> GR : grade
    deactivate GradeStudent
end


GR --> KA --: Know Approval Percentage of CourseEdition1
KA --> UI --: Know Approval Percentage of CourseEdition1
UI --> ProgrammeDirector --: Know Approval Percentage of courseEdition1

@enduml