@startuml
title US23: I want to know the approval percentage of a CourseEdition
'left to right direction

class US23_IWantToKnowTheApprovalPercentageOfACourseEdition {
    +US23_IWantToKnowTheApprovalPercentageOfACourseEdition(gradeStudentRepository : GradeStudentRepository)
    +IWantToKnowTheApprovalPercentageOfACourseEdition(courseEdition : CourseEdition): double

}

class GradeStudent {
    -grade: double
    -date: String
    +knowGrade()
}

class GradeStudentRepository {
    -gradeStudentList: List<GradeStudent>
    - _gradeStudentFactory: GradeStudentFactory
    +addGradeToStudent()
    +knowAverageGrade()
    +knowApprovalRate()
}

class GradeStudentFactory {
    +newGradeStudent()
}

class GradeStudentListFactory {
    +newArrayList()
}

Interface GradeStudentListFactoryImpl {
    +newArrayList()
}

Interface GradeStudentFactoryImpl {
    +newGradeStudent()
}

class Student {
    -_uniqueNumber:int
    -_name:String
    -_NIF:String
    -_phone:String
    -_email:String
    +Student(uniqueNumber: int, name: String, NIF: String, phone: String, email: String, address: Address)
    +isStudentRepeated(students: List<Student>)
    +hasSameUniqueNumber(Student student)
}

class CourseEdition {
    -_programmeEdition: ProgrammeEdition
    -_course: Course
    -_ruc: Teacher
    +CourseEdition(programmeEdition: ProgrammeEdition, course: Course)
    +Equals(objectToCompare: Object)
    +setRuc(Teacher: ruc)
    +whatProgrammeEditionBelongsThisCourseEdition ()
}


GradeStudent "*" --> "1" Student: belongs
GradeStudent "*" --> "1" CourseEdition: refers to
GradeStudentRepository "1" ....> "_gradeStudentFactory 1" GradeStudentFactory
GradeStudentFactory "1" ....> "1" GradeStudent
GradeStudentRepository "1" ....> "_gradeStudentList" GradeStudentListFactory
GradeStudentListFactory  ..|>  GradeStudentListFactoryImpl
GradeStudentFactory  ..|>  GradeStudentFactoryImpl
GradeStudentListFactory "1" ....> "Creates List of" GradeStudent


US23_IWantToKnowTheApprovalPercentageOfACourseEdition "1" ..> "1\n_gradeStudentList    " GradeStudentRepository
@enduml