@startuml
title US23: I want to know the approval percentage of a CourseEdition
'left to right direction

class US23_IWantToKnowTheApprovalPercentageOfACourseEdition  {
    +US23_IWantToKnowTheApprovalPercentageOfACourseEdition(gradeStudentRepository : GradeStudentRepository)
    +IWantToKnowTheApprovalPercentageOfACourseEdition(courseEdition : CourseEdition): double

}

package "StudentGrade" {
entity "<<root>>\nStudentGrade" {
    -_grade: Grade
    -_date: LocalDate
    -_studentGradeID: StudentGradeID
    -_studentID: StudentID
    -_courseEditionID: CourseEditionID
    +hasThisCourseEdition(courseEditionID : CourseEditionID): boolean
    +knowCourseEdition()
    +get_student()
    +get_courseEdition()
    +equals(o: Object): boolean

    }

    class Grade <<ValueObject>> {
    -_grade: double
    +knowGrade(): double
    }

    class LocalDate <<ValueObject>> {
    -date: String
    +isDateValid(date: String): void
    +get_date(): LocalDate
    }
}

class StudentGradeID <<ValueObject>> {
    -_studentGradeID: Long
    -_courseEditionID: Long
    -_studentID: Long
}

class GradeStudentRepository {
    -gradeStudentList: List<GradeStudent>
    - _gradeStudentFactory: GradeStudentFactory
    +addGradeToStudent()
    +knowAverageGrade()
    +knowApprovalRate()
}

class GradeStudentFactoryImpl {
    +newGradeStudent()
}
class List<GradeStudent> {

}

class GradeStudentListFactoryImpl {
    +newArrayList()
}

Interface GradeStudentListFactory {
    +newArrayList()
}

Interface GradeStudentFactory {
    +newGradeStudent()
}

class Student {
    -_uniqueNumber:int
    -_name:String
    -_NIF:String
    -_phone:String
    -_email:String
    +hasSameUniqueNumber(Student student)
    +hasSameNIF (Student student)
    +getUniqueNumber()
    +hasThisUniqueNumber(int uniqueNumber)
}

class CourseEdition {
    -_programmeEdition: ProgrammeEdition
    -_course: Course
    -_ruc: Teacher
    +Equals(objectToCompare: Object)
    +setRuc(Teacher: ruc)
    +whatProgrammeEditionBelongsThisCourseEdition ()
    +getCourse()
}

"<<root>>\nStudentGrade" "*" --> "1" Grade
"<<root>>\nStudentGrade" "*" --> "1" LocalDate
"<<root>>\nStudentGrade" --> "1" StudentGradeID
"<<root>>\nStudentGrade" "*" --> "1" Student: belongs
"<<root>>\nStudentGrade""*" --> "1" CourseEdition: refers to
GradeStudentRepository "1" ....> GradeStudentFactory
GradeStudentFactory "1" ....> "Creates" "<<root>>\nStudentGrade"
GradeStudentRepository "1" ....> "*" "<<root>>\nStudentGrade"
GradeStudentRepository "1" ....> GradeStudentListFactory
GradeStudentListFactory  <|..  GradeStudentListFactoryImpl
GradeStudentListFactory  ....>  List
GradeStudentRepository  -->  List
List --> "*" "<<root>>\nStudentGrade"
GradeStudentFactory  <|..  GradeStudentFactoryImpl



US23_IWantToKnowTheApprovalPercentageOfACourseEdition "1" ..> "1    " GradeStudentRepository
@enduml