@startuml

skinparam componentStyle component
skinparam ArrowColor black
skinparam defaultTextAlignment center

title "PAI - Logical View Level 3"

  interface "PAI API" as RESTAPI
  interface "Bootstrap Data API" as FileIO
  interface "BD API" as BDAPI

component "Backend" {
    portin " " as p1
    portin " " as p3
    portin " " as p2

  rectangle "Drivers and frameworks" {

    component "Router"

    Router -up- p1
  }

  rectangle "Interface Adapters" {
    component Controller
    interface "Controller API" as IController

    Controller -up- IController
  }

  rectangle "Service layer" {
    component Service
    interface "Service API" as IService

    Service -up- IService
  }

  rectangle "Domain layer" {
    component Domain
    interface "Domain API" as IDomain

    Domain -up- IDomain
  }

  p1 -up- RESTAPI
  p2 -up-( FileIO
  p3 -up-( BDAPI

  Router -down-( IController

  Controller -down-( IService
  Service -down-( IDomain
}

@enduml