@startuml

title: US21_GET_THE_NUMBER_OF_STUDENTS_ENROLLED_IN_A_PROGRAMME_EDITION_SEQUENCE CLASS DIAGRAM

class US21_IWantToGetTheNumberOfStudentsEnrolledInAProgrammeEditionController {
    -_programmeEditionRepository: ProgrammeEditionRepository
    -_programmeEditionEnrollmentRepo: ProgrammeEditionEnrollmentRepo
    +US21_IWantToGetTheNumberOfStudentsEnrolledInAProgrammeEditionController(programmeEditionEnrollmentRepo: ProgrammeEditionEnrollmentRepo, programmeEditionRepository: ProgrammeEditionRepository, programmeList ProgrammeList)
    +iWantToGetTheNumberOfStudentsEnrolledInAProgrammeEdition(programmeEdition: ProgrammeEdition)
    +getAllProgrammeEditions(): List<ProgrammeEdition>
}

class ProgrammeEditionEnrollmentRepo {
    -_programmeEditionEnrollments: Set<ProgrammeEditionEnrollment>
    -_programmeEditionEnrollments: ProgrammeEditionEnrollmentFactoryImpl
    +ProgrammeEditionEnrollmentRepo(programmeEditionEnrollmentFactory: ProgrammeEditionEnrollmentFactoryImpl, programmeEditionEnrolmentListFactory: ProgrammeEditionEnrolmentListFactory)
    +enrollStudentInProgrammeEdition(student: Student, programmeEdition: ProgrammeEdition)
    +isStudentEnrolledInThisProgrammeEdition(student: Student, programmeEdition: ProgrammeEdition)
    +countStudentsInProgrammesFromDepartmentInSchoolYear(department: Department, schoolYear: SchoolYear)
    +getTheNumberOfStudentsEnrolledInAProgrammeEdition(programmeEdition: ProgrammeEdition)
    +findProgrammeEditionsThatStudentIsEnrolled(student: Student)
}

class ProgrammeEditionRepository {
    -_IprogrammeEditionFactory: IProgrammeEditionFactory
    -_ProgrammeEditions: List<ProgrammeEdition>
    +ProgrammeEditionRepository(iProgrammeEditionFactory: IProgrammeEditionFactory, iProgrammeEditionListFactory: IProgrammeEditionListFactory)
    +createProgrammeEdition(programme: Programme, schoolYear: SchoolYear)
    +findProgrammeEditionBySchoolYearAndProgramme(programme: Programme, schoolYear: SchoolYear)
    +getAllProgrammeEditions()
    +findProgrammeInProgrammeEdition(programmeEdition: ProgrammeEdition)
}

class ProgrammeEditionEnrollment {
    -_student: Student
    -_programmeEdition: ProgrammeEdition
    -_enrollmentDate: LocalDate
    +ProgrammeEditionEnrollment(student: Student, programmeEdition: ProgrammeEdition)
    +isEnrollmentAssociatedToDepartmentAndSchoolYear(department: Department, schoolYear: SchoolYear)
    +getStudentUniqueNumber()
    +equals (obj: Object)
    +findProgrammeEditionInEnrollment()
    +findStudentInProgrammeEdition()
}

class ProgrammeEdition {
    -_programme: Programme
    -_schoolYear: SchoolYear
    +programmeEdition(programme: Programme,schoolYear: SchoolYear)
    +equals(object: Object)
    +findProgrammeInProgrammeEdition()
    +findSchoolYearInProgrammeEdition()
    +isEditionAssociatedToDepartmentAndSchoolYear(department: Department, schoolYear: SchoolYear)
}


US21_IWantToGetTheNumberOfStudentsEnrolledInAProgrammeEditionController "1" ..> "1" ProgrammeEditionRepository
US21_IWantToGetTheNumberOfStudentsEnrolledInAProgrammeEditionController "1" ..> "1" ProgrammeEditionEnrollmentRepo
ProgrammeEditionEnrollmentRepo "1" --> "_programmeEditionEnrollments *" ProgrammeEditionEnrollment
ProgrammeEditionRepository "1" --> "_programmeEditions *" ProgrammeEdition

@enduml