@startuml
actor ProgrammeDirector

participant ":UI" as S
participant ":Controller" as C
participant ":GradeStudentRepo" as GSR

ProgrammeDirector -> S ++ #application: I want to know approval percentage of Course Edition
S --> ProgrammeDirector -- : Course Edition?
ProgrammeDirector -> S ++ #application: Course Edition!
S -> C ++ #application: knowApprovalRate(CourseEdition)
C -> GSR ++ #application : knowApprovalRate(CourseEdition)

GSR -> GSR : knowApprovalRate(CourseEdition)
GSR --> C --: Approval Percentage of courseEdition1

C --> S --: Approval Percentage of courseEdition1

S --> ProgrammeDirector : Succeed Approval Percentage (courseEdition1)


@enduml
