@startuml

autonumber

title Count the number of enrolments

participant "ceService:CourseEditionEnrolmentService" as S #lightblue
participant "List<CourseEditionEnrolment>" as ListCEE #lightblue

S -> ListCEE ++ #lightblue: size()
ListCEE --> S --: numberOfStudents

@enduml