@startuml
actor ASC
participant ":UI" as UI
participant ":US12_ChangeProgrammeDirectorInSystem" as US12
participant ":TeacherRepository" as TR
participant ":ProgrammeRepository" as PL #lightgreen
participant ":Programme" as PG #yellow
autonumber

ASC -> UI : I want to change Programme Director
activate UI #application
UI --> ASC : Programme? Teacher?
deactivate UI

ASC -> UI : Programme1! Teacher1!
activate UI #application
UI -> US12 : changeProgrammeDirector(Programme1, Teacher1)
activate US12 #application

US12 -> TR : getTeacherId(Teacher1)
activate TR #application
TR -> US12 : :tIdVO1
deactivate TR
US12 -> PL : getProgrammeId(Programme1)
activate PL #application
PL -> US12 : :pIDVO1
deactivate PL

US12 -> PL :changeProgrammeDirector(:pIDVO1, :tIdVO1)
activate PL #application

PL -> PL : ofIdentity(:pIDVO1)


PL -> PG : newProgrammeDirector(:tIdVO1)
activate PG #application
PG -> PG : validates if teacher is not Null

PG --> PL : true
deactivate PG
PL->US12 : true
deactivate PL
US12 --> UI : true
deactivate US12

UI --> ASC : Success!
deactivate UI
@enduml