@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title Convert StudentGradeDataModel to StudentGrade

participant "service:SGService" as SGService #lightblue
participant "mapper:StudentGradeMapperImpl" as Mapper #burlywood

participant "mapper:StudentIDMapperImpl" as StudentIDMapper #orange
participant "mapper:CourseEditionIDMapperImpl" as CEIDMapper #orange
participant "mapper:StudentGradeIDMapper" as SGIDMapper #orange
participant "factory:StudentGradeFactory" as Factory #pink

SGService -> Mapper : toDomain(studentGradeDM)
activate Mapper

Mapper -> StudentIDMapper : dataModelToDomain(studentGradeDM.getStudentId())
activate StudentIDMapper
StudentIDMapper --> Mapper : StudentID
deactivate StudentIDMapper

Mapper -> CEIDMapper : toDomain(studentGradeDM.getCourseEditionID())
activate CEIDMapper
CEIDMapper --> Mapper : CourseEditionID
deactivate CEIDMapper

Mapper -> SGIDMapper : toDomain(studentGradeDM.getId())
activate SGIDMapper
SGIDMapper --> Mapper : StudentGradeID
deactivate SGIDMapper

Mapper -> Factory : newGradeStudentFromDataModel(grade, date, studentID, courseEditionID, studentGradeID)
activate Factory
Factory --> Mapper : StudentGrade
deactivate Factory

Mapper --> SGService : StudentGrade
deactivate Mapper
@enduml
