@startuml CheckTeacherExists
title Verify Teacher Existence
autonumber

participant Service
participant TeacherRepository
participant TeacherSpringData

activate Service
Service -> TeacherRepository : containsOfIdentity(teacherIdVO)
activate TeacherRepository
TeacherRepository -> TeacherSpringData : existsById(teacherIdDataModel)
activate TeacherSpringData
TeacherSpringData --> TeacherRepository : true
deactivate TeacherSpringData
TeacherRepository --> Service : true
@enduml
