@startuml SaveTCP
title Persist New Career Progression
autonumber

participant Service
participant TCPRepository
participant TCPRepoSpringData

activate Service
Service -> TCPRepository : save(newTCP)
activate TCPRepository
TCPRepository -> TCPRepoSpringData : save(tcpDataModel)
activate TCPRepoSpringData
TCPRepoSpringData --> TCPRepository : savedDM
deactivate TCPRepoSpringData
TCPRepository --> Service : savedTCP
@enduml
