@startuml ValidateBusinessRules
title Validate Rules on Last Career Progression
autonumber

participant Service
participant lastTCP

activate Service
Service -> lastTCP : isLastDateEqualOrBeforeNewDate(dateVO)
activate lastTCP
lastTCP --> Service : true
deactivate lastTCP

Service -> lastTCP : hasSameWorkingPercentage(wpVO)
activate lastTCP
lastTCP --> Service : true
deactivate lastTCP

Service -> lastTCP : getTeacherCategoryID()
activate lastTCP
lastTCP --> Service : categoryVO
deactivate lastTCP
@enduml
