package PAI.service.totalEnrolledStudentsInProgrammesByDepartmentAndSchoolYear;

import PAI.dto.totalEnrolledStudents.TotalEnrolledStudentsCommand;

public interface ITotalEnrolledStudentsInProgrammesByDepartmentAndSchoolYearService {

    int getTotalEnrolledStudentsInProgrammesByDepartmentAndYear (TotalEnrolledStudentsCommand command) throws Exception;
}
