@startuml
title US13 : Interaction Use #5 - Verify Duplicates
skinparam sequenceMessageAlign center

participant "T1:TeacherRepositorySpringData" as T #lightblue
participant "TIDM1:TeacherIDMapper" as TMapper #lightgreen
participant "teacherIDDataModel1:TeacherIDDataModel" as tiddm #lightyellow
participant "NIFM1:NIFMapper" as NIF #lightgreen
participant "NIFDataModel1:NIFDataModel" as NIFDM #lightyellow

activate T
T -> TMapper : domainToDataModel(teacherIDVO)
activate TMapper
TMapper -> tiddm**: new TeacherIDDataModel(teacherIDVO)
activate tiddm
tiddm --> TMapper : teacherIDDataModel1
deactivate tiddm
TMapper --> T: teacherIDDataModel1
deactivate TMapper
T -> NIF : domainToDataModel(NIFVO)
activate NIF
NIF -> NIFDM**: new NIFDataModel(NIFVO)
activate NIFDM
NIFDM --> NIF: NIFDataModel1
deactivate NIFDM
NIF --> T: NIFDataModel1
deactivate NIF
T -> : existsByTeacherIdOrNif(teacherIDDataModel1, NIFDataModel1)
T <-- : False
@enduml