@startuml

title US20 \n As a Programme Director, I want to define the RUC for a course edition \n (Process View - Level 2 Granularity)

skinparam titleFontName "Verdana"
skinparam defaultFontName "Verdana"
skinparam defaultTextAlignment center
skinparam shadowing true
skinparam actorBackgroundColor #lightblue
skinparam participantBackgroundColor #lightblue/white

autonumber

actor ProgrammeDirector as PD
participant "Frontend" as Frontend <<container>>
participant "Backend" as Backend <<container>>
participant "Database" as DB <<container>>

PD -> Frontend: I want to define the RUC for a course edition
activate Frontend #E1F5FE

' --- Select teachers ---
Frontend -> Backend: (GET) Request teachers
activate Backend  #E1F5FE
Backend -> DB: Retrieve all teachers
activate DB  #E1F5FE
DB --> Backend: List of teachers
deactivate DB
Backend --> Frontend: (200 OK) List of teachers
deactivate Backend
Frontend --> PD: Display teacher selection list


deactivate Frontend
PD -> Frontend: Select teacher
activate Frontend #E1F5FE

' --- Select course edition ---
Frontend -> Backend: (GET) Request course editions
activate Backend  #E1F5FE
Backend -> DB: Retrieve all course editions
activate DB  #E1F5FE
DB --> Backend: List of course editions
deactivate DB
Backend --> Frontend: (200 OK) List of course editions
deactivate Backend
Frontend --> PD: Display course edition selection list
deactivate Frontend

PD -> Frontend: Select courseEdition
activate Frontend  #E1F5FE


' --- Confirm ---
Frontend --> PD: Confirm selected teacher and course edition?
deactivate Frontend
PD -> Frontend: Yes
activate Frontend #E1F5FE


' --- Define RUC ---
Frontend -> Backend: (PATCH) Request define RUC for course edition (course edition, teacher)
activate Backend  #E1F5FE
Backend -> DB: Persist course edition RUC (courseEdition, teacher)
activate DB  #E1F5FE
DB --> Backend: RUC updated
deactivate DB
Backend --> Frontend: (200 OK) RUC successfully updated
deactivate Backend

Frontend --> PD: RUC was successfully defined!
deactivate Frontend

@enduml