spring:
  datasource:
    url: jdbc:h2:tcp://h2:9092/./testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    database: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active:
      - teacher
      - student
      - programme
      - programmeEnrolment
      - course
      - course-edition-enrolment
      - programme-edition-enrolment
      - programme-edition
      - studyPlan
      - school-year
      - access-method
      - course-edition
      - course-in-study-plan
      - degree-type
      - department
      - teacher-category
      - studentGrade
  main:
    log-startup-info: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8081

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        boot: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"