@startuml
actor ProgrammeDirector
participant ":UI" as UI
participant ":IWantToKnowTheAverageGradeInACourseEditionCtr" as KA
participant ":CourseEditionRepository" as CER
participant ":GradeStudentRepository" as GR
participant ":GradeStudent" as GradeStudent
autonumber


ProgrammeDirector -> UI ++ #application: I want to know average grade of Course Edition
UI --> ProgrammeDirector -- : Course Edition?
ProgrammeDirector -> UI ++ #application: Course Edition1!
UI -> KA ++ #application : IWantToKnowTheAvg(courseEdition1)
KA -> CER ++ #application : findCourseEditionID (courseEdition1)
CER -> CER : findIdByCourseEdition (CourseEdition1)
CER -> KA :  :ceIdVO1
deactivate CER
KA -> GR ++ #application : knowApprovalRate(:ceIdVO1)



loop for each GradeStudent in GR
    GR -> GradeStudent : hasThisCourseEdition(:ceIdVO1)
    activate GradeStudent
    GradeStudent --> GR : True!
    deactivate GradeStudent

    GR -> GradeStudent : knowGrade()
    activate GradeStudent
    GradeStudent --> GR : (double) grade
    deactivate GradeStudent
end


GR --> KA --: Average Grade of courseEdition1
KA --> UI --: Average Grade of courseEdition1
UI --> ProgrammeDirector --: Average Grade of courseEdition1

@enduml