@startuml
actor ProgrammeDirector
participant ":UI" as UI
participant ":IWantToKnowTheAverageGradeInACourseEditionCtr" as KA
participant ":GradeStudentRepository" as GR
participant ":GradeStudent" as GradeStudent


ProgrammeDirector -> UI ++ #application: 1.I want to know average grade of Course Edition
UI --> ProgrammeDirector -- : 2.Course Edition?
ProgrammeDirector -> UI ++ #application: 3.Course Edition!
UI -> KA ++ #application : 4.IWantToKnowTheAvg(courseEdition1)
KA -> GR ++ #application : 5.knowTheAverageGrade(courseEdition1)



loop for each GradeStudent in GR
    GR -> GradeStudent : 6.hasThisCourseEdition(courseEdition1)
    activate GradeStudent
    GradeStudent --> GR : 7.True!
    deactivate GradeStudent

    GR -> GradeStudent : 8.knowGrade()
    activate GradeStudent
    GradeStudent --> GR : 9.grade
    deactivate GradeStudent
end


GR --> KA --: 10.Average Grade of courseEdition1
KA --> UI --: 11.Average Grade of courseEdition1
UI --> ProgrammeDirector --: 12.Average Grade of courseEdition1

@enduml