@startuml
autonumber

skinparam sequence {
   LifelineBorderColor black
   LifelineBackgroundColor LightBlue
 }

title As a RUC, I want to grade a Student in a Course Edition\nProcess View – Level 2 (with HATEOAS)

actor "RUC" as RUC
participant ":Frontend" as FE
participant ":Backend" as BE
database DB

RUC -> FE ++: Request to assign a grade
FE --> RUC --: Request grade, date, student and course info
RUC -> FE ++: Insert grade, date,\nStudentID, CourseEditionID

FE -> BE ++: HTTP POST /courseeditions/studentgrades/register
note right of BE: Controller parses JSON\nand builds Command
BE -> DB ++: Verify enrolment and date validity
DB --> BE --: OK (preconditions met)

BE -> DB ++: INSERT INTO studentgrades
DB --> BE --: Grade registered

BE --> FE --: HTTP 201 Created +\nEntityModel<GradeAStudentResponseDTO>\n(includes _links: self, averageGrade, approvalRate)
FE --> RUC --: Grade registered with success

@enduml
