@startuml

autonumber
title As a RUC, I want to grade a Student in a Course Edition \n (Process View Level 2 – with HATEOAS support)
skinparam sequencemessagealign center

actor RUC as RUC
participant "Frontend" as FE <<Container>> #application
participant "Backend" as BE <<Container>> #strategy
database Database


RUC -> FE : Request to grade a Student in the Course Edition
activate FE

FE -> BE : **(GET)** \n /courseeditions
activate BE

BE --> Database : **(GET)** \n findAllCourseEditions()
activate Database

BE <-- Database : List <CourseEditionResponseDTO>
deactivate Database

BE --> FE : All Course Editions \n (**with HATEOAS links**: self, gradeStudent)
deactivate BE

FE --> RUC : Course Edition?
RUC -> FE : Course Edition!

FE --> RUC: Student Grading form
RUC -> FE: grade, date, studentID

FE -> BE : **(POST)** \n /studentgrades/register
activate BE

BE -> Database : **(INSERT)** \n save(studentGradeDataModel)
activate Database

BE <-- Database : studentGrade \n (grade, date, studentID)
deactivate Database

BE --> FE: studentGrade \n (grade, date, studentID) \n (**with _links**: self, update, courseEdition, student)
deactivate BE

FE --> RUC: Student graded successfully!
deactivate FE

@enduml
