@startuml
actor admin



admin -> UI ++ #application : I want to configure TeacherCategory
UI --> admin -- : categoryName?

admin -> UI ++ #application :(categoryName)


UI -> ConfigureTeacherCategoryController ++ #application : configureTeacherCategory(categoryName)

participant ":TeacherCategoryRepository" as TeacherCategoryRepository
ConfigureTeacherCategoryController -> TeacherCategoryRepository ++ #application : createTeacherCategory(categoryName)

create "tc1:TeacherCategory" as TeacherCategory
TeacherCategoryRepository -> TeacherCategory ++ #application : <create>(categoryName)
TeacherCategory -> TeacherCategory: isNameValid(categoryName)
TeacherCategory --> TeacherCategoryRepository -- : tc1
TeacherCategoryRepository -> TeacherCategoryRepository : isTeacherCategoryRegistered (tc1)
TeacherCategoryRepository -> TeacherCategoryRepository : registerTeacherCategory(categoryName)

TeacherCategoryRepository --> ConfigureTeacherCategoryController --: true

ConfigureTeacherCategoryController --> UI --: true
UI --> admin --: true
@enduml