@startuml
actor ASC

ASC -> UI ++ #application : I want to add Course to a Programme
UI --> ASC -- : courseName?
ASC -> UI ++ #application : courseName!
UI --> ASC -- : semester?
ASC -> UI ++ #application : semester!

UI -> addCourseToAProgrammeController ++ #application : addCourseToAProgramme (course, semester)

addCourseToAProgrammeController -> ":Programme" ++ #application : addCourseToAProgramme (course, semester)

":Programme" -> semesterListOfAProgramme ++ #application : addCourseToAProgramme (semester)

semesterListOfAProgramme -> listOfCoursesInASemester ++ #application : addCourseToAProgramme (course)

listOfCoursesInASemester -> listOfCoursesInASemester : validation
listOfCoursesInASemester -> listOfCoursesInASemester : addCourseToASemester

listOfCoursesInASemester --> semesterListOfAProgramme --: :c1

semesterListOfAProgramme --> ":Programme" --: :c1

":Programme" --> addCourseToAProgrammeController --: :c1

addCourseToAProgrammeController --> UI : true

UI --> ASC : true

@enduml