@startuml

autonumber

participant "Router" as RO #lightblue
participant "Controller" as C #lightgreen
participant "Service" as S #lightblue
participant "Domain" as D #lightpink
participant "Repository" as R #lightyellow

[o-> RO ++: (POST) Request Register\nStudent in the System

RO -> C ++: Submit Student Form
C -> S ++: Register Student

S -> D ++: Create Student
D --> S --: Student

S -> R ++: Check if Student exists
R --> S --: Student does not exist

S -> R ++: Save Student
R --> S --: Saved Student

S --> C --: Saved Student
C --> RO --: Saved Student
[o<-- RO --: (201 OK) Student registered successfully!

@enduml