@startuml

title US04: \n As an Administrator, I want to register a teacher in the system. \n Process View Level 3
autonumber

skinparam sequence {
    LifelineBorderColor black
    LifelineBackgroundColor LightBlue
    ActorBorderColor black
    ActorBackgroundColor LightGray
    GroupBorderColor #cccccc
    GroupBackgroundColor #f2f2f2
}

actor Administrator
participant ":FrontEnd" as FE
participant ":Router" as RT
participant ":Controller" as CT
participant ":Service" as SE
participant ":Domain" as DM
participant ":Repository" as RE
participant ":Driver" as DR

Administrator -> FE ++: Request to register Teacher.
FE --> Administrator --: Prompt: "Enter Teacher's Information"
Administrator -> FE ++: Enter: "teacher information"

FE -> RT ++: POST /teachers \n {body: "teacher information"}
RT -> CT ++: (POST) /teachers {request}

CT -> SE ++: createAndSaveTeacher (requestDto)
SE -> DM ++: createTeacher (teacher information)
DM --> SE --: teacher

SE -> RE ++: save (teacher)
RE -> DR ++: save (teacher)

DR -> : INSERT INTO teachers
DR <--: persisted teacher

DR --> RE --: teacher
RE --> SE --: teacher
SE --> CT --: teacher

CT --> RT --: HTTP 201 CREATED + \n teacherDTO
RT --> FE --: HTTP 201 CREATED + \n teacherDTO

FE --> Administrator --: Teacher registered successfully

footer <size:18>teacher information = teacherID, name, email, NIF, countryCode, phoneNumber, academicBackground, street, postalCode, location, country, departmentID</size>

@enduml
