@startuml
autonumber

skinparam sequence {
   LifelineBorderColor black
   LifelineBackgroundColor LightBlue
 }

title US04: \n As an Administrator, I want to register a teacher in the system.

actor Administrator
participant "Frontend" as FE
participant "Backend" as BE
database DB

Administrator -> FE ++: Request to register Teacher.
FE --> Administrator --: Request Teacher's attributes?

Administrator -> FE ++: Enter Teacher: teacherID, name, email, NIF, phoneNumber, \n academicBackground, street, postalCode, \n location, country, date, workingPercentage

FE -> BE ++: (GET) Request list of departments
BE -> DB ++: Fetch all departments
DB --> BE --: List of department
BE --> FE --: List of department
FE --> Administrator --: Display departments

Administrator -> FE ++: Select department

FE -> BE ++: (POST) Register Teacher
BE -> DB ++: Persist instance of teacher created
DB --> BE --: Registry confirmed
BE --> FE --: (200 OK) Registration successfully
FE --> Administrator --: Teacher registered successfully!

@enduml
