@startuml

title US04: \n As an Administrator, I want to register a teacher in the system. \n Process View Level 4

autonumber
skinparam sequence {
    LifelineBorderColor black
    LifelineBackgroundColor LightBlue
    ActorBorderColor black
    ActorBackgroundColor LightGray
    GroupBorderColor #cccccc
    GroupBackgroundColor #f2f2f2
}

actor "Administrator" as ADM
participant ":Frontend" as FE
participant ":Router" as RT
participant ":TeacherRestController" as CT
participant ":ITeacherAssembler" as AS
participant ":ITeacherRegistrationService" as SE
participant ":ITeacherRepository" as RP
participant ":ITeacherFactory" as FT
participant ":ITeacherMapper" as MP


ADM -> FE ++: Request to register Teacher.
FE --> ADM --: Prompt: "Enter Teacher's Information"
ADM -> FE ++: Enter: "teacher information"

FE -> RT ++: POST /teachers \n {body: "teacher information"}
RT -> CT ++: (POST) /teachers {request}
CT -> AS ++: RegisterTeacherRequestDTO
AS --> CT --: RegisterTeacherCommandDTO




CT -> SE ++: createAndSaveTeacher (teacherCommandDTO)
SE -> FT ++: createTeacher (teacher information)
FT --> SE --: teacher



SE -> RP ++: containsOfIdentity (teacherId)
RP -> : containsOfIdentity (teacherId)
RP <-- : false
RP --> SE --: false



SE -> RP ++: save (teacher)
RP -> MP ++: toDataModel (teacher)
MP --> RP --: teacherDataModel
RP -> : INSERT INTO teachers
RP <-- : teacherDataModel
RP --> SE --: teacher


SE --> CT --: teacher
CT -> AS ++: toDTO (teacher)
AS --> CT --: teacherDTO



CT --> RT --: HTTP 201 Created + teacherDTO
RT --> FE --: HTTP 201 Created + \nteacherDTO
FE --> ADM --: OK. Created.

footer <size:18>teacher information = teacherID, name, email, NIF, countryCode, phoneNumber, academicBackground, street, postalCode, location, country, departmentID</size>

@enduml
