@startuml

title US04: \n As an Administrator, I want to register a teacher in the system. \n Process View Level 4
autonumber

skinparam sequence {
    LifelineBorderColor black
    LifelineBackgroundColor LightBlue
    ActorBorderColor black
    ActorBackgroundColor LightGray
    GroupBorderColor #cccccc
    GroupBackgroundColor #f2f2f2
}

actor Administrator
participant ":FrontEnd" as FE
participant ":Controller" as CT
participant ":DepartmentRestController" as DCT
participant ":IDepartmentRegistrationService" as DSE
participant ":IDepartmentAssembler" as DA
participant ":Service" as SE
participant ":Domain" as DM
participant ":Repository" as RE



group Human Interaction
Administrator -> FE ++: Request to register Teacher.
FE --> Administrator --: Prompt: "Enter Teacher's Information"
Administrator -> FE ++: Input: "teacherID, name, email, NIF, countryCode, \n phoneNumber, academicBackground, \n street, postalCode, location, country"
end group

group HTTP Request
FE -> DCT ++: (GET) /departments
end group

group Application Service Invocation
DCT -> DSE ++: getAllDepartments()

group Persistence
DSE -> RE ++: findAll()
RE --> DSE --: List<Department>
end group

DSE --> DCT --: List<Department>
end group

group HTTP Response
DCT --> FE--:  HTTP 200 OK + (List<DepartmentDto>)
end group

group Human Interaction
FE --> Administrator --: Display Department List. \n Prompt: "Select one Department.
Administrator -> FE ++: Select Department
end group

group HTTP Request
FE -> CT ++: (POST) /teachers with JSON {request}
end group

group Application Service Invocation
CT -> SE ++: createAndSaveTeacher(command)
group Domain Logic
SE -> DM ++: Teacher teacher = new Teacher(command)
DM --> SE --: teacher
end group
group Persistence
SE -> RE ++: save(teacher)
RE --> SE --: Persisted teacher
end group
SE --> CT --: teacher
end group
group HTTP Response
CT --> FE --: HTTP 201 CREATED + teacherDTO
end group
FE --> Administrator --: Teacher registered successfully
'TA --> RC --: teacherAcronym, name, email, nif, phoneNumber,\n academicBackground,street,postalcode,location,country, departmentID
'
@enduml

