@startuml
autonumber

skinparam sequence {
   LifelineBorderColor black
   LifelineBackgroundColor LightBlue
 }

title US04: \n As an Administrator, I want to register a teacher in the system. \n Process View Level 1

actor Administrator
participant ":System" as System #lightgrey


Administrator -> System ++: I want to register a teacher.
System --> Administrator --: What are the Teacher's attributes?
Administrator -> System ++: teacherID, name, email, NIF, countryCode, \n phoneNumber, academicBackground, \n street, postalCode, location, country

System --> Administrator --: Which Department?
Administrator -> System ++: department
System --> Administrator --: Teacher registered successfully!

@enduml