@startuml

!pragma layout smetana
'left to right direction'

class US14_UpdateTeachersCategoryController {
    +US14_UpdateTeachersCategoryController()
    +getTeacherByNIF(NIF: String)
    +updateTeachersCategoryInTeacherCareerProgression(date: String, teacherNIF: String, teacherCategoryName: String)
}

class Teacher {
     -_acronym:String
     -_name:String
     -_email:String
     -_nif:String
     -_phoneNumber:String
     -_academicBackground:String
     -_address:Address
     -_department:Department
     +Teacher(acronym: String, name: String, email: String, nif: String, phoneNumber: String,
     academicBackground: String, street: String, postalCode: String, location: String, country: String,
     date: String, category: TeacherCategory, workingPercentage: int, department: Department, teacherCareerProgressionFactory: TeacherCareerProgressionFactory)
     +validateAcronym(teacherAcronym:String)
     +validateName(name: String)
     +validateEmail(email: String)
     +validateNif(nif: String)
     +validatePhoneNumber(phoneNumber: String)
     +validateAcademicBackground(academicBackground: String)
     +hasSameAcronym(teacher: Teacher)
     +hasSameNif(teacher: Teacher)
     +isInDepartment(department: Department)
     +hasThisNIF(NIF: String)
     +updateWorkingPercentageInTeacherCareerProgression(date: String, workingPercentage: int)
     +updateTeachersCategoryInTeacherCareerProgression(date: String, teacherCategory: TeacherCategory)
}

class TeacherCareerProgression {
    -_date: LocalDate
    -_workingPercentage: int
    +TeacherCareerProgression(date: String, workingPercentage: int)
    +getCategory()
    +getWorkingPercentage()
    +isDateAfter(tcp: TeacherCareerProgression)
}

class TeacherCareerProgressionFactory {
+createTeacherCareerProgression(date: String, category: TeacherCategory, workingPercentage: int)
}

interface TeacherCareerProgressionFactoryInterface {
+createTeacherCareerProgression(date: String, category: TeacherCategory, workingPercentage: int)
}

class TeacherRepository {
    +TeacherRepository()
    +registerTeacher(acronym: String, name:String, email: String, nif: String, phoneNumber:String,
                     address: Address, department: Department)
    +compareTeacherAcronymAndNifInList(Teacher: teacher)
    +getAllTeachers()
    +getTeacherByNIF(NIF: String)
}

class TeacherCategory {
    -_name:String
    + TeacherCategory (name:String)
}

US14_UpdateTeachersCategoryController "1" --> "1 " TeacherRepository
Teacher "1..*" --o "List<Teacher>" TeacherRepository
TeacherCareerProgression "*" --> "1" TeacherCategory: _category
Teacher --> TeacherCareerProgressionFactory
Teacher "List<TeacherCareerProgression>" *-- "*" TeacherCareerProgression
TeacherCareerProgressionFactory ..> TeacherCareerProgression: <<create>>
TeacherCareerProgressionFactoryInterface <|.. TeacherCareerProgressionFactory


@enduml