@startuml
title Ref: Convert Study Plan to DTO (Backend - Granularity 4)
skinparam sequenceLifeLineBackgroundColor lightblue
skinparam sequenceMessageAlign center
autonumber

participant ":StudyPlanService" as StudyPlanService <<service>> #F6CBA5
participant ":StudyPlanAssembler" as StudyPlanAssembler <<mapper>> #E1D5E7
participant "studyPlanDTO1:StudyPlanDTO" as StudyPlanDTO <<component>> #FFE599

activate StudyPlanService
StudyPlanService -> StudyPlanAssembler ++: **toDTO**(studyPlan)
StudyPlanAssembler -> StudyPlanDTO **: **createStudyPlanDTO**(programmeName, \nProgrammeAcronym, startDate, maxEcts, durationInYears)
activate StudyPlanDTO
StudyPlanDTO --> StudyPlanAssembler: studyPlanDTO1
deactivate StudyPlanDTO
StudyPlanAssembler --> StudyPlanService --: studyPlanDTO1
@enduml