@startuml
title Ref: Convert DTO to Response DTO (Backend - Granularity 4)
skinparam sequenceLifeLineBackgroundColor lightblue
skinparam sequenceMessageAlign center
autonumber

participant ":ProgrammeRestController" as ProgrammeRestController <<controller>> #82CFFD
participant ":StudyPlanAssembler" as StudyPlanAssembler <<mapper>> #E1D5E7
participant "studyPlanResponseDTO1:StudyPlanResponseDTO" as StudyPlanResponseDTO <<component>> #FFE599

activate ProgrammeRestController
ProgrammeRestController -> StudyPlanAssembler ++: **toResponseDTO**(studyPlanDTO)
StudyPlanAssembler -> StudyPlanResponseDTO **: createStudyPlanResponseDTO(programmeAcronym, startDate, durationInYears, maxEcts)
activate StudyPlanResponseDTO
StudyPlanResponseDTO --> StudyPlanAssembler: studyPlanResponseDTO1
deactivate StudyPlanResponseDTO
StudyPlanAssembler --> ProgrammeRestController --: studyPlanResponseDTO1
@enduml