@startuml
actor HRC
participant ":Test" as TE #lightgrey
participant ":Controller" as CTL #lightgreen
participant ":TeacherCategoryRepo" as TCR #lightblue
participant "tr1:TeacherRepo" as TR #orange
participant "t1:Teacher" as T #lightyellow
participant "tcp1:TeacherCareerProgression" as TCP #lightpink
participant "tcp2:TeacherCareerProgression" as TCP2 #lightpink


HRC -> TE: I want to update Teacher (date, teacherNIF, teacherCategoryName)
activate TE
TE -> CTL : updateTeacherCategory(date, teacherNIF, teacherCategoryName)
activate CTL
CTL -> TR: getTeacherByNIF(teacherNIF)
activate TR
TR -> TR : find t1, that has TeacherCategory tc1
TR --> CTL
deactivate TR
|||
CTL -> TCR: getTeacherCategoryByName(teacherCategoryName)
activate TCR
TCR -> TCR: find tc2
TCR --> CTL
deactivate TCR
|||
CTL -> TR: updateTeacherCategoryInTeacherCareer(date, t1, tc2)
activate TR
TR -> T: updateTeacherCategory(date, tc2)
activate T
T -> T: get Last TeacherCarrerProgression, tcp1
|||
T -> TCP : getWorkingPercentage(tcp1)
activate TCP
TCP --> T : wp1
deactivate TCP
|||
T -> T: getCategory(tcp1)
T -> T: Validate if tc2 is different than tc1
T -> TCP2** : createTeacherCarrerProgression(date, tc2, wp1)
activate TCP2
TCP2 -> TCP2 : validateDate(date)
TCP2 --> T
deactivate TCP2
|||
ref over T, TCP2
    check if tcp2 has a date later than tcp1
end ref
|||
T -> T : add(tcp2)
T --> TR : success!
deactivate T
TR --> CTL : success!
deactivate  TR
CTL --> TE : success!
deactivate CTL
TE --> HRC : success!
deactivate TE
@enduml