@startuml
actor HRC
participant ":Test" as TE #lightgreen
participant "tc1:TeacherCategory" as TC #lightblue
participant "dpt1: Department" as D #orange
participant "tc2:TeacherCategory" as TC2 #lightblue
participant ":Controller" as CTL #lightgreen
participant "tr1:TeacherRepo" as TR #lightyellow
participant "t1:Teacher" as T #lightyellow
participant "a1:Address" as A
participant "tcp1:TeacherCareerProgression" as TCP #lightpink
participant "tcp2:TeacherCareerProgression" as TCP2 #lightpink



note right TE #aliceblue
    //arrange
end note
activate TE
'note right
'end note
TE -> TC**: createTeacherCategory(name)
activate TC
|||
TC --> TE
deactivate TC
|||
TE -> D**: createDepartment(name, acronym)
|||
activate D
|||
D --> TE

deactivate D
|||
TE -> T**: createTeacher(acronym, name, NIF, teacherContact,\naddressInformation, tc1, workingPercentage, dpt1, date)
activate T
|||
T -> A**: createAddress(street, postalCode,location, country)
|||
activate A
A --> T
deactivate A
|||
T -> TCP** : createTeacherCareerProgression(date, tc1, workingPercentage)
activate TCP
TCP -> TCP : validateDate(date)
TCP -> TCP : validateWorkingPercentage(workingPercentage)
TCP --> T
deactivate TCP
T --> TE
|||
deactivate T
TE -> TC2** : createTeacherCategory(name)
|||
activate TC2
TC2 --> TE
|||
deactivate TC2
TE ->  TR**: teacherRepository()
|||
activate TR
TR --> TE
deactivate TR
|||
HRC -> TE: I want to update Teacher t1 with TeacherCategory tc2
note right TE #aliceblue
    //act
end note
TE -> CTL : updateTeacherCategory(date, t1, tc2)
activate CTL
CTL -> TR : updateTeacherCategory(date, t1, tc2)
activate TR
TR -> T : updateTeacherCategory(date, tc2)
activate T
T -> T : getLastWorkingPercentage()
|||
T -> TCP : getWorkingPercentage(tcp1)
activate TCP
TCP --> T : wp1
deactivate TCP
|||
T -> TCP2** : updateTeacherCategoryInTeacherCareer(date, tc2, wp1)
activate TCP2
TCP2 -> TCP2 : validateDate(date)
TCP2 --> T
deactivate TCP2
|||
ref over T, TCP2
    check if tcp2 has a date later than any other tcp in the list
end ref
|||
T -> T : add(tcp2)
T --> TR : success!
deactivate T
TR --> CTL : success!
deactivate  TR
CTL --> TE : success!
deactivate CTL
TE --> HRC : success!
deactivate TE

@enduml