@startuml

skinparam componentStyle rectangle
skinparam ArrowColor black
skinparam defaultTextAlignment center

title "PAI - Logical View Level 1 (US16 - Enroll Student in Course)"

rectangle " " {
    actor "Academic Services Coordinator" as ASC
    rectangle "Student Enrollment System" {
        interface "API" as API
        interface "BD API" as BDAPI
    }
}

ASC -down-> API : Uses
API -down-> BDAPI : Uses

@enduml 