@startuml
title: Get Programme Edition Enrollments By Student ID\n(Code View - Level 4)

autonumber

participant ":Router" as router
participant ":StudentProgrammeEditionEnrolmentController" as peeCtrl
activate peeCtrl
participant ":ProgrammeEditionEnrolmentService" as peeService
participant ":ProgrammeEditionEnrolmentRepository" as peeRepo
participant ":SchoolYearRepository" as syRepo
participant ":ProgrammeEditionEnrolmentAssembler" as peeAssembler
participant ":ProgrammeEditionEnrolmentHateoasAssembler" as peeHateoasAssembler
database DB

router -> peeCtrl: GET students/{id}/programme-edition-enrolments
peeCtrl -> peeService ++: getProgrammeEditionEnrollmentsByStudentID(StudentID)
peeService -> peeRepo ++: findProgrammeEditionsThatStudentIsEnrolled(StudentID)
peeRepo -> DB ++: SELECT programme_edition_id FROM programme_edition_enrollments\nWHERE student_id = StudentID
DB --> peeRepo --: List<ProgrammeEditionID>

peeRepo --> peeService --: List<ProgrammeEditionID>
peeService --> peeCtrl --: List<ProgrammeEditionID>

peeCtrl -> peeAssembler ++: toDtoList(List<ProgrammeEditionID>, StudentID)
peeAssembler --> peeCtrl --: List<ProgrammeEditionEnrolmentDetailDTO>

peeCtrl -> peeHateoasAssembler ++: toCollectionModel(List<ProgrammeEditionEnrolmentDetailDTO>)


peeHateoasAssembler --> peeCtrl --: CollectionModel<ProgrammeEditionEnrolmentDetailDTO>
peeCtrl --> router: CollectionModel<ProgrammeEditionEnrolmentDetailDTO>

legend right
  DTO = Data Transfer Object
  Assembler = Convert Domain to DTO
  HATEOAS Assembler = Convert Domain to EntityModel with links
end legend

@enduml