@startuml

title US13: As a HRC, I want to register a new teacher in the system, including all relevant data.

actor HRC
participant "UI" as UI #Cyan/Silver
participant ":Controller" as Controller #Cyan/Silver
participant ":TeacherCategoryRepository" as TeacherCategoryRepository #Cyan/Silver
participant ":DepartmentRepository" as DepartmentRepository #Cyan/Silver
participant ":TeacherRepository" as TeacherRepository #Cyan/Silver
participant "t1:Teacher" as Teacher #Cyan/Silver
participant "addrs1:Address" as Address #Cyan/Silver
participant "<TeacherCareerProgressionList>:TeacherCareerProgression" as TeacherCareerProgression #Cyan/Silver


HRC -> UI: I need all Teacher Categories.
activate UI

UI -> Controller: I need all Teacher Categories.
activate Controller

Controller -> TeacherCategoryRepository: **getTeacherCategoryList()**
activate TeacherCategoryRepository

TeacherCategoryRepository --> Controller: <TeacherCategoryList>
deactivate TeacherCategoryRepository

Controller --> UI: <TeacherCategoryList>

UI --> HRC: <TeacherCategoryList>

HRC -> UI: I need all Departments.

UI -> Controller: I need all Departments.

Controller -> DepartmentRepository: **getDepartmentList()**
activate DepartmentRepository

DepartmentRepository --> Controller: <DepartmentList>
deactivate DepartmentRepository

Controller --> UI: <DepartmentList>

UI --> HRC: <DepartmentList>

HRC -> UI: acronym, name, email, nif, phoneNumber,\nstreet, postcode, location,country,\nacademicBackgroung, workingPercentage,\ndate, tc1, dpt1

Note Right HRC #Pink/White
    *tc1* = Teacher Category Object
    *dpt1* = Department Object
End Note

UI -> Controller: **registerTeacher**(acronym, name, email, nif, phoneNumber,\nstreet, postcode, location, country,\nacademicBackground, workingPercentage,\ndate, tc1, dpt1)

Controller -> TeacherRepository: **registerTeacher**(acronym, name, email, nif, phoneNumber,\nstreet, postcode, location, country,\nacademicBackground, workingPercentage,\ndate, tc1, dpt1)
activate TeacherRepository

TeacherRepository -> Teacher **: **createTeacher** (acronym, name, email, nif, phoneNumber,\nstreet, postcode, location, country,\nacademicBackground, date, tc1, dpt1)
activate Teacher

Teacher -> Address **: **createAddress** (street, postcode, location, country)
activate Address

Address --> Teacher: addrs1
deactivate Address

Teacher -> TeacherCareerProgression **: **createTeacherCareerProgressionList** (tc1, workingPercentage, date)

TeacherCareerProgression --> Teacher: <TeacherCareerProgressionList>
deactivate TeacherCareerProgression

Teacher --> TeacherRepository: t1

ref over TeacherRepository, Teacher
    Check if a teacher is already registered
end ref

TeacherRepository -> TeacherRepository: add (t1)

deactivate Teacher

TeacherRepository --> Controller: Registered
deactivate TeacherRepository

Controller --> UI: Registered
deactivate Controller

UI --> HRC: Success
deactivate UI

@enduml