@startuml

title UC: Enrol Student in Programme\n(Process View Level 2)
autonumber

participant "<<system(C4)>>\nFrontend" as FE
participant "<<system(C4)>>\nBackend" as BE

[o-> FE: Request enroll Student in Programme
activate FE
FE -> BE: POST / students/enrol-programme /\n{studentID, accessMethodID, programmeAcronym, date}\t
activate BE
BE --> FE: 201 Created /\n{programmeEnrolmentGID, studentID,\naccessMethodID, programmeID, date,\n_links: {self: students/enroll}}
deactivate BE
[o<-- FE: Success! The student was enrolled successfully.\t\n(Display Enrolment Details and Enrol in Course URL)\t
deactivate FE
@enduml