@startuml
autonumber

title As an HRC I want to Update a Teacher's Category in the System\n(Process View Level 2)
skinparam DefaultTextAlignment center

actor HRC
participant "«Container» \n :Frontend" as FE
participant "«Container» \n :Backend" as BE
database DB


HRC -> FE ++: want to Update a Teacher's Category in the System
FE -> BE ++: **GET** /teachers
BE -> DB ++: **SELECT** fetchAllTeachers()
DB --> BE --: List<teachers>
BE --> FE --: (Ok 200) List<teachers>
FE --> HRC --: Display teachers

HRC -> FE ++: Select teacher
FE -> BE ++:  **GET** /teachercategories
BE -> DB ++: **SELECT** fetchAllTeacherCategories()
DB --> BE --: List<teacherCategories>
BE --> FE --: (Ok 200) List<teacherCategories>
FE --> HRC --: Display categories

HRC -> FE ++: Select category and date
FE -> BE ++: **POST** /teachers/careerprogressions/{teacherID}/categories\n (request)
BE -> DB ++: **INSERT** save (TeacherCareerProgressionDataModel)
DB --> BE --: teacherCareerProgression
BE --> FE --: (Created 201) DTOResponse
FE --> HRC --: Teacher category updated successfully \n (Display Date, TeacherCategory, WorkingPercentage\nTeacherID)

@enduml
