@startuml

' Logical View - US17: Enrol a Student in a ProgrammeEdition

skinparam ranksep 60
skinparam nodesep 60
skinparam linetype ortho

' === CONTROLLER ===
class StudentProgrammeEditionEnrolmentRestController <<RESTController>> {
    + getProgrammeEditionsStudentCanEnrollIn(studentId: String): ResponseEntity<List<StudentProgrammeEditionEnrolmentDTO>>
}

' === SERVICE ===
interface IStudentProgrammeEditionEnrolmentService <<Service>> {
    + findAvailableProgrammeEditionsForStudent(StudentID): List<StudentProgrammeEditionEnrolmentDTO>
}

class StudentProgrammeEditionEnrolmentServiceImpl <<Service>> {
    + findAvailableProgrammeEditionsForStudent(StudentID): List<StudentProgrammeEditionEnrolmentDTO>
}

' === ASSEMBLER ===
interface IStudentProgrammeEditionEnrolmentAssembler <<Assembler>> {
    + toDTO(ProgrammeEdition): StudentProgrammeEditionEnrolmentDTO
}

class StudentProgrammeEditionEnrolmentAssemblerImpl <<Assembler>> {
    + toDTO(ProgrammeEdition): StudentProgrammeEditionEnrolmentDTO
}

' === DTO ===
class StudentProgrammeEditionEnrolmentDTO <<DTO>> {
    - programmeAcronym: String
    - programmeName: String
    - schoolYearId: String
    + getProgrammeAcronym(): String
    + getProgrammeName(): String
    + getSchoolYearId(): String
}

' === AGGREGATE ===
class ProgrammeEdition <<Entity>> {
    + findProgrammeIDInProgrammeEdition(): ProgrammeID
    + findSchoolYearIDInProgrammeEdition(): SchoolYearID
}

' === VALUE OBJECTS ===
class ProgrammeID <<VO>>
class SchoolYearID <<VO>>
class StudentID <<VO>>

' === REPOSITORIES ===
interface IProgrammeEnrolmentRepository <<Repository>> {
    + findProgrammesByStudent(StudentID): List<ProgrammeID>
}

interface IProgrammeEditionRepository <<Repository>> {
    + findByProgrammeIDs(List<ProgrammeID>): List<ProgrammeEdition>
}

' === NAVIGATIONS ===
StudentProgrammeEditionEnrolmentRestController --> IStudentProgrammeEditionEnrolmentService
StudentProgrammeEditionEnrolmentRestController --> StudentID

StudentProgrammeEditionEnrolmentServiceImpl ..|> IStudentProgrammeEditionEnrolmentService
StudentProgrammeEditionEnrolmentServiceImpl --> IProgrammeEnrolmentRepository
StudentProgrammeEditionEnrolmentServiceImpl --> IProgrammeEditionRepository
StudentProgrammeEditionEnrolmentServiceImpl --> StudentProgrammeEditionEnrolmentAssemblerImpl

StudentProgrammeEditionEnrolmentAssemblerImpl ..|> IStudentProgrammeEditionEnrolmentAssembler
StudentProgrammeEditionEnrolmentAssemblerImpl --> StudentProgrammeEditionEnrolmentDTO
StudentProgrammeEditionEnrolmentAssemblerImpl --> ProgrammeEdition
ProgrammeEdition --> ProgrammeID
ProgrammeEdition --> SchoolYearID

@enduml
