@startuml

autonumber

participant "UI"
participant ":CreateAProgrammeEditionInTheCurrentSchoolYearController" as CPEC
participant ":SchoolYearRepo" as SYR
'participant ":SchoolYear"
'participant "ProgrammeList"
participant "ProgrammeEditionRepo" as PER
'participant "ProgrammeEdition"


UI -> CPEC ++ #application : createAProgrammeEditionInTheCurrentSY(programme1)
CPEC -> SYR ++ #application : getLatestSchoolYear()
SYR --> CPEC ::sy1
SYR --
CPEC -> PER ++ #application : createProgrammeEdition(programme1, sy1)
create "PE1 : ProgrammeEdition" as PE
PER -> PE : <create> (programme1, sy1)
PER -> PER : isProgrammeEditionValid
PER -> PER : addProgrammeEditionToProgrammeEditionRepository
PER --> CPEC : true
PER --
CPEC --> UI : ok!
CPEC --
@enduml