@startuml
title : US18_Create A Programme Edition For The Current School Year
autonumber
Actor ASC

participant ":UI" as UI
participant ":CreateAProgrammeEditionForTheCurrentSchoolYearController" as CPEC
participant ":ProgrammeService" as PS
participant ":ProgrammeRepository" as PR
participant ":SchoolYearRepository" as SYR
participant ":ProgrammeEditionRepository" as PER
participant ":ProgrammeEditionFactory" as PEF

'get all programmes name
ASC -> UI ++ #application : I want to create a programme edition for the current school year
UI -> CPEC ++ #application : getAllProgrammeNames()
CPEC -> PS ++ #application : getAllProgrammeNames()
PS -> PR ++ #application : getAllProgrammeNames()
ref over PR
    convert DataModel to Domain
end ref
PR --> PS -- : programmeNamesList
PS --> CPEC -- : programmeNamesList
CPEC --> UI -- : programmeNamesList
UI -> ASC --  : Which Programme?
'''''''''''''''''''''''''''''''''''''''''

ASC -> UI ++ #application : Licenciatura Engenharia Informática
UI -> CPEC ++ #application : createAProgrammeEditionForTheCurrentSchoolYear(programmeName)

CPEC -> PR ++ #application : getProgrammeIDByName(programmeName)
PR --> CPEC -- : programmeID
CPEC -> SYR ++ #application : getCurrentSchoolYear()
SYR --> CPEC : schoolYearID
SYR --
CPEC -> PER ++ #application : createProgrammeEdition(programmeID, schoolYearID)
PER -> PEF ++ #application : createProgrammeEdition(programmeID, schoolYearID)

create "programmeEditionID:ProgrammeEditionID" as PEID
PEF -> PEID : <create> ()
create "programmeEdition:ProgrammeEdition" as PE
PEF -> PE : <create> (programmeEditionID, programmeID, schoolYearID)

PEF --> PER : programmeEdition
PEF--
ref over PER
    - verifies if ProgrammeEdition already exists in the repository.
    - add programmeEdition to the repository.
end ref
'PER -> PER : isProgrammeEditionAlreadyRegistered (programmeEdition)
'PER -> PER : add (programmeEdition)
PER --> CPEC : true
PER --
CPEC --> UI : true
CPEC --
UI --> ASC -- : Programme Edition created for the current school year!
participant "programmeNameList:List<NameWithNumbersAndSpecialChars>"
participant "programmeName:NameWithNumbersAndSpecialChars"
participant "programmeID:ProgrammeID"
participant "schoolYearID:SchoolYearID"
@enduml