@startuml
title : US18_Create A Programme Edition For The Current School Year
autonumber
Actor ASC

participant ":UI" as UI
participant ":CreateAProgrammeEditionForTheCurrentSchoolYearController" as CPEC
participant ":ProgrammeList" as PL
participant ":SchoolYearRepository" as SYR
participant ":ProgrammeEditionRepository-" as PER
participant ":ProgrammeEditionFactory" as PEF

ASC -> UI ++ #application : I want to create a programme edition for the current school year
UI -> CPEC ++ #application : getAllProgrammeNames()
CPEC -> PL ++ #application : getAllProgrammeNames()
PL --> CPEC -- : programmeNamesList
CPEC --> UI -- : programmeNamesList
UI -> ASC --  : Which Programme?
ASC -> UI ++ #application : Licenciatura Engenharia Informática
UI -> CPEC ++ #application : createAProgrammeEditionForTheCurrentSchoolYear(Licenciatura Engenharia Informática)

CPEC -> PL ++ #application : getProgrammeByName(Licenciatura Engenharia Informática)
PL --> CPEC -- : programme
CPEC -> SYR ++ #application : getCurrentSchoolYear()
SYR --> CPEC : currentSchoolYear
SYR --
CPEC -> PER ++ #application : createProgrammeEdition(programme, currentSchoolYear)
PER -> PEF ++ #application : createProgrammeEdition(programme, currentSchoolYear)
create "programmeEdition:ProgrammeEdition" as PE
PEF -> PE : <create> (programme, currentSchoolYear)
PEF --> PER : programmeEdition
PEF--
PER -> PER : isProgrammeEditionAlreadyRegistered (programmeEdition)
PER -> PER : add (programmeEdition)
PER --> CPEC : true
PER --
CPEC --> UI : true
CPEC --
UI --> ASC -- : Programme Edition created for the current school year!
participant "programmeNameList:List<String>"
participant "programme:Programme"
participant "currentSchoolYear:SchoolYear"
@enduml