@startuml

skinparam ranksep 150
skinparam nodesep 120
skinparam packageBorderColor #F0B0B0
skinparam arrowThickness 1.2
skinparam linetype ortho
top to bottom direction

package Controller {
    class US18_CreateProgrammeEditionForCurrentSchoolYearController <<controller>> {
        + US18_CreateProgrammeEditionForCurrentSchoolYearController(programmeEditionRepository : ProgrammeEditionRepository, schoolYearRepository : SchoolYearRepository, programmeList : ProgrammeList)
        + getAllProgrammeNames() : List<NameWithNumbersAndSpecialChars>
        + createAProgrammeEditionForTheCurrentSchoolYear(programmeName : NameWithNumbersAndSpecialChars) : boolean
    }
}

package Service {

    package SchoolYear {
            class SchoolYearServiceImpl
            interface ISchoolYearService <<interface>>
    }

    package Programme {
        class ProgrammeServiceImpl
        interface IProgrammeService <<interface>>
    }

    package ProgrammeEdition {
            class ProgrammeEditionServiceImpl
            interface IProgrammeEditionService <<interface>>
    }
}


'interface "IRepository<ProgrammeID, Programme>" as IRepository <<interface>>


package repository{

    interface JpaRepository

    together{
    class SchoolYearRepositorySpringDataImpl {
        - _SchoolYearRepository
        + getAllSchoolYears()
    }
    interface ISchoolYearRepository <<interface>>  {}
    interface ISchoolYearRepositorySpringData <<interface>> {}
    }

    together{
    class ProgrammeRepositorySpringDataImpl {
        - _ProgrammeRepository
        + getAllProgrammes()
    }
    interface IProgrammeRepository <<interface>> {}
    interface IProgrammeRepositorySpringData <<interface>> {}
    }

    together{
    class ProgrammeEditionRepositorySpringDataImpl {
        - _ProgrammeEditionRepository
        + getAllProgrammeEditions()
    }
    interface IProgrammeEditionRepository <<interface>> {}
    interface IProgrammeEditionRepositorySpringData <<interface>> {}
    }
}

package datamodel{

    together{
        interface ISchoolYearMapper <<interface>>
        class SchoolYearMapperImpl
        class SchoolYearDataModel
    }

    together{
        interface IProgrammeMapper <<interface>>
        class ProgrammeMapperImpl
        class ProgrammeDataModel
    }

    together{
        interface IProgrammeEditionMapper <<interface>>
        class ProgrammeEditionMapperImpl
        class ProgrammeEditionDataModel
    }
}


package domain {

    package "SchoolYear Aggregate" {
        entity "<<Root>>\n<<Entity>>\nSchoolYear" {}
        class "<<Value Object>>\nSchoolYearID" {}
    }

    package "Programme Aggregate" {
        entity "<<Root>>\n<<Entity>>\nProgramme" {}
        class "<<Value Object>>\nProgrammeID" {}
    }

    package "ProgrammeEdition Aggregate" {
        entity "<<Root>>\n<<Entity>>\nProgrammeEdition" {}
        class "<<Value Object>>\nProgrammeEditionID" {}
        interface IProgrammeEditionFactory <<interface>> {}
        class ProgrammeEditionFactoryImpl {}
    }
}

Controller -[#white]- Service
Service --[#white]- Repository
Repository -[#white]- datamodel
Repository --[#white]- domain
datamodel --[#white]- domain

'Aggregates -[#white]- ValueObjects

' Controller uses Services Interfaces
US18_CreateProgrammeEditionForCurrentSchoolYearController "1" ..> "*" ISchoolYearService : uses
US18_CreateProgrammeEditionForCurrentSchoolYearController "1" ..> "*" IProgrammeEditionService : uses
US18_CreateProgrammeEditionForCurrentSchoolYearController "1" ..> "*" IProgrammeService : uses

' Services implement interfaces
SchoolYearServiceImpl .up.|> ISchoolYearService : implements
ProgrammeEditionServiceImpl .up.|> IProgrammeEditionService : implements
ProgrammeServiceImpl .up.|> IProgrammeService : implements

'RepositoriesSpring implements IRepositoriesSpring
'SchoolYear
SchoolYearRepositorySpringDataImpl "*" ..|> "1" ISchoolYearRepository : implements
SchoolYearRepositorySpringDataImpl "*" ..> "1" ISchoolYearRepositorySpringData : uses
ISchoolYearRepositorySpringData "1" --|> "1" JpaRepository : extends

'ProgrammeEdition
ProgrammeEditionRepositorySpringDataImpl "*" ..|> "1" IProgrammeEditionRepository : implements
ProgrammeEditionRepositorySpringDataImpl "*" ..> "1" IProgrammeEditionRepositorySpringData : uses
IProgrammeEditionRepositorySpringData "1" --|> "1" JpaRepository : extends

'Programme
ProgrammeRepositorySpringDataImpl "*" ..|> "1" IProgrammeRepository : implements
ProgrammeRepositorySpringDataImpl "*" ..> "1" IProgrammeRepositorySpringData : uses
IProgrammeRepositorySpringData "1" --|> "1" JpaRepository : extends


'Services Uses Repository
ISchoolYearService "1" ..> "1" ISchoolYearRepository : uses
IProgrammeEditionService "1" ..> "1" IProgrammeEditionRepository : uses
IProgrammeService "1" ..> "1" IProgrammeRepository : uses

'Mappers & DataModels
SchoolYearMapperImpl ..|> ISchoolYearMapper : implements
ISchoolYearMapper ..> SchoolYearDataModel : transforms to/from
ProgrammeMapperImpl ..|> IProgrammeMapper : implements
IProgrammeMapper ..> ProgrammeDataModel : transforms to/from
ProgrammeEditionMapperImpl ..|> IProgrammeEditionMapper : implements
IProgrammeEditionMapper ..> ProgrammeEditionDataModel : transforms to/from

'Repository & Mapper
ISchoolYearRepository ..> ISchoolYearMapper : uses
IProgrammeRepository ..> IProgrammeMapper : uses
IProgrammeEditionRepository ..> IProgrammeEditionMapper : uses

'Services Uses Factory
'ISchoolYearService -down-> ISchoolYearFactory: uses
'IAccessMethodService -down-> IAccessMethodFactory: uses
IProgrammeEditionService -down-> IProgrammeEditionFactory: uses


'Domain
'SchoolYear
"<<Root>>\n<<Entity>>\nSchoolYear" "1" --> "uses 1" "<<Value Object>>\nSchoolYearID"

'Programme
"<<Root>>\n<<Entity>>\nProgramme" "1" --> "uses 1" "<<Value Object>>\nProgrammeID"

'ProgrammeEdition
IProgrammeEditionFactory "1" ..> "1..*" "<<Root>>\n<<Entity>>\nProgrammeEdition" : creates
ProgrammeEditionFactoryImpl ..|> IProgrammeEditionFactory: implements
"<<Root>>\n<<Entity>>\nProgrammeEdition" "1" --> "uses 1" "<<Value Object>>\nProgrammeEditionID"





@enduml