@startuml

skinparam ranksep 150
skinparam nodesep 120
skinparam packageBorderColor #F0B0B0
skinparam arrowThickness 1.2
skinparam linetype ortho
top to bottom direction

package Controller {
    class US18_CreateProgrammeEditionForCurrentSchoolYearController <<controller>> {
        + US18_CreateProgrammeEditionForCurrentSchoolYearController(programmeEditionRepository : ProgrammeEditionRepository, schoolYearRepository : SchoolYearRepository, programmeList : ProgrammeList)
        + getAllProgrammeNames() : List<NameWithNumbersAndSpecialChars>
        + createAProgrammeEditionForTheCurrentSchoolYear(programmeName : NameWithNumbersAndSpecialChars) : boolean
    }
}

package Service {

    package SchoolYear {
            class SchoolYearServiceImpl
            interface ISchoolYearService
    }

    package Programme {
        class ProgrammeServiceImpl
        interface IProgrammeService
    }

    package ProgrammeEdition {
            class ProgrammeEditionServiceImpl
            interface IProgrammeEditionService
    }
}


'interface "IRepository<ProgrammeID, Programme>" as IRepository <<interface>>


package repository{

    Interface JpaRepository

    together{
    class SchoolYearRepositorySpringDataImpl {
        - _SchoolYearRepository
        + getAllSchoolYears()
    }
    interface "ISchoolYearRepository <<interface>>"  {}
    interface "ISchoolYearRepositorySpringData <<interface>>" {}
    }

    together{
    class ProgrammeRepositorySpringDataImpl {
        - _ProgrammeRepository
        + getAllProgrammes()
    }
    interface "IProgrammeRepository <<interface>>"  {}
    interface "IProgrammeRepositorySpringData <<interface>>" {}
    }

    together{
    class ProgrammeEditionRepositorySpringDataImpl {
        - _ProgrammeEditionRepository
        + getAllProgrammeEditions()
    }
    interface "IProgrammeEditionRepository <<interface>>"  {}
    interface "IProgrammeEditionRepositorySpringData <<interface>>" {}
    }
}

package datamodel{

    together{
        interface ISchoolYearMapper
        class SchoolYearMapperImpl
        class SchoolYearDataModel
    }

    together{
        interface IProgrammeMapper
        class ProgrammeMapperImpl
        class ProgrammeDataModel
    }

    together{
        interface IProgrammeEditionMapper
        class ProgrammeEditionMapperImpl
        class ProgrammeEditionDataModel
    }
}


package domain {

    package "SchoolYear Aggregate" {
        entity "<<Root>>\n<<Entity>>\nSchoolYear" {}
        class "<<Value Object>>\nSchoolYearID" {}
    }

    package "Programme Aggregate" {
        entity "<<Root>>\n<<Entity>>\nProgramme" {}
        class "<<Value Object>>\nProgrammeID" {}
    }

    package "ProgrammeEdition Aggregate" {
        entity "<<Root>>\n<<Entity>>\nProgrammeEdition" {}
        class "<<Value Object>>\nProgrammeEditionID" {}
        interface IProgrammeEditionFactory <<interface>> {}
        class ProgrammeEditionFactoryImpl {}
    }
}

Controller -[#white]- Service
Service --[#white]- Repository
Repository -[#white]- datamodel
Repository --[#white]- domain
datamodel --[#white]- domain

'Aggregates -[#white]- ValueObjects

' Controller uses Services Interfaces
US18_CreateProgrammeEditionForCurrentSchoolYearController "1" ..> "*" ISchoolYearService : uses
US18_CreateProgrammeEditionForCurrentSchoolYearController "1" ..> "*" IProgrammeEditionService : uses
US18_CreateProgrammeEditionForCurrentSchoolYearController "1" ..> "*" IProgrammeService : uses

' Services implement interfaces
SchoolYearServiceImpl .up.|> ISchoolYearService : implements
ProgrammeEditionServiceImpl .up.|> IProgrammeEditionService : implements
ProgrammeServiceImpl .up.|> IProgrammeService : implements

'RepositoriesSpring implements IRepositoriesSpring
'SchoolYear
SchoolYearRepositorySpringDataImpl "*" ..|> "1" "ISchoolYearRepository <<interface>>" : implements
SchoolYearRepositorySpringDataImpl "*" ..> "1" "ISchoolYearRepositorySpringData <<interface>>" : uses
"ISchoolYearRepositorySpringData <<interface>>" "1" --|> "1" JpaRepository : extends

'ProgrammeEdition
ProgrammeEditionRepositorySpringDataImpl "*" ..|> "1" "IProgrammeEditionRepository <<interface>>" : implements
ProgrammeEditionRepositorySpringDataImpl "*" ..> "1" "IProgrammeEditionRepositorySpringData <<interface>>" : uses
"IProgrammeEditionRepositorySpringData <<interface>>" "1" --|> "1" JpaRepository : extends

'Programme
ProgrammeRepositorySpringDataImpl "*" ..|> "1" "IProgrammeRepository <<interface>>" : implements
ProgrammeRepositorySpringDataImpl "*" ..> "1" "IProgrammeRepositorySpringData <<interface>>" : uses
"IProgrammeRepositorySpringData <<interface>>" "1" --|> "1" JpaRepository : extends


'Services Uses Repository
ISchoolYearService "1" ..> "1" "ISchoolYearRepository <<interface>>" : uses
IProgrammeEditionService "1" ..> "1" "IProgrammeEditionRepository <<interface>>" : uses
IProgrammeService "1" ..> "1" "IProgrammeRepository <<interface>>" : uses

'Mappers & DataModels
SchoolYearMapperImpl ..|> ISchoolYearMapper : implements
ISchoolYearMapper ..> SchoolYearDataModel : transforms to/from
ProgrammeMapperImpl ..|> IProgrammeMapper : implements
IProgrammeMapper ..> ProgrammeDataModel : transforms to/from
ProgrammeEditionMapperImpl ..|> IProgrammeEditionMapper : implements
IProgrammeEditionMapper ..> ProgrammeEditionDataModel : transforms to/from

'Repository & Mapper
"ISchoolYearRepository <<interface>>" ..> ISchoolYearMapper : uses
"IProgrammeRepository <<interface>>" ..> IProgrammeMapper : uses
"IProgrammeEditionRepository <<interface>>" ..> IProgrammeEditionMapper : uses

'Services Uses Factory
'ISchoolYearService -down-> ISchoolYearFactory: uses
'IAccessMethodService -down-> IAccessMethodFactory: uses
IProgrammeEditionService -down-> IProgrammeEditionFactory: uses


'Domain
'SchoolYear
"<<Root>>\n<<Entity>>\nSchoolYear" "1" --> "uses 1" "<<Value Object>>\nSchoolYearID"

'Programme
"<<Root>>\n<<Entity>>\nProgramme" "1" --> "uses 1" "<<Value Object>>\nProgrammeID"

'ProgrammeEdition
IProgrammeEditionFactory "1" ..> "1..*" "<<Root>>\n<<Entity>>\nProgrammeEdition" : creates
ProgrammeEditionFactoryImpl ..|> IProgrammeEditionFactory: implements
"<<Root>>\n<<Entity>>\nProgrammeEdition" "1" --> "uses 1" "<<Value Object>>\nProgrammeEditionID"





@enduml