package PAI.assembler.teacherCareerProgression;

import PAI.domain.teacherCareerProgression.TeacherCareerProgression;
import PAI.dto.teacherCareerProgression.*;

public interface ITeacherCareerProgressionAssembler {
    UpdateTeacherWorkingPercentageResponseDTO toUpdateWorkingPercentageDTO(TeacherCareerProgression teacherCareerProgression);
    UpdateTeacherWorkingPercentageCommand toUpdateTeacherWorkingPercentageCommand(UpdateTeacherWorkingPercentageRequestDTO request);
    UpdateTeacherCategoryResponseDTO toUpdateCategoryDTO(TeacherCareerProgression teacherCareerProgression);
    UpdateTeacherCategoryCommand toUpdateTeacherCategoryCommand(UpdateTeacherCategoryRequestDTO request) ;
}
