@startuml
autonumber

participant "pService:ProgrammeServiceImpl" as PS #implementation
participant "pMapper:ProgrammeAssembler" as PA #lightgreen
participant "programmeVOsDTO:ProgrammeVOsDTO" as PDTO

activate PS
PS -> PA ++: fromDTOToDomain(ProgrammeRequestDTO)
PA -> PDTO**: newProgrammeVOsDTO (nameVO, acronymVO, quantECTSVO \nquantSemestersVO, degreeTypeID, departmentID, teacherID)
activate PDTO
PDTO --> PA--: programmeVOsDTO
PA --> PS--: programmeVOsDTO
@enduml