@startuml
'!pragma layout smetana
'left to right direction

skinparam ranksep 30
skinparam nodesep 30
skinparam classBackgroundColor #E1F5FE
skinparam linetype ortho

class US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController {
    +US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController(
          programmeEditionEnrolmentRepo: IProgrammeEditionEnrolmentRepository,
          programmeEditionRepository: IProgrammeEditionRepository,
          programmeRepository: IProgrammeRepository,
          courseEditionEnrolmentRepository: ICourseEditionEnrolmentRepository,
          courseEditionRepository: ICourseEditionRepository,
          schoolYearRepository: ISchoolYearRepository,
          programmeEnrolmentRepository: IProgrammeEnrolmentRepository)
    +enrolStudentInProgrammeEditionAndSetOfCoursesEditionsController(studentId: StudentID, \n programmeId: ProgrammeID, schoolYearId: SchoolYearID)
    +getAllProgrammes(): List<ProgrammeID>
    +getAllSchoolYears(): List<SchoolYearID>
}

'Interfaces
interface IProgrammeEditionEnrolmentRepository {
    +enrolStudentInProgrammeEdition(studentId: StudentID, programmeEditionId: ProgrammeEditionID) : boolean
    +isStudentEnrolledInThisProgrammeEdition(studentId: StudentID, programmeEditionId: ProgrammeEditionID) : boolean
}

interface IProgrammeEditionRepository {
    +findProgrammeEditionBySchoolYearAndProgramme(programmeId: ProgrammeID, schoolYearId: SchoolYearID) : Optional<ProgrammeEditionID>
}

interface IProgrammeRepository {
    +getAllProgrammes() : List<ProgrammeID>
}

interface ICourseEditionEnrolmentRepository {
    +enrolStudentInACourseEdition (studentId: StudentID, courseEditionId: CourseEditionID) : boolean
    +findByStudentAndEdition (studentId: StudentID, courseEditionId: CourseEditionID) : Optional<CourseEditionEnrolment>
    +enrolStudentInProgrammeEditionCoursesEditions (studentId: StudentID, courseEditionsId: List<CourseEditionID>) : void
}

interface ICourseEditionRepository {
    +findCourseEditionsByProgrammeEdition(programmeEditionId: ProgrammeEditionID): List<CourseEditionId>
}

interface ISchoolYearRepository {
    +getAllSchoolYears() : List<SchoolYearId>
}

interface IProgrammeEnrolmentRepository {
    +isStudentEnrolled(studentId: StudentID, programmeId: ProgrammeID) : boolean
}

interface IProgrammeRepositoryListFactory {
    +copyProgrammeArrayList(List<ProgrammeID>)
}

interface ISchoolYearListFactory {
    +copySchoolYearArrayList(List<SchoolYear>)
}

interface IProgrammeEditionEnrolmentFactory{
    +newProgrammeEditionEnrolment(studentId: StudentID, programmeEditionId: ProgrammeEditionID)
}

interface IProgrammeEditionEnrolmentListFactory{
    +newProgrammeEditionEnrolmentList(): Set<ProgrammeEditionEnrolmentId>
}

'Repositories
class ProgrammeEditionEnrolmentRepositoryImpl {
    +ProgrammeEditionEnrolmentRepositoryImpl(programmeEditionEnrolmentFactory: ProgrammeEditionEnrolmentFactory,
          programmeEditionEnrolmentListFactory: ProgrammeEditionEnrolmentListFactory)
    +enrolStudentInProgrammeEdition(studentId: StudentID, programmeEditionId: ProgrammeEditionID) : boolean
    +isStudentEnrolledInThisProgrammeEdition(studentId: StudentID, programmeEditionId: ProgrammeEditionID) : boolean
}

class ProgrammeEditionRepositoryImpl {
    +ProgrammeEditionRepositoryImpl(programmeEditionFactory: ProgrammeEditionFactory)
    +findProgrammeEditionBySchoolYearAndProgramme(programmeId: ProgrammeID, schoolYearId: SchoolYearID) : Optional<ProgrammeEditionID>
}

class ProgrammeRepositoryImpl {
    +ProgrammeRepository(programmeFactory: ProgrammeFactory)
    +getAllProgrammes() : List<ProgrammeId>
}

class CourseEditionEnrolmentRepositoryImpl {
    +CourseEditionEnrolmentRepositoryImpl ()
    +enrolStudentInACourseEdition(studentId: StudentID, courseEditionId: CourseEditionID) : boolean
    +findByStudentAndEdition(studentId: StudentID, courseEditionId: CourseEditionID) : Optional<CourseEditionEnrolment>
    +enrolStudentInProgrammeEditionCoursesEditions(studentId: StudentID, courseEditions: List<CourseEditionID>) : void
}

class CourseEditionRepositoryImpl {
    +CourseEditionRepository(courseEditionFactory: CourseEditionFactory)
    +findCourseEditionsByProgrammeEdition(programmeEdition: ProgrammeEdition) : List<CourseEditionID>
}

class SchoolYearRepositoryImpl {
    +schoolYearRepository(schoolYearFactory: SchoolYearFactory, schoolYearListFactory: SchoolYearListFactory)
    +getAllSchoolYears() : List<SchoolYearID>
}

class ProgrammeEnrolmentRepositoryImpl {
    +()
    +isStudentEnrolled(studentId: ProgrammeEnrolmentRepositoryStudentID, programmeId: ProgrammeID) : boolean
}

class ProgrammeEditionRepositoryImpl {
    +ProgrammeEditionRepository(programmeEditionFactory: ProgrammeEditionFactory)
    +findProgrammeEditionBySchoolYearAndProgramme(programmeId: ProgrammeID, schoolYearId: SchoolYearID) : Optional<ProgrammeEditionID>
}

'Repository -> interface
IProgrammeEditionEnrolmentRepository <|.. ProgrammeEditionEnrolmentRepositoryImpl
IProgrammeEditionRepository <|.. ProgrammeEditionRepositoryImpl
IProgrammeRepository <|.. ProgrammeRepositoryImpl
ICourseEditionEnrolmentRepository <|.. CourseEditionEnrolmentRepositoryImpl
ICourseEditionRepository <|.. CourseEditionRepositoryImpl
ISchoolYearRepository <|.. SchoolYearRepositoryImpl
IProgrammeEnrolmentRepository <|.. ProgrammeEnrolmentRepositoryImpl

'Aggregates
package "CourseEditionEnrolment Aggregate" #Lightblue {
    class CourseEditionEnrolment <<Root>> <<Entity>> {
    +CourseEditionEnrolment(studentId:StudentID, courseEditionId: CourseEditionID)
    +hasStudent (studentId: StudentID) : boolean
    +hasCourseEdition (courseEditionId: CourseEditionID) : boolean
    }
}

package "ProgrammeEditionEnrolment Aggregate" #Lightblue {
    class ProgrammeEditionEnrolment <<Root>> <<Entity>> {
    +ProgrammeEditionEnrolment(studentId:StudentID, programmeEditionId: ProgrammeEditionID)
    +getStudentUniqueNumber() : String
    +equals (obj: Object) : boolean
    +findProgrammeEditionInEnrollment () : ProgrammeEditionID
    }
}

package "ProgrammeEditionEnrolment Aggregate" #Lightblue {
    class ProgrammeEditionEnrolment <<Root>> <<Entity>> {
    +ProgrammeEditionEnrolment(studentId:StudentID, programmeEditionId: ProgrammeEditionID)
    +getStudentUniqueNumber() : String
    +equals (obj: Object) : boolean
    +findProgrammeEditionInEnrollment () : ProgrammeEditionID
    }
}

package "Programme Aggregate" #Lightblue{
    class ProgrammeID <<Root>> <<Entity>>  {
     + ProgrammeID(name : String, acronym : String, quantityOfEcts: int, quantityOfSemesters : int,
          degreeTypeId : DegreeTypeID, departmentId : DepartmentID, programmeDirectorId : TeacherID, programmeCourseListFactory: ProgrammeCourseListFactory)
    }
 }

 package "Student Aggregate" #Lightblue{
     class StudentID <<Root>> <<Entity>> {
         +StudentID(uniqueNumber: int, name: Name, NIF: NIF, phone: Phone,
         email: Email, address: Address)
         + hasSameUniqueNumber(studentId : StudentID) : boolean
         + hasSameNIF(studentId : StudentID) : boolean
         + getUniqueNumber() : String
         + hasThisUniqueNumber(uniqueNumber : String) : boolean
     }
 }

 package "ProgrammeEdition Aggregate" #Lightblue{
     class ProgrammeEditionID <<Root>> <<Entity>> {
         +ProgrammeEditionID(programmeId: ProgrammeID, schoolYearId: SchoolYearID)
         +findProgrammeInProgrammeEdition() : ProgrammeID
         +findSchoolYearInProgrammeEdition() : SchoolYearID
     }
 }

 package "CourseEdition Aggregate" #Lightblue{
     class CourseEditionID <<Root>> <<Entity>> {
         +CourseEditionID(programmeEditionId: ProgrammeEditionID, course: Course)
         +whatProgrammeEditionBelongsThisCourseEdition() : ProgrammeEditionID
     }
 }

 package "SchoolYear Aggregate" #Lightblue{
     class SchoolYearID <<Root>> <<Entity>>  {
        -_description:String
        -_startData:String
        -_endDate:String
        +SchoolYearID(description: String, StartDate: String, EndDate: String)
    }
 }

package "ProgrammeEnrolment Aggregate" #Lightblue{
    class ProgrammeEnrolment <<Root>> <<Entity>> {
        +ProgrammeEnrolment(studentId: StudentID, accessMethod: AccessMethod)
        +getStudentFromEnrolment() : StudentID
        +getProgrammeFromEnrolment() : ProgrammeID
    }
}


'Value Objects

class CourseEditionEnrolmentId <<Value Object>>{
    -_id : long
    + CourseEditionEnrolmentId ( id: long)
    + getId(): long
    + equals(object: Object) : boolean
    + hashcode(): int
    + toString(): String

}

class ProgrammeEditionEnrolmentId <<Value Object>> {
    -_id : long
    + ProgrammeEditionEnrolmentId ( id: long)
    + getId(): long
    + equals(object: Object) : boolean
    + hashcode(): int
    + toString(): String

}

class ProgrammeId <<Value Object>> {
    -_id : long
    + SchoolYearId (id: long)
    + getId(): long
    + equals(object: Object) : boolean
    + hashcode(): int
    + toString(): String
}

class StudentID <<Value Object>> {
    -_uniqueNumber : int
    + StudentID(uniqueNumber : int)
    + isUniqueNumberValid()
}

class Name <<Value Object>> {
    -_name : String
    + Name(name : String)
    + isNameValid
}

class NIF <<Value Object>> {
    -_NIF : String
    + NIF(NIF : String)
    + isNIFInvalid()
}

class Phone <<Value Object>> {
    -_phone : String
    + Phone(phone : String)
    + isPhoneNumberValid
}

class Acronym <<Value Object>> {
     -_acronym : String
     + Acronym(acronym : String)
     + isAcronymInvalid(acronym : String)
}

class QuantEcts <<ValueObject>> {
    -_quantEcts: int
    + QuantEcts(quantityOfEcts : int)
    + isQuantEctsValid(quantityOfEcts : int)
}

class QuantityOfSemesters <<ValueObject>> {
    -_quantityOfSemesters: int
    + QuantSemesters(quantityOfSemesters: int)
    + isQuantityOfSemestersValid(quantityOfSemesters: int)
}

class ProgrammeID <<Value Object>> {
    -_programmeID :
}

class Email <<Value Object>> {
    -_email : String
    + Email(email : String)
}

class InstitutionalEmail <<Value Object>> {
    -_institutionalEmail : String
    + InstitutionalEmail(institutionalEmail : String)
    + generateInstitutionalEmail(uniqueNumber)
}
class Address <<Value Object>> {
        +Address(street: Street, postalCode: PostalCode, location: Location, country: Country)
        + getStreet() : Street
        + getPostalCode() : PostalCode
        + getLocation() : Location
        + getCountry() : Country
    }

class Street <<Value Object>> {
    -_street : String
    + Street(street : String)
    + validStreet
}

class PostalCode <<Value Object>> {
    -_postalCode : String
    + PostalCode(postalCode : String)
    + validPostalCode
}

class Location <<Value Object>> {
    -_location : String
    + Location(location : String)
    + validLocation()
}

class Country <<Value Object>> {
    -_country : String
    + Country(country : String)
    + validCountry()

}

class ProgrammeEnrolmentId <<Value Object>>{
    -_id : long
    + SchoolYearId (id: long)
    + getId(): long
    + equals(object: Object) : boolean
    + hashcode(): int
    + toString(): String
}

class CourseEditionId <<Value Object>>{
    -_id : long
    + CourseEditionId (id: long)
    + getId(): long
    + equals(object: Object) : boolean
    + hashcode(): int
    + toString(): String
}

class ProgrammeEditionId <<Value Object>> {
        -_id : long
        + ProgrammeEditionId (id: long)
        + getId(): long
        + equals(object: Object) : boolean
        + hashcode(): int
        + toString(): String
}

class SchoolYearId <<Value Object>>{
    -_id : long
    + SchoolYearId (id: long)
    + getId(): long
    + equals(object: Object) : boolean
    + hashcode(): int
    + toString(): String
    }

'Factory
class ProgrammeEditionEnrolmentFactoryImpl {
    +newProgrammeEditionEnrolment(studentId: StudentID, programmeEditionId: ProgrammeEditionID)
}

class ProgrammeEditionEnrolmentListFactoryImpl{
+newProgrammeEditionEnrolmentList(): Set<ProgrammeEditionEnrolmentID>
}

class CourseEditionEnrolmentListFactoryImpl {
    +newArrayList(): List<CourseEditionEnrolmentID>
}

class ProgrammeRepositoryListFactoryImpl {
    +copyProgrammeArrayList(List<Programme>): List<ProgrammeID>
}

class SchoolYearListFactoryImpl {
    +copySchoolYearArrayList(List<SchoolYear>) : List<SchoolYearID>
}


class CourseEditionListFactoryImpl{
    +newArrayList(CourseEditionID)
}


'Others

class HashSet{
    + add(): boolean
}

class ProgrammeArrayList {
    +add(): boolean
}

class ProgrammeEditionEnrolmentArrayList{
     +add(programmeEditionEnrolment: ProgrammeEditionEnrolment): boolean
}

class SchoolYearArrayList {
    +add(): boolean
}

class CourseEditionArrayList{
     +add(): boolean
}

' Controller - interfacesRepo
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1" ..> "1" IProgrammeEditionEnrolmentRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1" ..> "1" IProgrammeEditionRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1" ..> "1" IProgrammeRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1" ..> "1" ICourseEditionEnrolmentRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1" ..> "1" ICourseEditionRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1" ..> "1" ISchoolYearRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1" ..> "1" IProgrammeEnrolmentRepository

' Other connections
StudentID "1" --> "1 _address" Address
CourseEditionRepositoryImpl "1" -u-> "_listOfCE" CourseEditionID
CourseEditionRepositoryImpl "1" --> "1" CourseEditionListFactoryImpl
CourseEditionRepositoryImpl "1" --> "1" CourseEditionArrayList
CourseEditionArrayList "1" <.. "1" CourseEditionListFactoryImpl
CourseEditionArrayList "1 arrayOfCourseEdition" <.u. "*" CourseEditionID
CourseEditionEnrolment " " ..> " " ICourseEditionEnrolmentRepository
CourseEditionEnrolmentRepositoryImpl "1" --> "1" CourseEditionEnrolmentListFactoryImpl
CourseEditionEnrolmentRepositoryImpl "1" --> "1" HashSet
HashSet "1" <.. "1" CourseEditionEnrolmentListFactoryImpl
HashSet "1" <.. "*" SchoolYearID
ProgrammeEditionEnrolment"1" --> "1" StudentID
ProgrammeEditionEnrolmentRepositoryImpl "1" --> "1" ProgrammeEditionEnrolmentArrayList
IProgrammeEditionEnrolmentFactory <.. ProgrammeEditionEnrolmentRepositoryImpl
ProgrammeEditionEnrolmentArrayList "1" ..> "*" ProgrammeEditionEnrolment
ProgrammeEditionEnrolmentRepositoryImpl "1" ..> "1" ProgrammeEditionEnrolmentListFactoryImpl
ProgrammeEditionEnrolmentRepositoryImpl ..> IProgrammeEditionEnrolmentListFactory
IProgrammeEditionEnrolmentListFactory ..> ProgrammeEditionEnrolmentArrayList
IProgrammeEditionEnrolmentFactory <|.. ProgrammeEditionEnrolmentFactoryImpl
IProgrammeEditionEnrolmentListFactory <|.. ProgrammeEditionEnrolmentListFactoryImpl
ProgrammeEnrolmentRepositoryImpl "1" --> "*" ProgrammeEnrolment
ProgrammeRepositoryImpl ..> IProgrammeRepositoryListFactory
ProgrammeRepositoryImpl ..> ProgrammeID
ProgrammeRepositoryImpl "1" --> "1" ProgrammeArrayList
ProgrammeArrayList "1" --> " _programme *" ProgrammeID
IProgrammeRepositoryListFactory ..> ProgrammeArrayList
ProgrammeRepositoryListFactoryImpl ..|> IProgrammeRepositoryListFactory
SchoolYearRepositoryImpl ..> ISchoolYearListFactory
SchoolYearListFactoryImpl ..|> ISchoolYearListFactory
ISchoolYearListFactory ..> SchoolYearArrayList
SchoolYearRepositoryImpl ..> SchoolYearID
SchoolYearRepositoryImpl "1" --> "1" SchoolYearArrayList
SchoolYearArrayList "1" --> " _schoolYear *" SchoolYearID
ProgrammeEditionEnrolment "1"--> "1" ProgrammeEditionId
ProgrammeEditionEnrolment "1"--> "1" ProgrammeEditionEnrolmentId
ProgrammeEditionID "1" --> "1" ProgrammeEditionId
CourseEditionID "1" -->"1" CourseEditionId
ProgrammeEditionID "1" --> "1" SchoolYearId
SchoolYearID "1" --> "1" SchoolYearId
CourseEditionEnrolment "1" --> "1" StudentID
CourseEditionEnrolment "1" --> "1" CourseEditionId
CourseEditionEnrolment "1" --> "1" CourseEditionEnrolmentId
ProgrammeEnrolment "1" --> "1" ProgrammeId
ProgrammeID "1" --> "1" ProgrammeId
ProgrammeID "1" --> "1" Name
ProgrammeID "1" --> "1" Acronym
ProgrammeID "1" --> "1" QuantEcts
ProgrammeID "1" --> "1" QuantityOfSemesters
ProgrammeEnrolment "1" --> "1" StudentID
ProgrammeEnrolment "1" --> "1" ProgrammeEnrolmentId
StudentID "1" --> "1" StudentID
StudentID "*" --> "1" Name
StudentID "\n *" --> "1  " Email
StudentID "\n *" --> "1   " InstitutionalEmail
StudentID "\n *" --> "1 " Phone
StudentID "\n *" --> "1 " NIF
Address "  *" ---> "1" Street
Address "*                " ---> "1" PostalCode
Address " *" ---> "1" Location
Address " *" ---> "1" Country
@enduml
