@startuml
!pragma layout smetana

class US28_RemoveTheEnrollmentOfAStudentInACourseEdition_Controller {
    +US28_RemoveTheEnrollmentOfAStudentInACourseEdition_Controller(courseEditionEnrollmentRepository: CourseEditionEnrollmentRepository)
    +removeStudentEnrollment(student: Student, courseEdition: CourseEdition): boolean
}

class CourseEditionEnrollment {
    -_enrollmentDate: LocalDate
    -_isActive: boolean
    +CourseEditionEnrollment(student:Student, courseEdition: CourseEdition)
    +hasStudent() : boolean
    +hasCourseEdition() : boolean
    +isEnrollmentActive(): boolean
    +deactivateEnrollment(): void
}

class CourseEditionEnrollmentRepository {
    +CourseEditionEnrollmentRepository(courseEditionEnrollmentFactoryInterface: CourseEditionEnrollmentFactoryInterface,
    courseEditionEnrollmentListFactoryInterface: CourseEditionEnrollmentListFactoryInterface)
    +enrollStudentInACourseEdition (student: Student, courseEdition: CourseEdition): boolean
    +findByStudentAndEdition (student: Student, courseEdition: CourseEdition) : Optional <CourseEditionEnrollment>
    +removeEnrollment (student: Student, courseEdition: CourseEdition) : boolean
}

class Student {
    -_uniqueNumber:String
    -_name:String
    -_NIF:String
    -_phone:String
    -_email:String
    -_address:Address
    -_institutionalEmail:String
    +Student(uniqueNumber: String, name: String, NIF: String, phone: String, email: String, address: Address)
}

class CourseEdition {
    -_course: Course
    -_programmeEdition: ProgrammeEdition
    -_ruc: Teacher
    +CourseEdition(programmeEdition: ProgrammeEdition, course: Course)
}

class CourseEditionEnrollmentFactory {
    +createCourseEditionEnrollment(student: Student, courseEdition: CourseEdition)
}

class CourseEditionEnrollmentListFactory{
+getCourseEditionEnrollmentList(): Set<CourseEditionEnrollment>
}

interface CourseEditionEnrollmentFactoryInterface{
    +createCourseEditionEnrollment(student: Student, courseEdition: CourseEdition)
}
interface CourseEditionEnrollmentListFactoryInterface{
+getCourseEditionEnrollmentList():Set<CourseEditionEnrollment>
}


CourseEditionEnrollment "*" --> "_student 1" Student
CourseEditionEnrollment "*" --> "_courseEdition 1    " CourseEdition
US28_RemoveTheEnrollmentOfAStudentInACourseEdition_Controller "1" ..> "1 " CourseEditionEnrollmentRepository
CourseEditionEnrollmentFactoryInterface  <|..  CourseEditionEnrollmentFactory
CourseEditionEnrollmentListFactoryInterface  <|..  CourseEditionEnrollmentListFactory
CourseEditionEnrollmentRepository ..> CourseEditionEnrollmentFactoryInterface
CourseEditionEnrollmentFactoryInterface ..> CourseEditionEnrollment
CourseEditionEnrollmentRepository .u.> CourseEditionEnrollmentListFactoryInterface

@enduml
