@startuml
!pragma layout smetana

class US28_RemoveTheEnrollmentOfAStudentInACourseEdition_Controller {
    +US28_RemoveTheEnrollmentOfAStudentInACourseEdition_Controller(courseEditionEnrollmentRepository: CourseEditionEnrollmentRepository)
    +removeStudentEnrollment(student: Student, courseEdition: CourseEdition): boolean
}

class CourseEditionEnrollment {
    -_enrollmentDate: LocalDate
    -_isActive: boolean
    +CourseEditionEnrollment(student:Student, courseEdition: CourseEdition,
     enrollmentDate: LocalDate)
    +findStudentInCourseEditionEnrollment() : Student
    +findCourseEditionInEnrollment() : CourseEdition
    +isEnrollmentActive(): boolean
    +deactivateEnrollment(): void
}

class CourseEditionEnrollmentRepository {
    +CourseEditionEnrollmentRepository(courseEditionEnrollmentFactory: CourseEditionEnrollmentFactory)
    +enrollStudentInACourseEdition (student: Student, courseEdition: CourseEdition, enrollmentDate: LocalDate): boolean
    +findByStudentAndEdition (student: Student, courseEdition: CourseEdition) : Optional <CourseEditionEnrollment>
    +removeEnrollment (student: Student, courseEdition: CourseEdition) : boolean
}

class Student {
    -_uniqueNumber:int
    -_name:String
    -_NIF:String
    -_phone:String
    -_email:String
    -_address:Address
    +Student(uniqueNumber: int, name: String, NIF: String, phone: String, email: String, address: Address)
}

class CourseEdition {
    -_course: Course
    -_programmeEdition: ProgrammeEdition
    -_ruc: Teacher
    +CourseEdition(programmeEdition: ProgrammeEdition, course: Course)
}

class CourseEditionEnrollmentFactory {
    +createCourseEditionEnrollment(student: Student, courseEdition: CourseEdition, enrollmentDate: LocalDate)
}

CourseEditionEnrollment "*" --> "_student 1" Student
CourseEditionEnrollment "*" --> "_courseEdition 1    " CourseEdition
CourseEditionEnrollmentRepository"   1  " ..> "    _courseEditionEnrollments *  "CourseEditionEnrollment
CourseEditionEnrollmentFactory "1" ..> "      _courseEditionEnrollment 1"CourseEditionEnrollment : creates
CourseEditionEnrollmentRepository "1" --> "1 _courseEditionEnrollmentFactory      " CourseEditionEnrollmentFactory : uses
US28_RemoveTheEnrollmentOfAStudentInACourseEdition_Controller "1" ..> "1" CourseEditionEnrollmentRepository : uses
@enduml
