@startuml

title US28: Remove the enrollment of a student in a course edition

actor ASC #Orange/White
participant ":UI" as UI
participant ":US28_RemoveTheEnrollmentOfAStudentInACourseEditionController" as Controller
participant ":CourseEditionEnrollmentRepository" as Repository
participant ":CourseEditionEnrollment" as Enrollment

ASC -> UI : I want to remove the enrollment of a student in a course edition
activate UI
UI --> ASC : What student?
deactivate UI
ASC -> UI : Student!
activate UI
UI --> ASC : What course edition?
deactivate UI
ASC -> UI : Course edition!
activate UI

UI -> Controller : removeStudentEnrollment(student, courseEdition)
activate Controller

Controller -> Repository : removeEnrollment(student, courseEdition)
activate Repository
Repository -> Repository : findByStudentAndEdition(student, courseEdition)

Repository -> Enrollment : isEnrollmentActive()
activate Enrollment
Enrollment --> Repository : true
deactivate Enrollment

Repository -> Enrollment : deactivateEnrollment()
activate Enrollment
Enrollment --> Repository : Enrollment is now inactive
deactivate Enrollment

Repository --> Controller : true
deactivate Repository

Controller --> UI : true
deactivate Controller
UI --> ASC : Enrollment removed
deactivate UI

@enduml
