@startuml

title US28: Remove the enrollment of a student in a course edition

actor ASC #Orange/White
participant ":UI" as UI
participant ":US28_RemoveTheEnrollmentOfAStudentInACourseEditionController" as Controller
participant ":CourseEditionEnrollmentRepository" as Repository
participant ":CourseEditionEnrollment" as Enrollment

ASC -> UI : I want to deactivate the enrollment of a student in a course edition
UI --> ASC : What student?
ASC -> UI : Student!
UI --> ASC : What course edition?
ASC -> UI : Course edition!

UI -> Controller : removeStudentEnrollment(student, courseEdition)
activate UI

Controller -> Repository : removeEnrollment(student, courseEdition)
activate Repository
Repository -> Repository : findByStudentAndEdition(student, courseEdition)

Repository -> Enrollment : isEnrollmentActive()
activate Enrollment
Enrollment --> Repository : true
Repository -> Enrollment : deactivateEnrollment()
Enrollment --> Repository : Enrollment is now inactive
deactivate Enrollment

Repository --> Controller : true
deactivate Repository

Controller --> UI : true
deactivate UI
UI --> ASC : Enrollment removed

@enduml
