@startuml
skinparam sequence {
    LifeLineBorderColor Grey
    LifeLineBackgroundColor HoneyDew
}

title US28: As an ASC, I want to remove the enrolment of a student in a course edition - Sequence Diagram

actor ASC #Orange/White
participant ":UI" as UI
participant ":US28_Controller" as Controller
participant ":ICourseEditionEnrolmentRepository" as IRepo
participant "cee:CourseEditionEnrolment" as Enrolment
autonumber

ASC -> UI : I want to remove the enrolment\n of a student in a course edition
activate UI
UI --> ASC : What is the student ID?
deactivate UI
ASC -> UI : Student ID!
activate UI
UI --> ASC : What is the course edition ID?
deactivate UI
ASC -> UI : Course edition ID!
activate UI

UI -> Controller : removeStudentEnrolment\n(studentID, courseEditionID)
activate Controller

Controller -> IRepo : removeEnrolment\n(studentID, courseEditionID)
activate IRepo


IRepo -> IRepo : cee:findByStudentAndEdition\n(studentID, courseEditionID)

IRepo -> Enrolment : isEnrolmentActive()
activate Enrolment
Enrolment --> IRepo : true
deactivate Enrolment

IRepo -> Enrolment : deactivateEnrolment()
activate Enrolment
Enrolment --> IRepo : Enrolment status set to inactive
deactivate Enrolment


IRepo --> Controller : true
deactivate IRepo

Controller --> UI : true
deactivate Controller
UI --> ASC : Enrolment successfully removed
deactivate UI

@enduml
