@startuml
title: US19: As an ASC, I want to create a course edition\n(Process View - Level 3: Components (Frontend focus))
autonumber

skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam sequence {
  LifeLineBorderColor Grey
  LifeLineBackgroundColor HoneyDew
}
skinparam defaultTextAlignment center
skinparam shadowing true

actor ASC #LightBlue/White
participant "<<component>>\n:Router" as router #E1F5FE
participant "<<component>>\n:IDegreeTypeRestController\n(REST Controller)" as DegreeTypeController #E1F5FE
participant "<<component>>\n:IProgrammeRestController\n(REST Controller)" as ProgrammeController #E1F5FE
participant "<<component>>\n:ICourseInStudyPlanRestController\n(REST Controller)" as CSPController #E1F5FE
participant "<<component>>\n:IProgrammeEditionRestController\n(REST Controller)" as PEController #E1F5FE
participant "<<component>>\n:ICourseEditionRestController\n(REST Controller)" as CourseEditionController #E1F5FE

ASC -> router: GET /degreetypes
activate router
router -> DegreeTypeController: getAllDegreeTypes()
activate DegreeTypeController
DegreeTypeController --> router: List of Degree Types
deactivate DegreeTypeController
router --> ASC: 200 OK - List of Degree Types
deactivate router

ASC -> router: GET /programmes/{degreeTypeID}
activate router
router -> ProgrammeController: getProgrammesByDegreeTypeID(degreeTypeID)
activate ProgrammeController
ProgrammeController --> router: List of Programmes
deactivate ProgrammeController
router --> ASC: 200 OK - List of Programmes
deactivate router

ASC -> router: GET /coursesinstudyplan/{programmeID}
activate router
router -> CSPController: getCoursesInStudyPlanByProgrammeID(programmeID)
activate CSPController
CSPController --> router: List of Courses In Study Plan
deactivate CSPController
router --> ASC: 200 OK - List of Courses In Study Plan
deactivate router

ASC -> router: GET /programmeeditions/{programmeID}
activate router
router -> PEController: getProgrammeEditionsByProgrammeID(programmeID)
activate PEController
PEController --> router: List of Programme Editions
deactivate PEController
router --> ASC: 200 OK - List of Programme Editions
deactivate router

ASC -> router: POST /courseeditions
activate router
router -> CourseEditionController: createCourseEdition(JSON)
activate CourseEditionController
CourseEditionController --> router: 200 OK - Course Edition created
deactivate CourseEditionController
router --> ASC: 200 OK - Course Edition created
deactivate router
@enduml
