@startuml
title: US19: As an ASC, I want to create a course edition\n(Process View - Level 2: Containers)
autonumber

skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam sequence {
    LifeLineBorderColor Grey
    LifeLineBackgroundColor HoneyDew
}
skinparam defaultTextAlignment center
skinparam shadowing true

actor ASC  #LightBlue/White
participant "<<Container>>\nFrontend" as Frontend #E1F5FE
participant "<<Container>>\nBackend" as Backend #E1F5FE
database "<<Container>>\nDatabase" as Database #E1F5FE

ASC -> Frontend: Access course edition creation form
activate Frontend

Frontend -> Backend: GET /degreetypes
activate Backend
Backend -> Database: SELECT * FROM degree_types
activate Database
Database --> Backend: 200 OK + degree types
deactivate Database
Backend --> Frontend: 200 OK + degree types
deactivate Backend
Frontend --> ASC: Display degree type options
deactivate Frontend

ASC -> Frontend: Select degree type
activate Frontend
Frontend -> Backend: GET /programmes/{degreeTypeID}
activate Backend
Backend -> Database: SELECT * FROM programmes
activate Database
Database --> Backend: 200 OK + programmes
deactivate Database
Backend --> Frontend: 200 OK + programmes
deactivate Backend
Frontend --> ASC: Display programme options
deactivate Frontend

ASC -> Frontend: Select programme
activate Frontend
Frontend -> Backend: GET /course-in-study-plan/{acronym}
activate Backend
Backend -> Database: SELECT * FROM courses_in_study_plan
activate Database
Database --> Backend: 200 OK + courses in study plan
deactivate Database
Backend --> Frontend: 200 OK + courses in study plan
deactivate Backend
Frontend --> ASC: Display courses in study plan
deactivate Frontend

ASC -> Frontend: Select programme edition
activate Frontend
Frontend -> Backend: GET /programmeeditions/\nprogramme/{programmeacronym}
activate Backend
Backend -> Database: SELECT * FROM programme_editions
activate Database
Database --> Backend: 200 OK + programme editions
deactivate Database
Backend --> Frontend: 200 OK + programme editions
deactivate Backend
Frontend --> ASC: Display programme edition options
deactivate Frontend

ASC -> Frontend: Confirm course edition creation
activate Frontend
Frontend -> Backend: POST /courseeditions (...)
activate Backend
Backend -> Database: INSERT INTO course_editions (...)
activate Database
Database --> Backend: Confirmation + new courseEditionID
deactivate Database
Backend --> Frontend: 201 Created + course edition ID
deactivate Backend
Frontend --> ASC: Course edition created successfully!
deactivate Frontend
@enduml
