@startuml

title US14: As an HRC, I want to update the teacher's category in the system \n (Process View - Level 1 - System)

skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

actor HRC as admin
participant ":PAI" as System <<System>>

admin -> System: I want to update teacher's category!
activate System #E1F5FE

System --> admin: Provide a form with fields for date, \n teacher selection and teacher category selection!
deactivate System

admin -> System: Form submitted!
activate System #E1F5FE

System --> admin: Sure?
deactivate System

admin -> System: Yes!
activate System #E1F5FE

System --> admin: Ok!
deactivate System
@enduml