@startuml
autonumber

title UC: As an Administrator, I want to create a school year in the System\n(Process View Level 2)

skinparam {
    SequenceLifeLineBorderColor gray
    SequenceParticipantBorderColor darkblue
    DefaultTextAlignment center
}


participant "Frontend" as FE #lightblue
participant "Backend" as BE #lightblue



[o-> FE: startDate, endDate, description
activate FE #lightblue
FE -> BE : (POST) Request to create a school year \n(startDate, endDate, description)
activate BE #lightblue
BE ->o]: (INSERT) Persist school year to \nDatabase (School Year)

BE <-o]: School Year

BE --> FE: (201 Created) Created school year
deactivate BE #lightblue
[o<-- FE: School year created successfully!
deactivate FE #lightblue

@enduml
