@startuml

autonumber
skinparam {
  SequenceLifeLineBorderColor gray
  SequenceParticipantBorderColor darkgreen
  DefaultTextAlignment center
}

title UC: As an Administrator, I want to create a school year in the System\n(Process View Level 3)

actor Administrator as Admin #limegreen
participant ":UI" as UI #olivedrab
participant ":Controller" as C #seagreen
participant ":Service" as S #forestgreen
participant ":Repository" as R #lightseagreen
participant ":Domain" as D #teal
database BD #green


Admin -> UI: Request to create a school year
activate UI #seashell
UI --> Admin: Present School Year Form
deactivate UI #seashell
Admin -> UI: Fill School Year Form (startDate, endDate,\n description)
activate UI #seashell
UI -> C: Submit School Year Form
activate C #seashell
C -> S: Create School Year
activate S #seashell
S -> D: Create School Year
activate D #seashell
D --> S: School Year
deactivate D #seashell
S -> R: Check if School Year exists
activate R #seashell
R -> BD: Check if School Year exists
activate BD #seashell
BD --> R: School Year does not exist
deactivate BD #seashell
R --> S: School Year does not exist
deactivate R #seashell
S -> R: Save School Year
activate R #seashell
R -> BD: Save School Year
activate BD #seashell
BD --> R: Saved!
deactivate BD #seashell
R --> S: Saved!
deactivate R #seashell
S --> C: Saved!
deactivate S #seashell
C --> UI: Saved!
deactivate C #seashell
UI --> Admin: School Year created successfully!
deactivate UI #seashell
@enduml
