@startuml

autonumber
skinparam {
  SequenceLifeLineBorderColor gray
  SequenceParticipantBorderColor darkgreen
  DefaultTextAlignment center
}

title UC: As an Administrator, I want to create a school year in the System\n(Process View Level 3)

participant ":Routers" as Routers #olivedrab
participant ":ControllerRest" as C #seagreen
participant ":Service" as S #forestgreen
participant ":Domain" as D #teal
participant ":Repository" as R #lightseagreen


[o-> Routers: Fill School Year Form (startDate, endDate,\n description)
activate Routers #seashell
Routers -> C: Submit School Year Form
activate C #seashell
C -> S: Create School Year
activate S #seashell
S -> D: Create School Year
activate D #seashell
D --> S: School Year
deactivate D #seashell
S -> R: Check if School Year exists
activate R #seashell
R ->o]: Check if School Year exists

R<--o]: School Year does not exist

R --> S: School Year does not exist
deactivate R #seashell
S -> R: Save School Year
activate R #seashell
R ->o]: Save School Year

R<--o]: Saved!

R --> S: School Year!
deactivate R #seashell
S --> C: School YearDTO!
deactivate S #seashell
C --> Routers: School YearDTO!
deactivate C #seashell
[o<- Routers: School YearDTO!
deactivate Routers #seashell
@enduml
