@startuml

autonumber
skinparam {
  SequenceLifeLineBorderColor gray
  SequenceParticipantBorderColor black
  DefaultTextAlignment center
}

title As an Administrator, I want to create a school year in the System\n(Process View Level 3)

participant ":Routers" as Routers #ffe082
participant ":ControllerRest" as C #ffe082
participant ":Service" as S #ffe082
participant ":Domain" as D #ffe082
participant "SchoolYear1:SchoolYear" as SY #ffe082
participant ":Repository" as R #ffe082

[o-> Routers: **POST** /schoolyears \n(schoolYearDTO)
activate Routers #seashell
Routers -> C: createSchoolYear(schoolYearDTO)
activate C #seashell
C -> S: createSchoolYear(schoolYearDTO)
activate S #seashell

ref over S, D
**Transform:**
DTO → Domain Object
end ref

S -> D: addSchoolYear\n(description, startDate, endDate)
activate D #seashell
D -> SY**: addSchoolYear\n(description, startDate, endDate)
activate SY #seashell
SY --> D: schoolYear1
deactivate SY
D --> S: schoolYear1
deactivate D #seashell

S -> R: schoolYearExists(schoolYear1)
activate R #seashell
R ->o]: schoolYearExists(schoolYear1)

R<--o]: False

R --> S: False
deactivate R #seashell

S -> R: save(schoolYear1)
activate R #seashell
R ->o]: save(schoolYear1)

R<--o]: schoolYear1

R --> S: schoolYear1
deactivate R #seashell

ref over S, D
**Transform:**
Domain → DTO
end ref

S --> C: schoolYearDTO1
deactivate S #seashell
C --> Routers: schoolYearDTO1
deactivate C #seashell
[o<- Routers: (Created 201) schoolYearDTO1
deactivate Routers #seashell

@enduml
