@startuml
participant ":ISchoolYearRepository" as ISchoolYearRepository
participant ":SchoolYearRepository" as SchoolYearRepository

activate ISchoolYearRepository
ISchoolYearRepository -> SchoolYearRepository : getAllSchoolYearsIDs()
activate SchoolYearRepository

create ":SchoolYearArrayList"
SchoolYearRepository -> ":SchoolYearArrayList": create()
participant ":SchoolYear" as SchoolYear
loop for each "sy[i]:SchoolYearRepository" as SchoolYearRepository
SchoolYearRepository -> SchoolYear :  getAllSchoolYearsIDs()
participant ":SchoolYear" as SchoolYear
activate SchoolYear
SchoolYear --> SchoolYearRepository : syID
deactivate SchoolYear
SchoolYearRepository -> ":SchoolYearArrayList" :  add()
activate ":SchoolYearArrayList"
":SchoolYearArrayList" --> SchoolYearRepository: True
deactivate ":SchoolYearArrayList"
end
SchoolYearRepository --> ISchoolYearRepository : listOfSchoolYearsIDs
deactivate SchoolYearRepository

deactivate ISchoolYearRepository
@enduml