@startuml
participant ":IProgrammeEditionEnrolmentRepository" as ProgrammeEditionEnrolmentRepository
participant ":IProgrammeEditionEnrolmentRepositorySpringData" as ProgrammeEditionEnrolmentRepositorySpringData
participant ":ProgrammeEditionEnrolmentDataModel" as DataModel
participant ":ProgrammeEditionEnrolment" as Enrolment

ProgrammeEditionEnrolmentRepository -> ProgrammeEditionEnrolmentRepositorySpringData : findAll()
activate ProgrammeEditionEnrolmentRepositorySpringData
ProgrammeEditionEnrolmentRepositorySpringData --> ProgrammeEditionEnrolmentRepository : peeList
deactivate ProgrammeEditionEnrolmentRepositorySpringData

loop for each peeDataModel
    ProgrammeEditionEnrolmentRepository -> DataModel : toDomain(peeDataModel)
    activate DataModel
    DataModel --> ProgrammeEditionEnrolmentRepository : peeID
    deactivate DataModel

    ProgrammeEditionEnrolmentRepository -> Enrolment : hasSameStudent(studentId)

    ProgrammeEditionEnrolmentRepository -> Enrolment : hasSameProgrammeEdition(programmeEditionId)

end

@enduml
