@startuml
title Ref: Merge Both DTOs Data Into Single DTO (Backend - Granularity 4)
skinparam sequenceLifeLineBackgroundColor lightblue
skinparam sequenceMessageAlign center
autonumber

participant ":ProgrammeRestController" as ProgrammeRestController <<controller>> #F6CBA5
participant ":ProgrammeAssembler" as ProgrammeAssembler <<mapper>>
participant "programmeStudyPlanResponseDTO1:ProgrammeStudyPlanResponseDTO" as ProgrammeStudyPlanResponseDTO <<component>>

activate ProgrammeRestController
ProgrammeRestController -> ProgrammeAssembler ++: createProgrammeStudyPlanResponseDTO(programmeResponseDTO1, \nstudyPlanResponseDTO1)
ProgrammeAssembler -> ProgrammeStudyPlanResponseDTO **: createProgrammeStudyPlanResponseDTO(name, acronym, quantityOfECTS, \nquantSemesters, degreeTypeName, departmentName, teacherName, startDate, durationInYears)
activate ProgrammeStudyPlanResponseDTO
ProgrammeStudyPlanResponseDTO --> ProgrammeAssembler: programmeStudyPlanResponseDTO1
deactivate ProgrammeStudyPlanResponseDTO
ProgrammeAssembler --> ProgrammeRestController --: programmeStudyPlanResponseDTO1
@enduml