@startuml
title Ref: Convert Programme to DTO (Backend - Granularity 4)
skinparam sequenceLifeLineBackgroundColor lightblue
skinparam sequenceMessageAlign center
autonumber

participant ":ProgrammeRestController" as ProgrammeRestController <<controller>> #F6CBA5
participant ":ProgrammeAssembler" as ProgrammeAssembler <<mapper>>
participant "programmeResponseDTO1:ProgrammeResponseDTO" as ProgrammeResponseDTO <<component>>

activate ProgrammeRestController
ProgrammeRestController -> ProgrammeAssembler ++: createProgrammeResponseDTO(P1)
ProgrammeAssembler -> ProgrammeResponseDTO **: createProgrammeResponseDTO (name, acronym, quantECTS \nquantSemesters, degreeTypeName, departmentName, teacherName)
activate ProgrammeResponseDTO
ProgrammeResponseDTO --> ProgrammeAssembler: programmeResponseDTO1
deactivate ProgrammeResponseDTO
ProgrammeAssembler --> ProgrammeRestController --: programmeResponseDTO1
@enduml