@startuml
autonumber

title US06: Update Department Director Of A Department
actor Administrator
participant ":UI" as UI

activate Administrator #ddfada
Administrator -> UI: I want to update the Department Director of a Department!
activate UI #ddfada
participant ":US06_IWantToUpdateTheDepartmentDirectorOfADepartmentController" as Controller
UI -> Controller: getAllDepartmentIDs ()
activate Controller #ddfada
participant ":IDepartmentRepository" as IDepartmentRepository
Controller -> IDepartmentRepository: getDepartmentIDs ()
activate IDepartmentRepository #ddfada
IDepartmentRepository --> Controller: setOfDepartmentIDs
Controller --> UI: setOfDepartmentIDs


UI --> Administrator: What Department?
Administrator -> UI: Enter the Department!
UI --> Administrator: What Teacher?
Administrator -> UI: Enter the Teacher!
UI --> Administrator: Sure?
Administrator -> UI: Yes!


UI -> Controller : updateDepartmentDirector (departmentID, teacherID)
Controller -> IDepartmentRepository: updateOfDepartmentDirector(departmentID, teacherID)
participant ":Department" as Department
IDepartmentRepository -> Department: changeDirector (teacherID)
activate Department #ddfada
participant ":Teacher" as Teacher
Department -> Teacher: isInDepartment (departmentID)
activate Teacher #ddfada
Teacher --> Department: True
deactivate Teacher
Department --> IDepartmentRepository: True
deactivate Department
IDepartmentRepository --> Controller: True
deactivate IDepartmentRepository
Controller --> UI: True
deactivate Controller


UI --> Administrator: OK!
deactivate UI
deactivate Administrator


@enduml