@startuml
autonumber
title US06: Update Department Director Of A Department
actor Administrator
participant ":UI" as UI
participant ":US06_IWantToUpdateTheDepartmentDirectorOfADepartmentController" as Controller
participant ":IDepartmentService" as IDepartmentService
participant ":DepartmentServiceImpl" as DepartmentServiceImpl
participant ":IDepartmentRepository" as IDepartmentRepository
participant ":DepartmentRepositorySpringData" as DepartmentRepositorySpringData

activate Administrator #ddfada
Administrator -> UI: I want to update the Department Director of a Department!
activate UI #ddfada

UI -> Controller: UpdateDepartmentDirector(DepartmentID,directorID)
activate Controller #ddfada

ref over Controller
    Convert departmentID to VO
end ref

Controller -> IDepartmentService: UpdateDepartmentDirector(DepartmentID,directorID)
activate IDepartmentService #ddfada
ref over DepartmentServiceImpl
Domain to DataModel
end ref
IDepartmentService->DepartmentServiceImpl :UpdateDepartmentDirector(DepartmentID,directorID)
activate DepartmentServiceImpl #ddfada
DepartmentServiceImpl -> IDepartmentRepository :findDepartmentByID(departmentID)
activate IDepartmentRepository #ddfada
IDepartmentRepository -> DepartmentRepositorySpringData :findDepartmentByID(departmentID)
activate DepartmentRepositorySpringData #ddfada
DepartmentRepositorySpringData --> IDepartmentRepository  :Optional<Department> opDep
IDepartmentRepository -->DepartmentServiceImpl :Optional<Department> opDep
DepartmentServiceImpl -> IDepartmentRepository:save(department:Department)
IDepartmentRepository->DepartmentRepositorySpringData:save(department:Department)
DepartmentRepositorySpringData-->IDepartmentRepository:department:Department
deactivate DepartmentRepositorySpringData #ddfada
IDepartmentRepository-->DepartmentServiceImpl:department:Department
deactivate IDepartmentRepository #ddfada
DepartmentServiceImpl-->IDepartmentService:department:Department
ref over DepartmentServiceImpl
DataModel to Domain
end ref
deactivate DepartmentServiceImpl #ddfada
IDepartmentService-->Controller:True
deactivate IDepartmentService
Controller --> UI: True
deactivate Controller #ddfada


UI --> Administrator: OK!
deactivate UI
deactivate Administrator

@enduml