@startuml
actor ProgrammmeDirector as PD
participant UI #application
participant ":DefineRucForCourseEditionController" as C #application
participant ":CourseEditionRepository" as CER #application
participant ":TeacherRepository" as TR #application
participant  ":CourseEdition" as CE #application


PD -> UI ++ #application: I want to define the RUC for a Course Edition
UI -> C  : getCourseEdition()
activate C #application
C -> CER :getCourseEdition()
activate CER #application
C <-- CER : List <CourseEdition>
deactivate CER
UI <-- C : List <CourseEdition>
deactivate C
PD <-- UI --: Course Edition?
PD -> UI ++ #application: Course Edition 1
UI-> C : getTeachers()
activate C #application
C -> TR :getTeachers()
activate TR #application
TR --> C :List <Teacher>
deactivate TR
C --> UI :List <Teacher>
deactivate C
PD <-- UI -- : Teacher?
PD -> UI: Teacher 1
activate UI #application
UI -> C : defineRucForCourseEdition(CourseEdition, Teacher)
activate C #application
C -> CER : setRucInACourseEdition(ce1,t1)
activate CER #application
CER -> CE : setRuc(t1)
activate CE #application
CE --> CER :True
deactivate CE
CER --> C :True
deactivate CER
deactivate CE
C --> UI :True
deactivate C
UI --> PD : True
deactivate UI


@enduml