@startuml

title US14: As an HRC, I want to update the teacher's category in the system \n (Process View - Level 1 - System)

skinparam defaultTextAlignment center
skinparam shadowing true

left to right direction
skinparam packageStyle rectangle

actor "HRC" as admin

rectangle "<<PAI System>>" {
    usecase "I want to update the teacher's category in the system" as UC01
}

admin --> UC01

@enduml