@startuml
skinparam sequenceMessageAlign center

actor Admin
participant ":UI" as UI
participant "ctllr:Controller" as ctrl
participant "syr1:SchoolYearRepository" as syRepo
participant "sy[i]:SchoolYear" as SY

Admin -> UI : I want to create a School Year in the System
UI --> Admin : description?
Admin -> UI : description!
UI --> Admin : startDate?
Admin -> UI : startDate!
UI --> Admin : endDate?
Admin -> UI : endDate!

UI -> ctrl : I want to create a School Year in the System \n (description, startDate, endDate)
activate ctrl
ctrl -> syRepo : addSchoolYear \n (description,startDate,endDate)
activate syRepo
loop for each SchoolYear in syRepo
    syRepo -> SY : schoolYearExists(newSchoolYear)
    activate SY
    SY --> syRepo : False
    deactivate SY
end
create "sy1:SchoolYear" as SchoolYear
syRepo -> SchoolYear: createSchoolYear \n (description, startDate, endDate)
activate SchoolYear
SchoolYear -> SchoolYear : validateParameters()
SchoolYear -> SchoolYear : validateDateFormat()
SchoolYear --> syRepo: sy1
deactivate SchoolYear

syRepo -> syRepo : add(sy1)
syRepo --> ctrl : true
ctrl --> UI : true
UI --> Admin : Success

@enduml