@startuml

autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor #lightblue

participant "CECtrl:CourseEditionRestController" as ceC #lightgreen
participant "scDTOAssembler:StudentCountDTOAssembler" as A #lightblue
participant "studentCountDTO:StudentCountDTO" as DTO #strategy

activate ceC
ceC -> A ++: fromDomainToDTO(studentCount)
A -> DTO**: <Create> StudentCountDTO(studentCount)
activate DTO
DTO --> A--: studentCountDTO
A --> ceC--: studentCountDTO

@enduml