@startuml
autonumber

participant "CECtrl:CourseEditionRestController" as ceC #lightgreen
participant "CEAssembler:CourseEditionAssembler" as A #lightblue
participant "courseEditionID:CourseEditionID" as CE

activate ceC
ceC -> A ++: fromDTOToCourseEditionID(selectedCourseEditionIdDTO)
A -> CE**: newCourseEditionID(selectedCourseEditionIdDTO)
activate CE
CE --> A --: courseEditionID
deactivate CE
A --> ceC --: courseEditionID
@enduml