@startuml

autonumber

title Query database for all CourseEditions

participant "ceRepo:CourseEditionEnrolmentRepository" as R #lightblue
participant "JPA: EntityManager / Spring Data JPA" as JPA #lightblue
database "Database" as DB #lightblue

R -> JPA ++ #lightblue: execute findAllCourseEditions()
JPA -> DB ++ #lightblue: SELECT * FROM course_editions
DB --> JPA --: ResultSet with CourseEdition rows
JPA --> R --: List<CourseEdition>

@enduml