@startuml

autonumber

title Convert domain objects to CourseEditionDTOs

participant "ceCtrl:CourseEditionEnrolmentRestController" as C #lightblue
participant "CourseEdition" as CE #lightblue
participant "CourseEditionDTO" as DTO #lightblue

C -> CE ++ #lightblue: for each CourseEdition in List<CourseEdition>
loop for each courseEdition
    CE -> DTO ++ #lightblue: new CourseEditionDTO(courseEdition)
    DTO --> C --: courseEditionDTO
end
C --> C --: List<CourseEditionDTO>

@enduml