@startuml

autonumber

title As an ASC I want to change a Programme Director\n (Process View Level 3)


participant "<<Component>>\n:Router" as RT #lightpink
participant "<<Component>>\n:ProgrammeRestController" as C #lightgreen
participant "<<Component>>\n:ProgrammeService" as S #lightblue
participant "<<Component>>\n:ProgrammeRepository" as R #lightyellow
participant "<<Component>>\n:Domain"  as D #lightpink
participant "<<Component>>\n:Drivers" as Drivers #lightyellow




-> RT ++: (PATCH) /assigndirector

RT -> C ++: ChangeProgrammeDirector (ProgrammeDirectorDTO)
C -> S ++: ProgrammeDirectorVOsDTO
S -> R ++: Get Programmes
R -> Drivers ++: Retrieve Programmes
Drivers -> : ofIdentity(ProgrammeID)
Drivers <-- : List of Programmes
Drivers --> R --: List of Programmes
R --> S --: List of Programmes
S --> C --: List of Programmes

C -> S ++: Get Teachers
S -> R ++: Get Teachers
R -> Drivers ++: Retrieve all Teachers
Drivers -> : ofIdentity(TeacherID)
Drivers <-- : List of Teachers
Drivers --> R --: List of Teachers
R --> S --: List of Teachers
S --> C --: List of Teachers

C -> S ++: Change Programme Director

S -> D ++: Update Programme Director
D --> S --: Programme Director

S -> R ++: Save Programme Director
R -> Drivers ++: save(ProgrammeDirector)
Drivers -> : save(ProgrammeDirector)
Drivers <-- : ProgrammeDirector
Drivers --> R --: ProgrammeDirector
R --> S --: Saved Programme Director

S --> C --: Saved Programme Director
C --> RT --: Saved Programme Director
<-- RT --: (204) Programme Director


@enduml