@startuml
actor RUC
participant ":UI" as UI
participant ":US22_iWantToGradeAStudentInACourseEditionController" as ctr
participant ":CourseEditionEnrolmentRepository" as CEER
participant ":GradeStudentRepository" as GR
participant ":GradeStudentFactory" as GSF
participant "g1:Grade «Value Object»" as G
participant "LocalDate «ValueObject»" as D
participant "gs1:StudentGrade" as GS

autonumber

RUC -> UI ++ #application: I want to grade a Student in a Course Edition
UI --> RUC --: Grade, Date, CourseEdition, Student?
RUC -> UI ++ #application: Grade, Date, CourseEdition, Student!
UI -> ctr ++ #application : IWantToGradeStudent (Grade, Date, Student, CourseEdition)
ctr -> CEER ++ #application : isStudentEnrolledInCourseEdition (Student, CourseEdition)
CEER --> ctr -- : true


ctr -> GR ++ #application : addGradeToStudent (Grade, Date, Student, CourseEdition)
GR -> GR : !hasStudentAlreadyGradeAtThisCourseEdition(student,courseEdition)
GR -> GSF ++ #application : newStudentGrade (Grade, Date, Student, CourseEdition)

create G
GSF -> G ++ #application : <Create> new(grade)
G -> G : isGradeValid()
G -> GSF :  g1
deactivate G

create D
GSF -> D ++ #application : <Create> new(Date)
D -> D : isDateValid()
D --> GSF : d1
deactivate D


create GS
GSF -> GS ++ #application : <Create> (g1, d1, Student, CourseEdition)
GS --> GSF -- : sg1
GSF --> GR -- : sg1


GR -> GR : addGrade(sg1)
GR --> ctr --: sg1
ctr --> UI --: sg1
UI --> RUC --: Succeed

@enduml