@startuml
actor ProgrammeDirector
participant ":UI" as UI
participant ":IWantToKnowTheAverageGradeInACourseEditionCtr" as KA
participant ":GradeStudentRepository" as GR


ProgrammeDirector -> UI ++ #application: I want to know approval percentage of Course Edition
UI --> ProgrammeDirector -- : Course Edition?
ProgrammeDirector -> UI ++ #application: Course Edition!
UI -> KA ++ #application : knowTheAverageGrade(courseEdition1)
KA -> GR ++ #application : knowTheAverageGrade(courseEdition1)
GR -> GR :knowTheAverageGrade(courseEdition1)

GR --> KA --: Average Grade (courseEdition1)
KA --> UI --: Average Grade (courseEdition1)
UI --> ProgrammeDirector --: Average Grade (courseEdition1)

@enduml