@startuml
autonumber

skinparam sequence {
    LifelineBorderColor black
    LifelineBackgroundColor LightBlue
    ActorBorderColor black
    ActorBackgroundColor LightGray
}

title US16: Enroll a Student in a Course Edition\nProcess View – Level 3

participant ":Router" as RT
participant ":Controller" as CT
participant ":Service" as SE
participant ":Repository" as RE
participant ":Domain" as DM


 [o--> RT ++: (POST) /students/{id}/courses-edition-enrolments with JSON {request}
RT -> CT ++: enrolStudentInCourseEdition(CourseEditionEnrolmentDto)

CT -> SE ++: enrollStudentInCourseEdition(CourseEditionEnrolment)


SE -> DM ++: new CourseEditionEnrolment()
DM --> SE --: CourseEditionEnrolment

SE -> RE ++: save(CourseEditionEnrolment)


RE ->o]: Insert Data
RE <--o]: DataLinha


RE -> DM ++: new CourseEditionEnrolment()
DM --> RE --: CourseEditionEnrolment

RE --> SE --: CourseEditionEnrolment

SE --> CT --: CourseEditionEnrolment

CT --> RT --: HTTP 201 Created **with EntityModel<CourseEditionEnrolmentDto>**

[o-->  RT: HTTP 201 Created **with EntityModel<CourseEditionEnrolmentDto>**

@enduml