@startuml

title US13: As a HRC, I want to register a new teacher in the system, including all relevant data.

actor HRC
participant ":System" as System #Pink

HRC -> System: I want to register a new teacher including all relevant data.
activate System #silver
System --> HRC: Choose a teacher category from the list
HRC -> System: tc1
System --> HRC: Choose a department from the list
HRC -> System: dpt1
System --> HRC: What are the attributes?
HRC -> System: acronym, name, email, nif, phoneNumber,\nstreet, postcode, location,country,\nacademicBackground, workingPercentage, date
System --> HRC: Teacher registered!
deactivate System


Note Right HRC #Pink/White
    *tc1* = Teacher Category Object
    *dpt1* = Department Object
End Note
@enduml