@startuml

title US05: Register a Department in the System\nProcess View – Level 4

autonumber
skinparam sequence {
    LifelineBorderColor black
    LifelineBackgroundColor LightBlue
    ActorBorderColor black
    ActorBackgroundColor LightGray
    GroupBorderColor #cccccc
    GroupBackgroundColor #f2f2f2
}

actor "Administrator" as ADM
participant ":Frontend" as UI
participant ":DepartmentRestController" as Controller
participant ":IDepartmentAssembler" as Assembler
participant ":IDepartmentHateoasAssembler" as HAAssembler
participant ":IDepartmentRegistryService" as Service
participant ":IDepartmentRepository" as Repository
participant ":DepartmentFactory" as Factory
participant ":DepartmentDataModelMapper" as DataModelMapper
database "DB" as SpringDataRepo

group Human Interaction
ADM -> UI ++: Request to register a department
UI --> ADM --: Prompt: "Fill in department details"
ADM -> UI ++: Enter name and acronym
end group

group Controller Layer
UI -> Controller ++: (POST) /departments {request}
Controller -> Assembler ++: RegisterDepartmentRequest
Assembler --> Controller --: RegisterDepartmentCommand
end group


group Application + Domain Logic
Controller -> Service ++: createAndSaveDepartment
Service -> Factory ++: create Department
Factory --> Service --: Department
Service -> Repository ++: validate department
Repository -> SpringDataRepo ++: validate department
SpringDataRepo --> Repository --: validation
Repository --> Service --: validation
end group

group Persistence
Service -> Repository ++: save department
Repository -> DataModelMapper ++: map to DepartmentDataModel
DataModelMapper --> Repository --: DepartmentDataModel
Repository -> SpringDataRepo ++: save DepartmentDataModel
SpringDataRepo --> Repository --: persisted
Repository --> Service --: persisted
end group

group Response Mapping
Service --> Controller --: Department
Controller -> Assembler ++: assemble to DepartmentDTO
Assembler --> Controller --: DepartmentDTO
Controller -> HAAssembler ++: assemble to EntityModel<DepartmentDTO>
HAAssembler --> Controller --: EntityModel<DepartmentDTO>
end group

group HTTP Response
Controller --> UI --: HTTP 201 Created + \nEntityModel<DepartmentDTO>
UI --> ADM --: Success message
end group

@enduml
