@startuml

title US05: Register a Department in the System\nProcess View – Level 4

autonumber
skinparam sequence {
    LifelineBorderColor black
    LifelineBackgroundColor LightBlue
    ActorBorderColor black
    ActorBackgroundColor LightGray
    GroupBorderColor #cccccc
    GroupBackgroundColor #f2f2f2
}

actor "Administrator" as ADM
participant ":Frontend" as UI
participant ":Router" as RT
participant ":DepartmentRestController" as Controller
participant ":IDepartmentAssembler" as Assembler
participant ":IDepartmentHateoasAssembler" as HAAssembler
participant ":IDepartmentRegistryService" as Service
participant ":IDepartmentRepository" as Repository
participant ":DepartmentFactory" as Factory
participant ":DepartmentDataModelMapper" as DataModelMapper


ADM -> UI ++: Request to register a department
UI --> ADM --: Prompt: "Fill in department details"
ADM -> UI ++: Enter name and acronym


UI -> RT ++: POST /departments \n{body: name, acronym}
RT -> Controller ++: POST /departments {request}
Controller -> Assembler ++: RegisterDepartmentRequest
Assembler --> Controller --: RegisterDepartmentRequestVOs




Controller -> Service ++: createAndSaveDepartment (requestVOs)
Service -> Factory ++: createDepartment (name, acronym)
Factory --> Service --: department



Service -> Repository ++: containsOfIdentity (departmentId)
Repository -> : containsOfIdentity (departmentId)
Repository <-- : false
Repository --> Service --: false



Service -> Repository ++: save (department)
Repository -> DataModelMapper ++: toDataModel (department)
DataModelMapper --> Repository --: departmentDataModel
Repository -> : INSERT INTO departments
Repository <-- : departmentDataModel
Repository --> Service --: department


Service --> Controller --: department
Controller -> Assembler ++: toDTO (department)
Assembler --> Controller --: departmentDTO
Controller -> HAAssembler ++: toModel (departmentDTO)
HAAssembler --> Controller --: EntityModel<DepartmentDTO> departmentDTOHateoas


Controller --> RT --: HTTP 201 Created + departmentDTOHateoas
RT --> UI --: HTTP 201 Created + \ndepartmentDTOHateoas
UI --> ADM --: OK. Created.


@enduml
