@startuml
autonumber

skinparam sequence {
   LifelineBorderColor black
   LifelineBackgroundColor LightBlue
 }

title US05:\n Register a Department In The System\n Process View Level 2
actor ADM
participant "Frontend" as FE
participant "Backend" as BE
database DB

ADM -> FE ++: Request to register Department
FE --> ADM --: Request name, acronym
ADM -> FE ++: Enter name, acronym

FE -> BE ++: HTTP Request \n(POST) /departments
BE -> DB ++: Persist instance of department created
DB --> BE --: Registration confirmed
BE --> FE --: HTTP Response
FE --> ADM --: Registered department successfully

@enduml
