@startuml

' US34 - Enrol a Student in a Programme Edition (including the enrolment in a set of courses)
' Process View - Level 2 (Frontend, Backend, DB)

autonumber

skinparam sequence {
   LifelineBorderColor black
   LifelineBackgroundColor LightBlue
}

title US34: Enrol a Student in a Programme Edition (including the enrolment in a set of courses) \n (Process View - Level 2)

actor ASC
participant ":Frontend" as FE <<component>>
participant ":Backend" as BE <<component>>
database ":Database" as DB <<database>>

' Fase 1 – Consulta
ASC -> FE ++: Wants to enrol student in a programme edition
FE -> BE ++: Get programmes where student is enrolled \n(GET /programmes?studentID={id})
BE -> DB ++: Retrieve programmes where student is enrolled
DB --> BE --: List of programmes where student is enrolled
BE --> FE --: Return list of programmes (200 OK)
FE --> ASC --: Display programmes

ASC -> FE ++: Select programme and school year
FE -> BE ++: Get programe edition \n(GET /programme-editions?schoolYearID={id}&programmeID={id})
BE -> DB ++: Fetch programe edition by programme ID and school  ID
DB --> BE --: Programme edition fetched
BE --> FE --: Return programme edition
FE -> BE ++: Get course editions for programme edition \n(GET /course-editions?programmeEditionID={id})
BE -> DB ++: Fetch course editions by programme edition ID
DB --> BE --: List of course editions
BE --> FE --: Return course editions
FE --> ASC --: Display course edition list

'Fase 2 – Inscrição
ASC -> FE ++: Confirms enrolment (programme + selected courses)

FE -> BE ++: Submit programme edition enrolment \n(POST /programme-editions/enrolments/{editionID})
BE -> DB ++: Save programme edition enrolment
DB --> BE --: Programme edition enrolment saved
BE --> FE --: Programme enrolment confirmed (201 Created)

FE -> BE ++: Submit course editions enrolment \n(POST /course-editions/enrolments/{editionID})
BE -> DB ++: Save course editions enrolments
DB --> BE --: Course editions enrolments saved

BE --> FE --: Course enrolments confirmed (201 Created)
FE --> ASC --: Show enrolment success message

@enduml