@startuml

title US18: As an ASC, I want to create a programme edition for the current school year \n (Process View - Level 2 - System)

skinparam componentStyle component
skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

participant "Frontend" as frontend <<Component>>
participant "Backend" as backend <<Component>>
participant "Database" as DB <<Component>>

 -> frontend: I want to create a programme edition for the current school year!
activate frontend #E1F5FE

frontend -> backend: (GET) Request List Of Programmes
activate backend #E1F5FE
backend --> frontend: List of programmes


<-- frontend: What programme name?

 -> frontend: Entered programme name!


frontend -> backend: (GET) Request current school year
backend --> frontend: Current school year
<-- frontend: What school year uuid?

 -> frontend: Entered school year uuid!

<-- frontend: Sure?

 -> frontend: Yes!

frontend -> backend: (POST) Request create programme edition (name, uuid)

backend -> DB: (INSERT) Persist ProgrammeEdition (programmeEdition)
activate DB #LightGray
DB --> backend: programmeEdition
deactivate DB

backend --> frontend: (201, Created) programmeEdition created!
deactivate backend

 <-- frontend: Ok!
deactivate frontend

@enduml