@startuml

title US18: As an ASC, I want to create a programme edition for the current school year \n (Process View - Level 2 - Containers)

skinparam componentStyle component
skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

actor ASC as ASC

participant "Frontend" as frontend <<Container>>
participant "Backend" as backend <<Container>>

ASC -> frontend: I want to create a programme edition for the current school year!
activate frontend #E1F5FE

frontend -> backend: (GET) Request List Of Programmes
activate backend #E1F5FE
backend --> frontend: List of programmes


frontend --> ASC: What programme name?

ASC -> frontend: Entered programme name!


frontend -> backend: (GET) Request current school year
backend --> frontend: Current school year
frontend --> ASC: What school year uuid?

ASC -> frontend: Entered school year uuid!

frontend --> ASC: Sure?

ASC -> frontend: Yes!

frontend -> backend: (POST) Request create programme edition (name, uuid)

backend --> frontend: (201, Created) programmeEdition created!
deactivate backend

frontend --> ASC: Ok!
deactivate frontend

@enduml