@startuml

title US18: As an ASC, I want to create a programme edition for the current school year \n (Process View - Level 2 - Containers)

skinparam componentStyle component
skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

actor ASC as ASC
participant "Frontend" as frontend <<Component>>
participant "Backend" as backend <<Component>>
participant "Database" as DB <<Component>>

ASC -> frontend: I want to create a programme edition for the current school year!
activate frontend #E1F5FE

frontend -> backend: GET /programmes/ids
activate backend #E1F5FE
backend --> frontend: 200 + body {List<ProgrammeIDResponseDTO>}


ASC <-- frontend: What programme name?

ASC -> frontend: Entered programme name!


frontend -> backend: GET /schoolyears/current
backend --> frontend: 200 + body {CurrentSchoolYearResponseDTO}
ASC <-- frontend: What school year uuid?

ASC -> frontend: Entered school year uuid!

ASC <-- frontend: Sure?

ASC -> frontend: Yes!

frontend -> backend: POST /programmeeditions + body {"programme": {"name": "Computer Science Engineering","acronym": "CSE"}, "schoolYear": {"id": "7ed3c1a3-ec53-429a-ab57-1052bad47328"}}

backend -> DB: INSERT INTO programmeEdition (EDITION_PROGRAMME_ACRONYM, EDITION_PROGRAMME_NAME, EDITION_SCHOOL_YEAR) VALUES ('CSE','Computer Science Engineering','7ed3c1a3-ec53-429a-ab57-1052bad47328')
activate DB #LightGray
DB --> backend: programmeEdition
deactivate DB

backend --> frontend: 201 + body {ProgrammeEditionResponseDTO}
deactivate backend

ASC <-- frontend: Ok!
deactivate frontend

@enduml