@startuml

title US18: As an ASC, I want to create a programme edition for the current school year \n (Process View - Level 3 Granularity)

skinparam componentStyle component
skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

actor ASC as ASC
participant "UI" as ui <<Component>>
participant "RESTController" as controller <<Component>>
participant "Service" as service <<Component>>
participant "Repository" as repository <<Component>>
database DB

activate ASC
ASC -> ui: I want to create a programme edition for the current school year!
activate ui #E1F5FE

ui -> controller: (GET) Request List Of Programmes
activate controller #E1F5FE
controller -> service: Get all programmes
activate service #E1F5FE
service -> repository: Get all programmes
activate repository #E1F5FE
repository -> DB: Fetch all programmes
activate DB #E1F5FE
DB --> repository: List of programmeDataModel
deactivate DB #E1F5FE
repository --> service: List of programme
deactivate repository #E1F5FE
service --> controller: List of programmeDTO
deactivate service #E1F5FE
controller --> ui: List of programme

ui --> ASC: What programme name?

ASC -> ui: Entered programme name!

ui -> controller: (GET) Request Current School Year
controller -> service: Get current school year
activate service #E1F5FE
service -> repository: Get current school year
activate repository #E1F5FE
repository -> DB: Fetch school year
activate DB #E1F5FE
DB --> repository: schoolYearDataModel
deactivate DB #E1F5FE
repository --> service: schoolYear
deactivate repository #E1F5FE
service --> controller: schoolYearDTO
deactivate service #E1F5FE
controller --> ui: schoolYearDTO

ui --> ASC: What school year uuid?

ASC -> ui: Entered school year uuid!

ui --> ASC: Sure?

ASC -> ui: Yes!

ui -> controller: (POST) Request create programme edition (nameDTO, uuidDTO)

controller -> service: Create programme edition (name, uuid)
activate service #E1F5FE
service -> repository: Create programme edition (nameVO, uuidVO)
activate repository #E1F5FE
repository -> DB: (INSERT) Persist ProgrammeEdition (nameVO, uuidVO)
activate DB #E1F5FE
DB --> repository: programmeEditionDataModel
deactivate DB #E1F5FE
repository --> service: programmeEdition
deactivate repository #E1F5FE
service --> controller: programmeEditionDTO
deactivate service #E1F5FE

controller --> ui: (201, Created) programmeEditionDTO
deactivate controller #E1F5FE

ui --> ASC: Ok!
deactivate ui
deactivate ASC

@enduml