@startuml
skinparam Shadowing true

title UC: Enrol Student in Programme\n(Process View Level 3)
autonumber

participant "Router" as RO
participant "RESTController" as RC
participant "Service" as S
participant "Repository" as R
participant "Domain" as D

[o-> RO ++: POST / students/enrol-programme /\n{studentID, accessMethodID, programmeAcronym, date}\t
RO -> RC++: Request to Enrol Student in Programme
RC -> S++: Enrol Student in Programme
S -> D++: Create Programme Enrollment
D --> S--: Programme Enrollment

S -> R++: Validation of duplicate enrollment Create Programme Enrollment
R --> S--: Student not enrolled in Programme validated

S -> R++: Save Student Enrolled in Programme
R --> S--: Student Enrolled in Programme
S --> RC--: Student Enrolled in Programme

RO <-- RC--: Student Enrolled in Programme
[o<-- RO --:201 Created /\n{programmeEnrolmentGID, studentID,\naccessMethodID, programmeID, date,\n_links: {self: students/enroll}}

@enduml