@startuml
!pragma layout smetana

class TeacherCategory {
    - name: String
    + TeacherCategory(name: String)
    + getName(): String
}

class TeacherCategoryFactory {
    + createTeacherCategory(name: String): TeacherCategory
}

class TeacherCategoryRepository {
    - teacherCategoryRepositoryList: List<TeacherCategory>
    - teacherCategoryFactory: TeacherCategoryFactory
    + TeacherCategoryRepository(teacherCategoryFactory: TeacherCategoryFactory, teacherCategoryRepositoryListFactory: TeacherCategoryRepositoryListFactory)
    + registerTeacherCategory(name: String): boolean
    + getTeacherCategoryByName(name: String): Optional<TeacherCategory>
    + getTeacherCategoryList(): List<TeacherCategory>
}

class TeacherCategoryRepositoryListFactory {
    + getTeacherCategoryList(): List<TeacherCategory>
}

TeacherCategoryFactory --> TeacherCategory
TeacherCategoryRepositoryListFactory --> TeacherCategoryRepository
TeacherCategory "1..*" --> "1" TeacherCategoryRepository: teacherCategoryRepositoryList

@enduml