@startuml
autonumber

participant "pCtrl:ProgrammeRestController" as C #implementation
participant "pMapper:ProgrammeAssembler" as PA #lightgreen
participant "programmeDTO:ProgrammeDTO" as PDTO

activate C
C -> PA ++: fromDomainToDTO(Programme)
PA -> PDTO**: newProgrammeDTO (name, acronym, maxECTS \nquantSemesters, degreeTypeID, departmentID, teacherID)
activate PDTO
PDTO --> PA--: programmeDTO
PA --> C--: programmeDTO

@enduml