@startuml
autonumber

participant "pCtrl:ProgrammeRestController" as C #implementation
participant "pMapper:ProgrammeAssembler" as PA #lightgreen
participant "programmeDTO:ProgrammeDTO" as PDTO
participant "pHATEOASAssembler:ProgrammeHATEOASAssembler" as PHA #lightblue
participant "entityModel<ProgrammeDTO>:EntityModel<ProgrammeDTO>" as EM

activate C
C -> PA ++: fromDomainToDTO(Programme)
PA -> PDTO**: newProgrammeDTO (name, acronym, maxECTS \nquantSemesters, degreeTypeID, departmentID, teacherID)
activate PDTO
PDTO --> PA--: programmeDTO
PA --> C--: programmeDTO
C -> PHA ++: toModel(programmeDTO)
PHA -> EM**: newEntityModel(programmeDTO)
activate EM
EM --> PHA --: entityModel<ProgrammeDTO>
PHA --> C --: entityModel<ProgrammeDTO>

@enduml