@startuml
autonumber

participant "pController:ProgrammeRestController" as PS #implementation
participant "pAssembler:ProgrammeAssembler" as PA #lightgreen
participant "programmeVOsDTO:ProgrammeVOsDTO" as PDTO

activate PS
PS -> PA ++: fromDTOToDomain(ProgrammeDTO)
PA -> PDTO**: newProgrammeVOsDTO (nameVO, acronymVO, maxECTSVO \nquantSemestersVO, degreeTypeID, departmentID, teacherID)
activate PDTO
PDTO --> PA--: programmeVOsDTO
PA --> PS--: programmeVOsDTO
@enduml