@startuml
autonumber

participant "dtCtrl:DegreeTypeRestController" as C #implementation
participant "dtService:DegreeTypeService" as DTS #lightblue
participant "dtAssembler:DegreeTypeAssembler" as DTA #lightpink
participant "dtDTO:DegreeTypeDTO" as DTDTO #lightgreen
participant "dtRepo:DegreeTypeRepository" as DTR #technology
participant "dtMapper:DegreeTypeMapper" as M #lightyellow
participant "dtFactory:DegreeTypeFactoryImpl" as F #lightpink
participant "degreeType[i]:degreeType" as DT

activate C
C -> DTS ++: getAllDegreeTypes()

DTS -> DTR ++: findAll()

DTR -> : findAll()
DTR <-- : List<DegreeTypeDataModel>

loop for DegreeTypeDataModel[i]
DTR -> M ++: toDomainModel(degreeTypeDataModel[i])
M -> F ++: recreate(degreeTypeDataModel[i])
F -> DT**: newDegreeType(degreeTypeID, \n name, maxECTS)
activate DT
DT --> F --: degreeType[i]
F --> M --: degreeType[i]
M --> DTR --: degreeType[i]
end

DTR --> DTS --: List<DegreeType>
DTS --> C --: List<DegreeType>
C -> DTA ++: toDTOs(List<DegreeType>)
DTA --> C --: List<DegreeTypeDTO>
deactivate C

@enduml