@startuml
autonumber

participant "pCtrl:ProgrammeRestController" as C #implementation
participant "p:Programme" as P #lightblue
participant "pMapper:ProgrammeAssembler" as PA #lightgreen
participant "programmeIDDTO:ProgrammeIDDTO" as PDTO
participant "pHATEOASAssembler:ProgrammeHATEOASAssembler" as PHA #lightblue
participant "entityModel<ProgrammeIDDTO>:EntityModel<ProgrammeIDDTO>" as EM

activate C
C -> P ++: P1.identity()
P --> C --:programmeID
C -> PA ++: toDTO(programmeID)
PA -> PDTO**: newProgrammeIDDTO (acronym)
activate PDTO
PDTO --> PA--: programmeIDDTO
PA --> C--: programmeIDDTO
C -> PHA ++: toModel(programmeIDDTO)
PHA -> EM**: newEntityModel(programmeIDDTO)
activate EM
EM --> PHA --: entityModel<ProgrammeIDDTO>
PHA --> C --: entityModel<ProgrammeIDDTO>

@enduml