@startuml
title Convert VO to List<CourseEditionID>
autonumber
skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam defaultTextAlignment center
skinparam shadowing true


activate ":US16_EnrolAStudentInACourseEditionController" #E1F5FE
create ":List<ProgrammeEditionID>"
":US16_EnrolAStudentInACourseEditionController" -> ":List<ProgrammeEditionID>": create (List<ProgrammeEditionID>)

deactivate ":US16_EnrolAStudentInACourseEditionController"
@enduml