@startuml

title US30 As an ASC, I want to add a course to a programme using a Web UI. \n (Process View - Level 3 Granularity)

autonumber

participant "Router" as router <<component>> #teal
participant "RESTController" as restController <<component>> #teal
participant "Service" as service <<component>> #teal
participant "Domain" as domain <<component>> #teal
participant "Repository" as repository <<component>> #teal

-> router: addCourseToProgramme (semester,\n curricularYear,\n courseID,\n studyPlanID,\n durationOfCourse,\n quantityOfCreditsEcts)
activate router #E1F5FE

router -> restController: addCourseToProgramme (semester,\n curricularYear,\n courseID,\n studyPlanID,\n durationOfCourse,\n quantityOfCreditsEcts)
activate restController #E1F5FE

restController -> service: addCourseToProgramme (semester,\n curricularYear,\n courseID,\n studyPlanID,\n durationOfCourse,\n quantityOfCreditsEcts)
activate service #E1F5FE

service -> domain: addCourseToProgramme (semester,\n curricularYear,\n courseID,\n studyPlanID,\n durationOfCourse,\n quantityOfCreditsEcts)
activate domain #E1F5FE

domain -> service: courseInStudyPlan
deactivate domain

service --> repository: save(courseInStudyPlan)
activate repository
repository --> service: courseInStudyPlan
deactivate repository

service --> restController: courseInStudyPlan
deactivate service

restController --> router: (201, Created) courseInStudyPlanDTO
deactivate restController

<-- router: (201, Created) courseInStudyPlanJSON

@enduml