@startuml

autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title As a Programme Director I want to know the Average Grade of a Course Edition of my Programme. \n(Process View lvl 3)
skinparam sequencemessagealign center

actor ProgrammeDirector
participant ":Router" as UI <<Component>> #application
participant ":Controller " as controller <<Component>> #motivation
participant ":Service" as service <<Component>> #business
participant ":Repository" as repo <<Component>> #technology

ProgrammeDirector -> UI : I want to know the average \n grade in a **CourseEdition**
activate UI
UI -> controller : Retrieve all Course Editions
activate controller
controller -> service : Retrieve all Course Editions
activate service
service -> repo : Retrieve all Course Editions
activate repo
repo ->  : Retrieve all Course Editions
repo <--  : All Course Editions
repo --> service : All Course Editions
deactivate repo
service --> controller : All Course Editions
deactivate service
controller --> UI : All Course Editions
deactivate controller


UI --> ProgrammeDirector : Choose a Course Edition
ProgrammeDirector -> UI : Course Edition!


UI -> controller ++: Calculate average grade

controller -> service ++: Calculate average grade

service -> repo ++: Retrieve students' grades
repo -->  : Retrieve students' grades
repo <-- : All Students' grades
repo --> service --: All Students' grades


service --> controller --: Course Edition's average

controller --> UI --: Course Edition's average

UI --> ProgrammeDirector : Course Edition's average!
deactivate UI

@enduml