@startuml

skinparam rectangle {
  BorderColor Orange
  BackgroundColor White
}

rectangle " " as SystemBox {

  artifact "LogicalView Level 1" as D1

  component "<system>\nPAI" as PAI {
  }

  interface "UI" as UI
  interface "POI Lib" as POI

  UI -right- PAI
  PAI -( POI
}

@enduml
