@startuml
!pragma layout smetana

title "PAI \n (Logical View - Level 2)"

interface UI
interface "API REST"


component "<<System>>\nPAI" {
  portin " " as p1
  portin " " as p2
  component Backend
  component Frontend
  component BD
  interface " " as I1

}

component Frontend {
portin " " as p4
}

component Backend {
portin " " as p5
portout " " as p6
}



I1 -right- BD
p5-up- p4
p1 -up- UI
p2 -up- "API REST"
p2 -down-p5
p1 -down-p4
p6 -down-(I1


@enduml
