@startuml

skinparam componentStyle component
skinparam ArrowColor black
skinparam defaultTextAlignment center

title "PAI - Logical View Level 3"

  interface "API" as API
  interface "BD API" as BDAPI

component "Backend" as backend {
    portin " " as p1
    portin " " as p3

  rectangle "Drivers and frameworks " {

    component "Router"
    component Drivers

    Router -- p1
    Drivers -- p3

    interface " " as IDrivers

    Drivers -- IDrivers
  }

  rectangle "Application layer" {
    component Controller
    component Repository
    interface " " as IRepo
    interface " " as IController


    Repository -- IRepo
    Controller -right- IController

  }

  rectangle "Service layer" {
    component Service
    interface " " as IService

    Service - IService
  }

  rectangle "Domain layer" {
    component Domain
    interface " " as IDomain

    Domain -up- IDomain
  }

  p1 -up- API
  p3 -up-( BDAPI

  Router -down-( IController
  Repository -up-( IDrivers

  Controller -down-( IService
  Service -up-( IRepo
  Service -down-( IDomain
}

@enduml