@startuml
title US05: Register a Department in the System
'left to right direction'

class US05_RegisterADepartmentController {
    +US05_RegisterADepartmentController(departmentRepo: DepartmentRepository)
    +registerDepartment(acronym: String, name: String): boolean
}

class Department {
    -_acronym:String
    -_name:String
    +Department(departmentAcronym: String, departmentName: String)
    +hasSameAcronym(department: Department) : boolean
    +hasSameName(department: Department) : boolean
    +getName(): String
    +getAcronym(): String
}

class DepartmentRepository {
    + departmentRepository(departmentFactory: DepartmentFactory, departmentListFactory: DepartmentListFactory )
    +registerDepartment(departmentAcronym: String, departmentName: String) :boolean
}

class DepartmentFactory {
    +newDepartment(acronym: String, acronym: name): Department
}

class DepartmentListFactory {
    +newDepartmentList: ArrayList<>
}

class ArrayList {
    +add()
}

DepartmentRepository "1" ..> "*" Department
DepartmentRepository "1" -> "1" ArrayList
Department "1" <- "1" ArrayList
DepartmentRepository "1" ..> "_departmentsList 1" DepartmentListFactory
DepartmentListFactory "1" ..> "1" ArrayList
US05_RegisterADepartmentController "1  " ..> "            1\n_departmentRepo    " DepartmentRepository
Department "1" <- "1" DepartmentFactory
DepartmentFactory "1\n _departmentFactory" <.. "1" DepartmentRepository
@enduml