@startuml

autonumber
title As an Administrator, I want to configure a DegreeType in the System \n (Process View Level 3)

skinparam sequenceMessageAlign center


participant ":Router" as Router <<Component>> #application
participant ":DegreeTypeRestController" as Controller <<Component>> #motivation
participant ":IDegreeTypeRegistrationService" as Service <<Component>> #business
participant ":DegreeTypeRepositoryImpl" as Repo <<Component>> #technology
participant ":Domain" as Domain <<Component>> #physical

-> Router : POST /degreetypes/
activate Router
Router -> Controller : registerDegreeType(RegisterDegreeTypeRequest request)
activate Controller

Controller -> Service : createAndSaveDegreeType(RegisterDegreeTypeCommand requestCommand)
activate Service

Service -> Domain : create(Name name, MaxEcts maxEcts)
activate Domain
Domain --> Service : DegreeType
deactivate Domain

Service -> Repo : containsOfIdentity(DegreeTypeID id)
activate Repo

Repo ->  : containsOfIdentity(DegreeTypeID id)
Repo <--  : Degree Type does not exist

Repo --> Service : DegreeType does not exist
deactivate Repo

Service -> Repo : save(DegreeType degreeType)
activate Repo

Repo --> Service : DegreeType saved
deactivate Repo

Service --> Controller : DegreeType saved
deactivate Service

Controller --> Router : DegreeType saved
deactivate Controller

<-- Router : (200, OK) DegreeType Registered
deactivate Router


@enduml
