@startuml

autonumber
title As a RUC, I want to grade a Student in a Course Edition \n (Process View Level 3)
skinparam sequencemessagealign center
autonumber

actor RUC
participant ":UI" as ui #application
participant ":Controller" as controller #motivation
participant ":Service" as service #business
participant ":Repository" as repo #technology
participant ":Domain" as domain #physical
database db #wheat

RUC -> ui : Select **Student grading** in a **CourseEdition** functionality
activate ui
ui -> controller : Retrieve all Course Editions
activate controller
controller -> service : Retrieve all Course Editions
activate service
service -> repo : Retrieve all Course Editions
activate repo
repo -> db : Retrieve all Course Editions
activate db
db --> repo : All Course Editions
deactivate db
repo --> service : All Course Editions
deactivate repo
service --> controller : All Course Editions
deactivate service
controller --> ui : All Course Editions
deactivate controller


ui --> RUC : Choose a Course Edition

RUC -> ui : Fill in the **Student grading** information \n (Grade, Date, StudentID)

ui -> controller : Submit Student grading information

activate controller
controller -> service : Create a new Student grade

activate service
service -> repo : Validate grading constraints
activate repo
repo --> service : true
deactivate repo

service -> domain : Create new Student grade
activate domain
domain --> service : Student Grade
deactivate domain

service -> repo : save Student Grade
activate repo
repo -> db : save
activate db
db --> repo : saved!
deactivate db
repo --> service : Student Grade saved!
deactivate repo

service --> controller : Student Grade saved!
deactivate service

controller --> ui : Student Grade saved!
deactivate controller

ui --> RUC : Student graded successfully!
deactivate ui

@enduml