@startuml

skinparam sequencemessagealign center
autonumber

actor RUC
participant ":UI" as ui #application
participant "ceRESTctrllr:CourseEditionRESTController" as ctrlrREST #motivation
participant ":StudentGradeServiceImpl" as sr #business
participant ":CourseEditionEnrolmentRepositorySpringData" as ceer #technology
participant ":CourseEditionEnrolmentMapperImpl" as ceemp #strategy
participant ":StudentGradeFactoryImpl" as sgf #implementation
participant "sg1:StudentGrade" as gs #physical
participant "sgRepo1:StudentGradeRepositorySpringData" as sgr #lightgray
participant "iSGRepo:IStudentGradeRepositorySpringData" as IStudentGradeRepoSpringData #lightcoral
participant "sgMapper:StudentGradeMapper" as sgmp #mistyrose

RUC -> ui : I want to grade a Student in a Course Edition
activate ui
ui --> RUC : What is the Grade, Date, CourseEditionID and StudentID?
deactivate ui
RUC -> ui : grade, date, courseEditionID, studentID!
activate ui
ui -> ctrlrREST : registerStudentGrade (Grade, Date, StudentID, CourseEditionID)
activate ctrlrREST
ctrlrREST -> sr : newStudentGrade (grade, date, studentID, courseEditionID)

activate sr
sr -> ceer : isStudentEnrolledInCourseEdition (studentID, courseEditionID)
activate ceer

ceer -> ceer: findAll
ceer -> ceemp :  DataModel CEE
activate ceemp
ceemp --> ceer : List <CEE>
deactivate ceemp
ceer --> sr : true
deactivate ceer

sr -> sr : isDateGradeInRangeWithSchoolYear()
sr -> sr : hasStudentAlreadyGradeAtThisCourseEdition()

sr -> sgf : newGradeStudent (Grade,Date, StudentID, CourseEditionID)
activate sgf
create gs
sgf -> gs : <Create> (Grade,Date, StudentID, CourseEditionID)
activate gs
gs --> sgf : sg1
deactivate gs
sgf --> sr : sg1
deactivate sgf
sr -> sgr : save(sg1)
activate sgr
sgr -> IStudentGradeRepoSpringData : save(sg1)
activate IStudentGradeRepoSpringData
IStudentGradeRepoSpringData -> sgmp : toData(sg1)
activate sgmp
sgmp --> IStudentGradeRepoSpringData : studentDataModel
deactivate sgmp
IStudentGradeRepoSpringData --> sgr : sg1
deactivate IStudentGradeRepoSpringData
sgr --> sr -- : sg1
sr --> ctrlrREST -- : true
ctrlrREST --> ui -- : true
ui --> RUC : Success!
deactivate ui

@enduml