@startuml
actor RUC
skinparam sequencemessagealign center

title As a RUC, I want to grade a Student in a CourseEdition \n (Process View Level 1)

participant ":System" as System #lightblue

RUC -> System  : Select "Student grading in a Course Edition"
activate System
System --> RUC  : Which CourseEdition?
RUC -> System : Course Edition!
System --> RUC : Student Grading form
RUC -> System : grade, date, studentID
System --> RUC : Confirm?
RUC -> System : Confirm.
System --> RUC : Success!
deactivate System

@enduml