@startuml

autonumber
title As a RUC, I want to grade a Student in a Course Edition \n (Process View Level 2)

skinparam sequencemessagealign center

actor RUC as RUC
participant "Frontend" as FE #application
participant "Backend" as BE #strategy
database DB


''RUC -> FE: Grade a Student in a Course Edition
''activate FE
''FE --> RUC: Grade details?
''RUC -> FE: grade, date, studentID
''FE --> RUC : Which Course Edition?
''deactivate FE

RUC -> FE : Grade a Student in a Course Edition
activate FE
FE -> BE : (GET) \n Retrieve all Course Editions
activate BE
BE --> DB : (GET) \n Retrieve all Course Editions
activate DB
DB --> BE : All Course Editions
deactivate DB
BE --> FE : All Course Editions
deactivate BE
FE --> RUC : Choose a Course Edition
deactivate FE

RUC -> FE : Request to grade a Student in the Course Edition
activate FE
FE --> RUC: Grade details?
deactivate FE
RUC -> FE: grade, date, studentID
activate FE
FE -> BE : (POST) \n Grade a Student in a Course Edition
activate BE
BE -> DB: (INSERT) \n Save Student's grade in Course Edition to Database
activate DB
DB --> BE: StudentGrade
deactivate DB
BE --> FE: Created StudentGrade!
deactivate BE
FE --> RUC: Student graded successfully!
deactivate FE


@enduml