@startuml
actor ProgrammmeDirector as PD
participant UI #application
participant ":Controller" as C #application
participant ":CourseEditionRepository" as CER #application
participant ":TeacherRepository" as TR #application
participant  ":CourseEdition" as CE #application


PD -> UI : I want to define the RUC for a Course Edition
UI -> C  : defineRucForACourseEdition
activate C #application
C -> CER :getCourseEdition()
activate CER #application
C <-- CER : List CourseEdition
deactivate CER
UI <-- C : List CourseEdition
deactivate C
PD <-- UI : Course Edition?
PD -> UI: ce1
UI-> C : ce1
activate C #application
C -> TR :getTeacher()
activate TR #application
TR --> C :List Teacher
deactivate TR
C --> UI :List Teacher
deactivate C
PD <-- UI : Teacher?
PD -> UI: t1
activate UI #application
UI -> C : defineRucForACourseEditionController(CourseEdition, Teacher)
activate C #application
C -> CER : setRucInCourseEdition(ce1,t1)
activate CER #application
CER -> CE : setRuc(t1)
activate CE #application
CE --> CER :True
deactivate CE
CER --> C :True
deactivate CER
deactivate CE
C --> UI :True
deactivate C
UI --> PD : True
deactivate UI


@enduml