@startuml
title (US26) Process View Level 3 - getTotalEnrolledStudentsByDepartmentAndSchoolYear()

autonumber

participant "<<Component>>\n:Router" as RT #lightpink
participant "<<Component>>\n:Controller" as C #lightgreen
participant "<<Component>>\n:TotalEnrolledStudentsInProgrammesByDepartmentAndSchoolYearService" as S #lightblue
participant "<<Component>>\n:DepartmentRepository" as DR #lightyellow
participant "<<Component>>\n:SchoolYearRepository" as SYR #lightyellow
participant "<<Component>>\n:ProgrammeRepository" as PR #lightyellow
participant "<<Component>>\n:ProgrammeEditionRepository" as PER #lightyellow
participant "<<Component>>\n:ProgrammeEnrollmentRepository" as PEER #lightyellow
participant "<<Component>>\n:Drivers" as Driver #salmon

[o-> RT ++: **GET** /departments/{departmentId}/schoolYears/{schoolYearId}/programme-enrolments/count
RT -> C ++: countByDepartmentAndSchoolYear(departmentId, schoolYearId)
C -> S ++: getTotalEnrolledStudentsInProgrammes\nByDepartmentAndYear(command)

S -> DR++: existsById(departmentId)
DR -> Driver ++:
Driver ->o] : containsOfIdentity(departmentID)
Driver <--o] : True
Driver --> DR --: True
DR --> S --: True

S -> SYR++: existsById(schoolYearId)
SYR -> Driver ++:
Driver ->o] : containsOfIdentity(schoolYearID)
Driver <--o] : True
Driver --> SYR --: True
SYR --> S --: True

S -> PR++: findProgrammeIDsByDepartment(departmentId)
PR -> Driver++: findProgrammeIDsByDepartment(departmentId)
Driver ->o] : findProgrammeIDsByDepartment(departmentId)
Driver <--o] : List<programmeId>
Driver --> PR --: List<programmeId>
PR --> S--: List<programmeId>

S -> PER++: findProgrammeEditionIDsBySchoolYearID\nAndProgrammeIDs(schoolYearID, List<programmeId>)
PER -> Driver++: findProgrammeEditionIDsBySchoolYearID\nAndProgrammeIDs(schoolYearID, List<programmeId>)
Driver ->o] : findProgrammeEditionIDsBySchoolYearID\nAndProgrammeIDs(schoolYearID, List<programmeId>)
Driver <--o] : List<programmeEditionId>
Driver --> PER --: List<programmeEditionId>
PER --> S--: List<programmeEditionId>

S -> PEER++: findAll()
PEER --> Driver++: findAll()
Driver ->o] : findAll()
Driver <--o] : List<programmeEditionEnrollment>
Driver --> PEER --: List<programmeEditionEnrollment>
PEER --> S--: List<programmeEditionEnrollment>

S -> S: filter enrolments where programmeEditionEnrollment\n contains programmeEditionIDList\nand count them

S --> C--: count

C --> RT--: HTTP 200 OK + count

[o<-- RT: HTTP 200 OK + count

@enduml
