@startuml

skinparam sequenceMessageAlign center

actor ASC
participant ":UI" as UI
participant "ctrl1:RegisterStudentInSystemController" as ctrl
participant "sr1:StudentRepository" as SR
participant "sf1:StudentFactory" as SF
participant "s[i]:Student" as Student

ASC -> UI: I want to register a student in the system
activate UI
UI --> ASC: What is the Student's information?
ASC -> UI: Unique number, name, NIF, phone, email, Address
UI -> ctrl: I want to register a Student \n (Unique number, name, NIF, phone, email, Address)
activate ctrl
ctrl -> SR: registerStudent \n (Unique number, name, NIF, phone, email, Address)
activate SR

SR -> SF: newStudent(uniqueNumber, name, NIF, phone, email, Address)
activate SF
SF --> SR: s1 (new Student)
deactivate SF

SR -> SR : isStudentRepeated(s1)

loop for each Student in SR
    activate Student
    SR -> Student: hasSameUniqueNumber(s1) || hasSameNIF(s1)
end

Student --> SR : False
deactivate Student

SR -> SR: students.add(s1)
SR --> ctrl: True
deactivate SR
ctrl --> UI: True
deactivate ctrl
UI --> ASC: Success!
deactivate UI

@enduml