@startuml
autonumber
skinparam sequenceMessageAlign center
title Diagram Referenced in US08_SequenceDiagram

participant "ctrl1:RegisterStudentInSystemController" as Controller #lightblue
participant "sID:StudentID" as studentID #implementation
participant "name1:Name" as name #motivation
participant "nif1:NIF" as NIF #physical
participant "phone1:Phone" as phone #technology
participant "email1:Email" as email #business
participant "street1:Street" as street #strategy
participant "pc1:PostalCode" as postalCode #application
participant "l1:Location" as location #implementation
participant "c1:Country" as country #motivation
participant "aE1:StudentAcademicEmail" as academicEmail #physical

activate Controller
Controller -> studentID** : create StudentIDVO (uniqueNumber)
activate studentID
studentID --> Controller : studentIDVO
deactivate studentID

Controller -> name** : create NameVO (name)
activate name
name --> Controller : nameVO
deactivate name

Controller -> NIF**: create NIFVO (NIF, nifCountry)
activate NIF
NIF --> Controller: NIFVO
deactivate NIF

Controller -> phone** : create PhoneVO (countryCode, phoneNumber)
activate phone
phone --> Controller : phoneVO
deactivate phone

Controller -> email** : create EmailVO (email)
activate email
email --> Controller : emailVO
deactivate email

Controller -> street** : create StreetVO (street)
activate street
street --> Controller : StreetVO
deactivate street

Controller -> postalCode** : create PostalCodeVO (postalCode)
activate postalCode
postalCode --> Controller : PostalCodeVO
deactivate postalCode

Controller -> location** : create LocationVO (location)
activate location
location --> Controller : LocationVO
deactivate location

Controller -> country** : create CountryVO (country)
activate country
country --> Controller : CountryVO
deactivate country

Controller -> academicEmail** : create StudentAcademicEmailVO (uniqueNumber)
activate academicEmail
academicEmail --> Controller : StudentAcademicEmailVO
deactivate academicEmail

@enduml