@startuml
title: Get All Departments\n(Code View - Level 4)

autonumber

participant ":DepartmentController" as depCtrl
activate depCtrl
participant ":DepartmentService" as depService
participant ":DepartmentRepository" as depRepo
participant ":DepartmentAssembler" as depAssembler
participant ":DepartmentMapper" as depMapper
participant ":DepartmentFactory" as depFactory
database DB

depCtrl -> depService ++: getAllDepartments()
depService -> depRepo ++: findAll()
depRepo -> DB ++: SELECT * FROM departments
DB --> depRepo --: List<DepartmentDataModel>

loop for DepartmentDataModel[i]
depRepo -> depMapper ++: toDomain(DepartmentDataModel[i])
depMapper -> depFactory ++: newDepartment(acronym, name, DirectorID)
note over of depFactory
    Creates a new
    Department object
end note
depFactory --> depMapper --: Department
depMapper --> depRepo --: List<Department>
end

depRepo -> depService: List<Department>
depService -> depAssembler ++: toDtoList(List<Department>)

loop for Department[i]
    note over of depAssembler
        Invokes DepartmentDTO
             to construct object
    end note
end
depAssembler --> depService --: List<DepartmentDTO>
depService --> depCtrl --: List<DepartmentDTO>

legend right
  DTO = Data Transfer Object
  Mapper = Convert DataModel para Domain
  Assembler = Convert Domain para DTO
end legend

@enduml