@startuml
title: Get All School Years\n(Code View - Level 4)

autonumber

participant ":SchoolYearController" as syCtrl
activate syCtrl
participant ":SchoolYearService" as syService
participant ":SchoolYearRepository" as syRepo
participant ":SchoolYearAssembler" as syAssembler
participant ":SchoolYearMapper" as syMapper
participant ":SchoolYearDTO" as schoolYearDTO
participant ":SchoolYearFactory" as syFactory

database DB

syCtrl -> syService ++: getAllSchoolYears()
syService -> syRepo ++: findAll()
syRepo -> DB ++: SELECT * FROM school_years
DB --> syRepo --: List<SchoolYearDataModel>

loop for SchoolYearDataModel[i]
syRepo -> syMapper ++: toDomain(SchoolYearDataModel[i])
syMapper -> syFactory ++: newSchoolYear(startDate, endDate)
note over of syFactory
    Creates a new SchoolYear object
end note
syFactory --> syMapper --: SchoolYear
syMapper --> syRepo --: SchoolYear
end

syRepo -> syService: List<SchoolYear>
syService -> syAssembler ++: toDtoList(List<SchoolYear>)

loop for SchoolYear[i]
    note over of syAssembler
        Invokes SchoolYearDTO
             to construct object
    end note
end
syAssembler --> syService --: List<SchoolYearDTO>
syService --> syCtrl --: List<SchoolYearDTO>

legend right
  DTO = Data Transfer Object
  Mapper = Convert DataModel para Domain
  Assembler = Convert Domain para DTO
end legend

@enduml
