@startuml
actor ProgrammeDirector

participant "System" as S
participant ":Controller" as C
participant ":GradeStudentRepo" as GSR

ProgrammeDirector -> S : I want to know approval percentage of course section (courseEdition)
activate S
S -> C : knowApprovalRate()
activate C
C -> GSR : knowApprovalRate()
activate GSR
GSR -> GSR : knowApprovalRate()
GSR --> C : Approval Percentage (CE1)
deactivate GSR
C --> S : Approval Percentage (CE1)
deactivate C
S --> ProgrammeDirector : Succeed Approval Percentage (CE1)
deactivate S

@enduml
