@startuml
skinparam Shadowing true
title UC: Enrol Student in Programme\n(Process View Level 1)
autonumber

actor ASC as Admin
participant ":System" as System

Admin -> System  ++: I Want to enrol a Student in a Programme.
System --> Admin  --: Student Unique Number? Department?

Admin -> System  ++: Student Unique Number! Department!
System --> Admin  --: Programme?

Admin -> System  ++: Programme!
System --> Admin  --: Access Method?

Admin -> System  ++: Access Method!
System --> Admin  --: Enrolment Date?

Admin -> System  ++: Enrolment Date!
System --> Admin  --: Success! The student was enrolled successfully.

@enduml