@startuml
autonumber

skinparam sequence {
    LifelineBorderColor black
    LifelineBackgroundColor LightBlue
    ActorBorderColor black
    ActorBackgroundColor LightGray
    GroupBorderColor #cccccc
    GroupBackgroundColor #f2f2f2
}

title Register a "X" in the System\nProcess View – Level 3

participant ":Router" as RT
participant "request\n:XRequest" as request
participant "xDTO\n:XDTO" as XDTO
participant "emXDTO\n:EntityModel<XDTO>" as emXDTO
participant ":Controller" as CT
participant "requestVOs\n:XRequestVOs" as requestVOs
participant ":Service" as SE
participant ":Domain" as DM
participant "x:X" as X #lightBlue
participant ":Repository" as RE
participant ":Driver" as DV


[o-> RT ++: (POST) /xs \n{body: inputDetails}
RT --> request **: <create> \nXRequest(inputDetails)
RT -> CT ++: (POST) /xs (request)
CT -> requestVOs **: <create> \nXRequestVOs(request.attribute[i]s)


CT -> SE ++: createAndSaveX (requestVOs)


SE -> DM ++: createX (requestVOs.attribute[i]s)
DM -> X **: <create> X(requestVOs.attribute[i]s)
DM --> SE --: x



SE -> RE ++: save (x)
RE -> DV++: save (x)
DV ->o]: INSERT INTO xs
DV <--o]: x'
DV --> RE -- : x'
RE --> SE --: x'


SE --> CT --: x'
CT --> XDTO **: <create> xDTO(x')
CT --> emXDTO **: <create> \nEntityModel<XDTO>(xDTO)

CT --> RT --: HTTP 201 Created + \nemXDTO
[o<-- RT --: HTTP 201 Created + \nemXDTO


@enduml