@startuml

title US30 As an ASC, I want to add a course to a programme using a Web UI. \n (Process View - Level 3 - Backend)

autonumber

participant ":Router" as router <<component>> <<Router>> #teal
participant ":CourseInStudyPlanRESTController" as restController <<component>> <<RESTController>> #teal
participant ":CourseInStudyPlanService" as service <<component>> <<Service>> #teal
participant ":CourseInStudyPlanFactory" as factory <<component>> <<Factory>> #teal
participant ":Domain" as domain <<component>> <<Domain>> #teal
participant ":Repository" as repository <<component>> <<Repository>> #teal

note over router: JSON payload includes the following attributes:\n semester, curricularYear, courseID, studyPlanID,\n durationOfCourse, quantityOfCreditsEcts

-> router: addCourseToProgramme (JSON)
activate router #E1F5FE

note over router: The conversion from JSON to DTO is done automatically through the Spring Boot Framework


router -> restController: addCourseToProgramme (DTO)
activate restController #E1F5FE

ref over restController
    Convert addCourseToProgrammeRequestDTO
    to CourseInStudyPlanCommmand
end

restController -> service: addCourseToProgramme (command)
activate service #E1F5FE

service --> factory: createCourseInStudyPlan (command)
activate factory #E1F5FE
factory --> service: createCourseInStudyPlan (VO)
deactivate factory

service -> domain: addCourseToProgramme (VO)
activate domain #E1F5FE

'CRIAR LIGAÇÃO DE SERVICE A COMMAND

domain -> service: courseInStudyPlan
deactivate domain

service --> repository: save(courseInStudyPlan)
activate repository #E1F5FE

repository --> service: courseInStudyPlan
deactivate repository

ref over restController
    Convert courseInStudyPlanVO to courseInStudyPlanDTO
end

service --> restController: courseInStudyPlan
deactivate service

restController --> router: (201, Created) courseInStudyPlanDTO
deactivate restController

<-- router: (201, Created) courseInStudyPlanJSON

note over router: The conversion from DTO to JSON is done automatically through the Spring Boot Framework

@enduml