@startuml

title US30 As an ASC, I want to add a course to a programme using a Web UI. \n (Process View - Level 2)

skinparam componentStyle component
skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

actor ASC as asc #teal

participant "Frontend" as frontend <<conteiner>> #teal
participant "Backend" as backend <<conteiner>> #teal
participant "Database" as db <<conteiner>> #teal

asc -> frontend: I want to add Course to a Programme!
activate frontend #E1F5FE

frontend --> asc: Which programme?
deactivate frontend

asc -> frontend: Enter programme!
activate frontend #E1F5FE

frontend --> asc: Which course?
deactivate frontend

asc -> frontend: Enter course!
activate frontend #E1F5FE

frontend --> asc: Which curricular year?
deactivate frontend

asc -> frontend: Enter curricular year!
activate frontend #E1F5FE

frontend --> asc: Which semester?
deactivate frontend

asc -> frontend: Enter semester!
activate frontend #E1F5FE

frontend --> asc: Duration of course in semester?
deactivate frontend

asc -> frontend: Enter duration!
activate frontend #E1F5FE

frontend --> asc: Quantity of Credits?
deactivate frontend

asc -> frontend: Enter ECTS credits!
activate frontend #E1F5FE





frontend --> asc: Sure?
deactivate frontend

asc -> frontend: Yes!
activate frontend #E1F5FE

frontend -> backend: (POST) add Course to a Programme (semester, curricularYear,\n courseID, studyPlanID, durationOfCourse, quantityOfCreditsEcts)
activate backend #E1F5FE

backend -> db: (INSERT) Persist CourseInStudyPlan (semester, curricularYear,\n courseID, studyPlanID, durationOfCourse, quantityOfCreditsEcts)
activate db #E1F5FE
db --> backend: courseInStudyPlan
deactivate db

backend --> frontend: (201, Created) Course added to Programme!
deactivate backend

frontend --> asc: Ok!
deactivate frontend

@enduml