@startuml

title US30 As an ASC, I want to add a course to a programme using a Web UI. \n (Process View - Level 2)

skinparam componentStyle component
skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

participant ":Frontend" as frontend <<container>> #teal
participant ":Backend" as backend <<container>> #teal

-> frontend : I want to add a course to a programme

frontend -> backend: (POST) add Course to a Programme (CourseInStudyPlanRequestDTO)
activate backend #E1F5FE


backend --> frontend: (201, Created) Course added to Programme!
deactivate backend

<-- frontend : Course added to Programme!
deactivate frontend

@enduml