@startuml

title US30 As an ASC, I want to add a course to a programme using a Web UI. \n (Process View - Level 3 - Backend)

autonumber

participant ":Router" as router <<component>> <<Router>> #teal
participant ":CourseInStudyPlanRESTController" as restController <<component>> <<RESTController>> #teal
participant ":CourseInStudyPlanService" as service <<component>> <<Service>> #teal
participant ":Domain" as domain <<component>> <<Domain>> #teal
participant ":Repository" as repository <<component>> <<Repository>> #teal

note over router: JSON payload includes the following attributes:\n semester, curricularYear, courseID, studyPlanID,\n durationOfCourse, quantityOfCreditsEcts

-> router: POST addCourseToProgramme (JSON)
activate router #E1F5FE

note over router: The conversion from JSON to DTO is done automatically through the Spring Boot Framework

router -> restController: addCourseToProgramme (RequestDTO)
activate restController #E1F5FE

ref over restController
    Convert addCourseToProgrammeRequestDTO
    to addCourseToProgrammeCommand
end

restController -> service: addCourseToProgramme (command)
activate service #E1F5FE

service -> domain: addCourseToProgramme(command)
activate domain #E1F5FE

domain --> service: courseInStudyPlan
deactivate domain

service -> repository: save(courseInStudyPlan)
activate repository #E1F5FE

repository --> service: courseInStudyPlan
deactivate repository

ref over service
    Convert courseInStudyPlan
    to courseInStudyPlanServiceDTO
end


service --> restController: courseInStudyPlanServiceDTO
deactivate service
ref over restController
    Convert courseInStudyPlanServiceDTO
    to courseInStudyPlanResponseDTO
end

restController --> router: (201, Created) courseInStudyPlanResponseDTO

deactivate restController
<-- router: (201, Created) courseInStudyPlanJSON
deactivate router
note over router: The conversion from DTO to JSON is done automatically through the Spring Boot Framework

@enduml