@startuml
title US30 As an ASC, I want to add a course to a programme using a Web UI. \n (Process View - Level 3 - Backend)

autonumber
skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}

participant ":RESTController" as restController <<component>> <<RESTController>> #teal
participant ":IAssembler" as assembler <<component>> <<Assembler>> #teal

activate restController #LightBlue
restController -> assembler: toVO (courseCommand)

activate assembler #LightBlue
create "courseInStudyPlanVO: CourseInStudyPlanVO"
assembler -> "courseInStudyPlanVO: CourseInStudyPlanVO": createCourseInStudyPlan (command.name,\n command.code,\n command.ects,\n command.semester,\n command.year,\n command.programmeId)

deactivate assembler
deactivate restController

@enduml