@startuml
title US30 As an ASC, I want to add a course to a programme using a Web UI. \n (Process View - Level 3 - Backend)

autonumber
skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}

participant ":RESTController" as restController <<component>> <<RESTController>> #teal
participant ":IAssembler" as assembler <<component>> <<Assembler>> #teal

activate restController #LightBlue
restController -> assembler: toCommand (courseRequestDTO)

activate assembler #LightBlue
create "courseInStudyPlanCommand: CourseInStudyPlanCommand"
assembler -> "courseInStudyPlanCommand: CourseInStudyPlanCommand": createCourseInStudyPlan (requestDto.name,\n requestDto.code,\n requestDto.ects,\n requestDto.semester,\n requestDto.year,\n requestDto.programmeId)

deactivate assembler
deactivate restController

@enduml