@startuml
title US30 As an ASC, I want to add a course to a programme using a Web UI. \n (Process View - Level 3 - Backend)

autonumber
skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}

participant ":RESTController" as restController <<component>> <<RESTController>> #teal
participant ":IAssembler" as assembler <<component>> <<Assembler>> #teal

activate restController #LightBlue
restController -> assembler: toResponseDTO (courseVO)

activate assembler #LightBlue

create "courseInStudyResponseDTO: CourseInStudyPlanResponseDTO"
assembler -> "courseInStudyResponseDTO: CourseInStudyPlanResponseDTO": createCourseInStudyPlan (courseVO.name,\n courseVO.code,\n courseVO.ects,\n courseVO.semester,\n courseVO.year,\n courseVO.programmeId)

deactivate assembler
deactivate restController

@enduml