@startuml
title US16: Enroll a student in a course edition
actor ASC
participant ":System" as System
ASC -> System: I want to enroll a student in a course edition.
System --> ASC: What Student?
ASC -> System: Enter the student!
System --> ASC: What Course Edition?
ASC -> System: Enter the course edition!
System --> ASC: Sure?
ASC -> System: Yes!
System --> ASC: OK!


@enduml