@startuml
!pragma layout smetana

class US16_EnrollAStudentInACourseEditionController {
    +US16_EnrollAStudentInACourseEditionController(ceeRepository: CourseEditionEnrollmentRepository,
    peeRepository: ProgrammeEditionEnrollmentRepo , courseEditionRepository: CourseEditionRepository)
    +enrollStudentInCourseEdition(student: Student, courseEdition: CourseEdition): boolean
    +getProgrammeEditionsThatStudentIsEnrolled(student: Student): List<ProgrammeEdition>
    +getCourseEditionsOfProgrammeEdition(programmeEdition: ProgrammeEdition): List<CourseEdition>
}

class CourseEditionEnrollmentFactory{
    +createCourseEditionEnrollment(student: Student, courseEdition: CourseEdition)
}

class CourseEditionEnrollment {
    -_enrollmentDate: LocalDate
    - _isActive: boolean
    +CourseEditionEnrollment(student:Student, courseEdition: CourseEdition)
    +equals (obj: Object): boolean
}

class ProgrammeEditionArrayList{
    +add(programmeEdition: ProgrammeEdition): boolean
}

interface CourseEditionEnrollmentListFactoryInterface{
    +getCourseEditionEnrollmentList(): Set<CourseEditionEnrollment>
}

class CourseEditionEnrollmentListFactory {
    +getCourseEditionEnrollmentList(): Set<CourseEditionEnrollment>
}

class CourseEditionListFactory {
    +newArrayList(): List<CourseEdition>
}

interface CourseEditionListFactoryInterface{
    +newArrayList(): List<CourseEdition>
}

class CourseEditionArrayList{
    +add(courseEdition: CourseEdition): boolean
}

interface CourseEditionEnrollmentFactoryInterface{
    +createCourseEditionEnrollment(student: Student, courseEdition: CourseEdition)
}

class CourseEditionEnrollmentRepository {
    +CourseEditionEnrollmentRepository (courseEditionEnrollmentFactory: CourseEditionEnrollmentFactory, courseEditionEnrollmentListFactory: CourseEditionEnrollmentListFactory)
    +enrollStudentInACourseEdition (student: Student, courseEdition: CourseEdition): boolean
}

class ProgrammeEditionEnrollment {
    -_enrollmentDate: LocalDate
    +ProgrammeEditionEnrollment(student:Student, programmeEdition: ProgrammeEdition)
    +findStudentInProgrammeEditionEnrollment () : Student
}

class ProgrammeEditionListFactory {
    +getProgrammeEditionEnrollmentList(): Set<ProgrammeEditionEnrollment>
}

interface ProgrammeEditionListFactoryInterface {
    +getProgrammeEditionEnrollmentList(): Set<ProgrammeEditionEnrollment>
}

class ProgrammeEditionArrayList {
    +add(programmeEdition: ProgrammeEdition): boolean
}

class CourseEditionEnrollmentHashSet {
    +add(courseEditionEnrollment: CourseEditionEnrollment): boolean
}

class ProgrammeEditionEnrollmentRepo {
    +ProgrammeEditionEnrollmentRepo(programmeEditionEnrollmentFactory: ProgrammeEditionEnrollmentFactory)
    +getProgrammeEditionsThatStudentIsEnrolled(student: Student): List<ProgrammeEdition>
}

class Student {
    -_uniqueNumber:String
    -_name:String
    -_NIF:String
    -_phone:String
    -_email:String
    +Student(uniqueNumber: String, name: String, NIF: String, phone: String, email: String, address: Address)
}

class Address {
     -_street:String
     -_postalCode: String
     -_location: String
     -_country: String
     +Address(street: String, postalCode: String, location: String, country: String)
}

class CourseEdition {
    +CourseEdition(programmeEdition: ProgrammeEdition, course: Course)
    +whatProgrammeEditionBelongsThisCourseEdition () : ProgrammeEdition
}

class ProgrammeEdition {
    +ProgrammeEdition(programme: Programme, schoolYear: SchoolYear)
}

class CourseEditionRepository {
    +CourseEditionRepository(courseEditionFactory: CourseEditionFactory)
    +findCourseEditionsByProgrammeEdition(programmeEdition: ProgrammeEdition) : List<ProgrammeEdition>
}

CourseEdition "_courseEditions *             " <.. "           1 " CourseEditionRepository
Student "_student  1                " <-- " *" CourseEditionEnrollment
CourseEditionEnrollment "    *  " --> " 1 _courseEdition   " CourseEdition
CourseEditionEnrollmentFactory "1  " ..> "_courseEditionEnrollment   1    "CourseEditionEnrollment
CourseEditionEnrollmentFactory "           _courseEditionEnrollmentFactory 1           " <-u- "  1" CourseEditionEnrollmentRepository
ProgrammeEditionEnrollment "      *     " --> "_student 1   " Student
ProgrammeEditionEnrollment "          * _programmeEditionEnrollment          " <.. "1 " ProgrammeEditionEnrollmentRepo
US16_EnrollAStudentInACourseEditionController "1 "..> "    1                  " CourseEditionRepository
US16_EnrollAStudentInACourseEditionController " 1 "..> "1   " ProgrammeEditionEnrollmentRepo
US16_EnrollAStudentInACourseEditionController "1 "..> "  1  " CourseEditionEnrollmentRepository
Address "_address  1             " <-u- "  1" Student
CourseEditionEnrollmentListFactory " 1 " <.u. "  1        " CourseEditionEnrollmentRepository
CourseEditionEnrollmentHashSet "    1" -u->  "_listOfCEE *             " CourseEditionEnrollment
CourseEditionEnrollmentListFactory"1 " ..> "_courseEditionEnrollmentHashSet  1    "CourseEditionEnrollmentHashSet
CourseEditionEnrollmentRepository " 1  " -u-> "     1\n _hashSet " CourseEditionEnrollmentHashSet
CourseEditionEnrollmentRepository"   1  " ..> "    _ceeEnrollment *       "CourseEditionEnrollment
CourseEditionEnrollmentFactoryInterface <|.. CourseEditionEnrollmentFactory
CourseEditionEnrollmentListFactoryInterface <|.. CourseEditionEnrollmentListFactory
CourseEditionListFactoryInterface <|.. CourseEditionListFactory
ProgrammeEditionListFactoryInterface <|.. ProgrammeEditionListFactory
CourseEditionRepository"     1    " ..> "_courseEditionListFactory 1  "CourseEditionListFactory
CourseEditionRepository"1    " -u-> "   1 _arrayList                      " CourseEditionArrayList
CourseEditionListFactory" 1        " ..> " 1       "  CourseEditionArrayList
ProgrammeEditionEnrollmentRepo"  1" .u.> "  _programmeEditionListFactory 1      "ProgrammeEditionListFactory
ProgrammeEditionEnrollmentRepo"1" -u-> "  1\n_PEArrayList           "ProgrammeEditionArrayList
ProgrammeEditionListFactory"1" ..> "               _PEArrayList 1    "ProgrammeEditionArrayList
CourseEdition "_listOfCourseEdition *  " <-u- "1"CourseEditionArrayList
ProgrammeEdition"_listOfProgrammeEdition\n                              *" <-u- "  1    "ProgrammeEditionArrayList
ProgrammeEditionEnrollmentRepo "1"..> "_programmeEdition *         "ProgrammeEdition

@enduml