@startuml
title US16: Enroll a student in a course edition

actor ASC
participant ":UI" as UI
ASC -> UI: I want to enroll a student in a course edition!
activate UI
UI --> ASC: What Student?
deactivate UI

ASC -> UI: Enter the student!
activate UI
participant ":US16_EnrollAStudentInACourseEditionController" as Controller
UI -> Controller: findProgrammeEditionsThatStudentIsEnrolled (student)
activate Controller
participant ":ProgrammeEditionEnrollmentRepository" as ProgrammeEditionEnrollmentRepository
Controller -> ProgrammeEditionEnrollmentRepository: findProgrammeEditionsThatStudentIsEnrolled (student)
activate ProgrammeEditionEnrollmentRepository
create ":ProgrammeEditionList"
ProgrammeEditionEnrollmentRepository -> ":ProgrammeEditionList": newArrayList()
activate ":ProgrammeEditionList"
":ProgrammeEditionList" --> ProgrammeEditionEnrollmentRepository: EmptyList<ProgrammeEdition>
deactivate ":ProgrammeEditionList"
loop for each "pee[i]:ProgrammeEditionEnrollment" in ProgrammeEditionEnrollmentRepo
participant ":ProgrammeEditionEnrollment" as ProgrammeEditionEnrollment
ProgrammeEditionEnrollmentRepository -> ProgrammeEditionEnrollment : findStudentInProgrammeEdition (student)
activate ProgrammeEditionEnrollment
ProgrammeEditionEnrollment --> ProgrammeEditionEnrollmentRepository : pee1
deactivate ProgrammeEditionEnrollment
ProgrammeEditionEnrollmentRepository -> ProgrammeEditionEnrollment :  findProgrammeEditionInEnrollment()
activate ProgrammeEditionEnrollment
ProgrammeEditionEnrollment --> ProgrammeEditionEnrollmentRepository : pe1
deactivate ProgrammeEditionEnrollment
ProgrammeEditionEnrollmentRepository -> ":ProgrammeEditionList":  add (pe1)
activate ":ProgrammeEditionList"
":ProgrammeEditionList" --> ProgrammeEditionEnrollmentRepository: True
deactivate ":ProgrammeEditionList"
end
ProgrammeEditionEnrollmentRepository --> Controller: List<ProgrammeEdition>
deactivate ProgrammeEditionEnrollmentRepository
Controller --> UI: Optional<List<ProgrammeEdition>>
deactivate Controller
UI --> ASC: Here is a list of programme editions the student is enrolled in. What Programme Edition?
deactivate UI

ASC -> UI: Enter the programme edition!
activate UI
UI -> Controller: findCourseEditionsByProgrammeEdition (programmeEdition)
activate Controller
participant ":CourseEditionRepository" as CourseEditionRepository
Controller -> CourseEditionRepository: findCourseEditionsByProgrammeEdition (programmeEdition)
activate CourseEditionRepository
create ":CourseEditionList"
CourseEditionRepository -> ":CourseEditionList": newArrayList ()
activate ":CourseEditionList"
":CourseEditionList" --> CourseEditionRepository: EmptyList<CourseEdition>
deactivate ":CourseEditionList"
loop for each "ce[i]:CourseEdition" in CourseEditionRepository
participant ":CourseEdition" as CourseEdition
CourseEditionRepository -> CourseEdition :  whatProgrammeEditionBelongsThisCourseEdition()
activate CourseEdition
CourseEdition --> CourseEditionRepository : ce1
deactivate CourseEdition
CourseEditionRepository -> ":CourseEditionList" :  add (ce1)
activate ":CourseEditionList"
":CourseEditionList" --> CourseEditionRepository: True
deactivate ":CourseEditionList"
end
CourseEditionRepository --> Controller: List<CourseEdition>
deactivate CourseEditionRepository
Controller --> UI: List<CourseEdition>
deactivate Controller
UI --> ASC: Here is a list of Course Editions! What Course Edition?
deactivate UI

ASC -> UI: Enter the course edition!
activate UI
UI --> ASC: Sure?
deactivate UI
ASC -> UI: Yes!
activate UI

UI -> Controller: enrollStudentInACourseEdition (student, courseEdition)
activate Controller

participant ":CourseEditionEnrollmentRepository" as CourseEditionEnrollmentRepository
Controller -> CourseEditionEnrollmentRepository: enrollStudentInACourseEdition (student, courseEdition)
activate CourseEditionEnrollmentRepository
participant ":ICourseEditionEnrollmentFactory" as CourseEditionEnrollmentFactoryInterface
CourseEditionEnrollmentRepository -> CourseEditionEnrollmentFactoryInterface: createCourseEditionEnrollment (student, courseEdition)
activate CourseEditionEnrollmentFactoryInterface
create "cee1:CourseEditionEnrollment"
CourseEditionEnrollmentFactoryInterface -> "cee1:CourseEditionEnrollment" : createCourseEditionEnrollment (student, courseEdition)
activate "cee1:CourseEditionEnrollment"
"cee1:CourseEditionEnrollment" --> CourseEditionEnrollmentFactoryInterface: cee1
deactivate "cee1:CourseEditionEnrollment"
CourseEditionEnrollmentFactoryInterface --> CourseEditionEnrollmentRepository: cee1
deactivate CourseEditionEnrollmentFactoryInterface
participant ":CourseEditionEnrollmentSet" as CourseEditionEnrollmentSet
CourseEditionEnrollmentRepository --> CourseEditionEnrollmentSet: add (cee1)
activate CourseEditionEnrollmentSet
CourseEditionEnrollmentSet -> CourseEditionEnrollmentRepository: True
deactivate CourseEditionEnrollmentSet
CourseEditionEnrollmentRepository --> Controller: True
deactivate CourseEditionEnrollmentRepository
Controller --> UI: True
deactivate Controller
UI --> ASC: OK!
deactivate UI

@enduml
