@startuml
title US30: As an ASC, I want to add a course to a programme using a Web UI\n (Process View - Level 2: Containers)
autonumber

skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam sequence {
    LifeLineBorderColor Grey
    LifeLineBackgroundColor #E1F5FE
}
skinparam defaultTextAlignment center
skinparam shadowing true

actor ASC  #honeydew
participant "<<Container>>\n:Frontend" as Frontend #honeydew
participant "<<Container>>\n:Backend" as Backend #honeydew
database "<<Container>>\n:Database" as Database #honeydew

group Retrieve Programmes
ASC -> Frontend: I want to add a Course to a Programme!\nAccess form
activate Frontend

Frontend -> Backend: **GET** /programmes
activate Backend
Backend -> Database: **SELECT** * FROM programmes
activate Database
Database --> Backend: 200 OK + programmes
deactivate Database
Backend --> Frontend: 200 OK + programmes
deactivate Backend
Frontend --> ASC: Display dropdown with programme options
deactivate Frontend
end

group Retrieve Courses
ASC -> Frontend: Select Programme
activate Frontend
Frontend -> Backend: **GET** /courses/{ids}
activate Backend
Backend -> Database: **SELECT** * FROM courses
activate Database
Database --> Backend: 200 OK + courses
deactivate Database
Backend --> Frontend: 200 OK + courses
deactivate Backend
Frontend --> ASC: Display dropdown with course options
deactivate Frontend
end

group Collect Course Details
ASC -> Frontend: Select Course
activate Frontend
Frontend --> ASC: Which Curricular Year?
deactivate Frontend

ASC --> Frontend: Select Curricular Year
activate Frontend
Frontend --> ASC: Which Semester?
deactivate Frontend

ASC -> Frontend: Select Semester
activate Frontend
Frontend --> ASC: Duration of Course in Semester?
deactivate Frontend

ASC --> Frontend: Select Duration
activate Frontend
Frontend --> ASC: Quantity of Credits?
deactivate Frontend

ASC -> Frontend: Select ECTS credits
activate Frontend
end

group Confirm and Submit
Frontend --> ASC: Confirm adding a course to a programme?
deactivate Frontend
ASC -> Frontend: Yes, confirm
activate Frontend
Frontend -> Backend: **POST** /courses-in-study-plan + body
note over Frontend, Backend
Request body (JSON):
{
  semester: "...",
  curricularYear: "...",
  courseAcronym: "...",
  courseName: "...",
  programmeAcronym: "...",
  programmeName: "..."
  studyPlanDate: "..."
  duration: "..."
  credits: "..."
}
end note
activate Backend
Backend -> Database: **INSERT INTO** courses_in_study_plan (data)
activate Database
Database --> Backend: Confirmation + new courseInStudyPlan
deactivate Database
Backend --> Frontend: 201 Created + body
note over Backend, Frontend
Response body (JSON) + hypermedia:
{
  generatedID: "...",
  semester: "...",
  curricularYear: "...",
  ...
    _links: {
      self: {
        href: "/course-in-study-plan"
      }
    }
}
end note
deactivate Backend
Frontend --> ASC: Course added to a programme successfully!
deactivate Frontend
end
@enduml
