@startuml
autonumber

skinparam {
    SequenceLifeLineBorderColor gray
    SequenceParticipantBorderColor rosyBrown
    DefaultTextAlignment center
}

participant "syRestCtrl" as C #rosyBrown
participant "syMapper" as SYM #rosyBrown
participant "syDTO" as SYDTO #rosyBrown

activate C #seashell
C -> SYM: fromDomainToDTO(SchoolYear)
activate SYM #seashell
SYM -> SYDTO**: new SchoolYearDTO (startDate, endDate,\n description)
activate SYDTO #seashell
SYDTO --> SYM: schoolYearDTO
deactivate SYDTO #seashell
SYM --> C: schoolYearDTO
deactivate SYM #seashell

@enduml