@startuml

left to right direction

title  As an ASC, I want to remove the enrolment of a student in a course edition using a Web UI.

actor ASC as "**A**cademic **S**ervices **C**ollaborator"

rectangle "<<PAI System>>" {
    usecase "Remove the enrolment of a student in a Course Edition" as usecase
}

ASC --> usecase

@enduml