@startuml
title As an ASC I want to remove the enrolment of a student in a course edition using a WEB UI\n(Process View Level 3 - Backend - Combined Flow)

skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue

participant ":Router" as Router <<Component>> #lightpink
participant ":StudentRestController" as Controller <<Component>> #motivation
participant ":CourseEditionEnrolmentService" as Service <<Component>> #business
participant ":CourseEditionEnrolmentRepository" as CEER <<Component>> #lightgreen
participant ":Drivers" as Drivers <<Component>> #technology


[o-> Router : **GET** \nstudents/{studentId}/enrolled-course-editions/
activate Router
Router -> Controller : findEnrolledCourseEditionsForStudent \n (studentUniqueNumber)
activate Controller
Controller -> Service : findEnrolledCourseEditionsForStudent(studentID)
activate Service
ref over Service
          Find active enrolments by StudentID
end ref
deactivate CEER
Service --> Controller : List<EnrolledCourseDetails>
deactivate Service
Controller --> Router : List<EnrolledCourseEditionDTO>
deactivate Controller
[o<-- Router : (**200 OK**) \n List<EnrolledCourseEditionDTO>
deactivate Router

[o-> Router : **PATCH** \nstudents/{studentId}/course-editions/{courseEditionGeneratedUUID}
activate Router
Router -> Controller : removeStudentEnrolmentFromACourseEdition \n (studentUniqueNumber, courseEditionGeneratedUUID)
activate Controller
Controller -> Service : removeCourseEditionEnrolment(studentID, courseEditionID)
activate Service
Service -> CEER : findCourseEditionByGeneratedID(courseEditionGeneratedUUID)
activate CEER
CEER -> Drivers ++: findCourseEditionByGeneratedId(courseEditionGeneratedIDDataModel)
Drivers ->o] : **SELECT** CourseEditionGeneratedIDDataModel
Drivers <--o] : courseEditionDataModel
Drivers --> CEER -- : courseEditionDataModel
CEER --> Service -- : courseEdition
deactivate CEER
Service --> Controller -- : courseEditionID

Controller -> Service ++: removeCourseEditionEnrolment(studentID, courseEditionID)
Service -> CEER ++: findByStudentAndEdition(studentID, courseEditionID)
CEER -> Drivers ++: findById_StudentIDAndId_CourseEditionID(studentIDDataModel, courseEditionIDDataModel)
Drivers ->o] : **SELECT** findById_StudentIDAndId_CourseEditionID
Drivers <--o] : courseEditionEnrolmentDataModel
Drivers --> CEER -- : courseEditionEnrolmentDataModel
CEER --> Service -- : courseEditionEnrolment
deactivate CEER
Service --> Controller -- : true
deactivate Service
Controller --> Router : (ACCEPTED, 202) \n + body {"Successfully removed the enrolment from course edition."}
[o<-- Router : (**202 ACCEPTED**) \n + body {"Successfully removed the enrolment from course edition."}
deactivate Controller
deactivate Router

@enduml