@startuml
actor ASC as Admin
participant ":System" as System

Admin -> System  : I Want to register a Programme in the System, including a Study Plan.
System --> Admin  : Name? Acronym? quantityOfEcts? quantityOfSemesters?  DegreeType? Department? Programme Director?
Admin -> System  : Name! Acronym! quantityOfEcts! quantityOfSemesters!  DegreeType! Department! Programme Director!
System --> Admin  : Sure?
Admin -> System  : Yes!
System --> Admin  : Done!


Admin -> System : I want to add a Course to StudyPlan.
System --> Admin   : Programme? Course? curricularYear? semester?
Admin -> System : Programme! Course! curricularYear! semester!
System --> Admin  : Sure?
Admin -> System  : Yes!
System --> Admin  : Ok
@enduml