@startuml

skinparam ranksep 100
skinparam nodesep 100

package "Student Aggregate" as S {
entity "<<root>>\nStudent" {
equals(studentIDVO: StudentID)
}
}

class "<<VO>>\nStudentID" {
-uniqueNumber: Integer
-NIF: Integer
}

package "AccessMethod Aggregate" as AM {
class "<<root>>\nAccessMethod" {
+equals(amIDVO: AccessMethodID)
}
}

class "<<VO>>\nAccessMethodID" {
-amIDVO: UUID
}

package "Programme Aggregate" as P {
entity "<<root>>\nProgramme" {
equals(ProgrammeIDVO: ProgrammeID)
}
}

class "<<VO>>\nProgrammeID" {
-nameVO: NameWithNumbersAndSpecialCharacters
-acronymVO: Acronym
}

package "ProgrammeEnrolment Aggregate" as PE {
entity "<<root>>\nProgrammeEnrolment" {
-enrolmentDate: Date
+ProgrammeEnrolment(studentIDVO: StudentID, amIDVO: AccessMethodID, programmeIDVO: ProgrammeID, dateVO: Date)
+getProgrammeEnrolmentID(programmeEnrolment: ProgrammeEnrolment)
+getStudentID(studentIDVO: StudentID)
+getProgrammeID(programmeIDVO: ProgrammeID)
+getAccessMethodID(programmeIDVO: ProgrammeID)
}
}

class US09_EnrolStudentInProgrammeController {
+US09_EnrolStudentInProgrammeController(programmeEnrolmentService: ProgrammeEnrolmentService)
}

class ProgrammeEnrolmentService {
+ProgrammeEnrolmentService(studentRepository: IStudentRepository, accessMethodRepository: IAccessMethodRepository, programmeList: IProgrammeRepository, programmeEnrolmentRepository: IProgrammeEnrolmentRepository)
+getStudentIDFromUniqueNumber(uniqueNumber: Int)
+getAccessMethodIDFromName(accessMethodName: String)
+getProgrammeIDFromName(programmeName: String)
+enrolStudent(studentIDVO: StudentID, amIDVO: NameVO, programmeIDVO: ProgrammeID, date: Date)
}

interface IStudentRepository {
+getStudentIDFromUniqueNumber(uniqueNumber: String)
}

class StudentRepository {
+getStudentIDFromUniqueNumber(uniqueNumber: String)
}

interface IAccessMethodRepository {
+getAccessMethodIDFromName(nameVO: NameWithNumbersAndSpecialCharacters)
}

class AccessMethodRepository {
+getAccessMethodIDFromName(nameVO: NameWithNumbersAndSpecialCharacters)
}

interface IProgrammeRepository {
+getProgrammeIDFromAcronym(acronymVO: Acronym)
}

class ProgrammeRepository {
getProgrammeIDFromAcronym(acronymVO: Acronym)
}

class ProgrammeEnrolmentSpringDataRepository {
-programmeEnrolmentFactory: ProgrammeEnrolmentFactory
-programmeEnrolmentList: ProgrammeEnrolmentListFactory
+ProgrammeEnrolmentSpringDataRepository(programmeEnrolmentFactory: ProgrammeEnrolmentFactoryImpl, programmeEnrolmentRepositoryListFactory ProgrammeEnrolmentRepositoryList)
+enrolStudents(studentIDVO: StudentID, amIDVO: AccessMethodID, programmeIDVO: ProgrammeID, enrolmentDate: Date)
}

interface IProgrammeEnrolmentRepository {
+ save(pe: ProgrammeEnrolment);
}

class ProgrammeEnrolmentFactoryImpl {
+createProgrammeEnrolment(student: Student, accessMethod: AccessMethod, programme: Programme, date: String)
}

interface IProgrammeEnrolmentFactory {
+createProgrammeEnrolment(student: Student, accessMethod: AccessMethod, programme: Programme, date: String)
}

class ProgrammeEnrolmentMapper {
+toDomain(peDataModel: ProgrammeEnrolmentDataModel, peFactory: ProgrammeEnrolmentFactory)
+toDataModel(pe: ProgrammeEnrolment)
}

class ProgrammeEnrolmentDataModel {
+ProgrammeEnrolmentDataModel(pe: ProgrammeEnrolment)
+createProgrammeEnrolmentDomain(peDataModel: ProgrammeEnrolmentDataModel)
}

interface IStudentSpringDataRepository {
+findByStudentIdUniqueNumber(uniqueNumber: String);
}

interface IAccessMethodSpringDataRepository {
+findByAccessMethodIDUuid(uuid: UUID)
}

interface IProgrammeSpringDataRepository {
+findByProgrammeIDAcronym(acronym: String)
}

interface IProgrammeEnrolmentSpringDataRepository {
+save(peDataModel: ProgrammeEnrolmentDataModel)
}

interface IProgrammeEnrolmentMapper {
+toDataModel(pe: ProgrammeEnrolment)
+toDomain(peDataModel: ProgrammeEnrolmentDataModel)
}

interface IProgrammeEnrolmentService {
+getStudentIDFromUniqueNumber(uniqueNumber: Int)
+getAccessMethodIDFromName(accessMethodName: String)
+getProgrammeIDFromName(programmeName: String)
+enrolStudent(studentIDVO: StudentID, amIDVO: NameVO, programmeIDVO: ProgrammeID, date: Date)
}

interface IProgrammeEnrolmentIDMapper {
+toDataModel(peIDDomain: ProgrammeEnrolmentIDDataModel)
}

interface IStudentIDMapper {
+toDataModel(studentIDDomain: StudentIDDataModel)
}

interface IProgrammeIDMapper {
+toDataModel(programmeIDDomain: ProgrammeIDDataModel)
}

interface IAccessMethodIDMapper {
+toDataModel(amIDDomain: AccessMethodIDDataModel)
}

class ProgrammeEnrolmentIDMapper {
+toDataModel(peIDDomain: ProgrammeEnrolmentIDDataModel)
}

class StudentIDMapper {
+toDataModel(studentIDDomain: StudentIDDataModel)
}

class ProgrammeIDMapper {
+toDataModel(programmeIDDomain: ProgrammeIDDataModel)
}

class AccessMethodIDMapper {
+toDataModel(amIDDomain: AccessMethodIDDataModel)
}

US09_EnrolStudentInProgrammeController "1" -l> "1..*" IProgrammeEnrolmentService
ProgrammeEnrolmentService -u.|> IProgrammeEnrolmentService

ProgrammeEnrolmentService "1" -r-> "1..*" IStudentRepository
StudentRepository -.|> IStudentRepository
StudentRepository -l.> IStudentSpringDataRepository

ProgrammeEnrolmentService "1" --> "1..*" IAccessMethodRepository
AccessMethodRepository -u.|> IAccessMethodRepository
AccessMethodRepository -d.> IAccessMethodSpringDataRepository
ProgrammeRepository -d> ProgrammeEnrolmentMapper
ProgrammeEnrolmentService "1" -l-> "1..*" IProgrammeRepository
ProgrammeRepository -u.|> IProgrammeRepository
ProgrammeRepository -u.> IProgrammeSpringDataRepository

ProgrammeEnrolmentService "1" -l-> "1..*" IProgrammeEnrolmentRepository
IProgrammeEnrolmentRepository <|.r. ProgrammeEnrolmentSpringDataRepository
ProgrammeEnrolmentSpringDataRepository -u.> IProgrammeEnrolmentSpringDataRepository


"<<root>>\nStudent" "1" --> "1" "<<VO>>\nStudentID"
"<<root>>\nAccessMethod" "1" --> "1" "<<VO>>\nAccessMethodID"
"<<root>>\nProgramme" "1" --> "1" "<<VO>>\nProgrammeID"

IStudentRepository "1" -d.> "*" "<<root>>\nStudent"
IAccessMethodRepository "1" -.> "*" "<<root>>\nAccessMethod"
IProgrammeRepository "1" -r.> "*" "<<root>>\nProgramme"
IProgrammeEnrolmentFactory "1..*" .l.> "*\ncreates" "<<root>>\nProgrammeEnrolment"
ProgrammeEnrolmentSpringDataRepository "1" -.> "1" IProgrammeEnrolmentFactory
IProgrammeEnrolmentFactory <|.. ProgrammeEnrolmentFactoryImpl


"<<root>>\nProgrammeEnrolment" "1..*" -u-> "1" "<<VO>>\nStudentID"
"<<root>>\nProgrammeEnrolment" "1..*" -u-> "1" "<<VO>>\nProgrammeID"
"<<root>>\nProgrammeEnrolment" "1..*" -u-> "1" "<<VO>>\nAccessMethodID"

ProgrammeEnrolmentSpringDataRepository "1" -d.> "1" IProgrammeEnrolmentMapper
ProgrammeEnrolmentMapper -.|> IProgrammeEnrolmentMapper
IProgrammeEnrolmentMapper "1" -d.> "1" ProgrammeEnrolmentDataModel
IProgrammeEnrolmentMapper "*" -r.> "1" IProgrammeEnrolmentFactory

ProgrammeEnrolmentMapper "1..*" -d-> "1" IProgrammeEnrolmentIDMapper
ProgrammeEnrolmentMapper "1..*" -d-> "1" IStudentIDMapper
ProgrammeEnrolmentMapper "1..*" -d-> "1" IProgrammeIDMapper
ProgrammeEnrolmentMapper "1..*" -d-> "1" IAccessMethodIDMapper

ProgrammeEnrolmentIDMapper -u.|> IProgrammeEnrolmentIDMapper
StudentIDMapper -u.|> IStudentIDMapper
ProgrammeIDMapper -u.|> IProgrammeIDMapper
AccessMethodIDMapper -u.|> IAccessMethodIDMapper

ProgrammeEnrolmentIDMapper "1" --> "peID\n1..*" "<<root>>\nProgrammeEnrolment"
StudentIDMapper "1" --> "studentID\n1..*" "<<root>>\nProgrammeEnrolment"
ProgrammeIDMapper "1" --> "programmeID\n1..*" "<<root>>\nProgrammeEnrolment"
AccessMethodIDMapper "1" --> "amID\n1..*" "<<root>>\nProgrammeEnrolment"

@enduml
