@startuml
actor ASC
participant ":ProgrammeList" as PL #lightgreen
participant ":Programme" as PG #yellow

ASC -> PL : I want to change Programme Director (Programme, Teacher)
activate PL
PL -> PG : Change Programme Director (Programme, Teacher)
PG -> PG : validate()
PG --> PL : Changed Programme Director
deactivate PG
PL --> ASC : Change Successful
@enduml
