@startuml
'https://plantuml.com/sequence-diagram

autonumber

Admin -> System: Create a School Year
System --> Alice: Authentication Response

Admin -> System: Another authentication Request
System <-- Admin: another authentication Response



@enduml