@startuml
skinparam sequenceMessageAlign center

actor Admin
participant ":SchoolYearRepository" as SYR

Admin -> SYR: insertSchoolYear(description, \nstartDate, endDate)
activate SYR
create "sy1:SchoolYear" as SchoolYear
SYR -> SchoolYear: createSchoolYear(description, startDate, endDate)
activate SchoolYear
SchoolYear -> SchoolYear: validation()
SchoolYear --> SYR: SchoolYear Instance
deactivate SchoolYear
|||
ref over SYR, SchoolYear
    Check if SchoolYear is already inserted
end ref
|||
SYR -> SYR: addSchoolYear(sy1:SchoolYear)
SYR --> Admin: SchoolYear created
deactivate SYR
@enduml