@startuml
skinparam sequenceMessageAlign center

actor Admin
participant ":SYR" as SchoolYearRepository
participant ":SchoolYear" as SchoolYear

Admin -> SchoolYearRepository: insertSchoolYear(description, \nstartDate, endDate)
activate SchoolYearRepository
SchoolYearRepository -> SchoolYear: createSchoolYear(description, \nstartDate, endDate)
activate SchoolYear
SchoolYear -> SchoolYear: validation()
SchoolYear --> SchoolYearRepository: SchoolYear Instance
deactivate SchoolYear
|||
ref over SchoolYearRepository, SchoolYear
    Check if SchoolYear is already inserted
end ref
|||
SchoolYearRepository -> SchoolYearRepository: addSchoolYear(SchoolYear)
SchoolYearRepository --> Admin: SchoolYear created
deactivate SchoolYearRepository
@enduml