@startuml
skinparam sequenceMessageAlign center

actor ASC
participant ":StudentRepository" as SR
participant "s1:Student" as Student

ASC -> SR: registerStudent(uniqueNumber, \npersonalInfo, Address)
activate SR
create Student
SR -> Student: createStudent(uniqueNumber, name, NIF, phone, email, Address)
activate Student
Student -> Student: validate()
Student --> SR: Student instance
|||
ref over SR, Student
    Check if a student is already registered
end ref

deactivate Student
|||
SR -> SR: addStudent(s1:Student)
SR --> ASC: Registration Successful
@enduml