@startuml

title US04: Register a Teacher in the System

participant "Test" as Test #Orange/White
participant ":TeacherRepository" as TeacherRepository #DeepPink/White
participant "t1:Teacher" as Teacher #Violet/White
participant "t[i]:Teacher" as Teacheri #Cyan/White



Test -> TeacherRepository: registerTeacher(acronym, name, email, nif, phoneNumber, address, category, department)
activate TeacherRepository

TeacherRepository -> Teacher **: createTeacher (acronym, name, email, nif, phoneNumber, address, category, department)
activate Teacher
Teacher --> TeacherRepository: Teacher created

deactivate Teacher


loop for each Teacher t[i] in TeacherRepository
TeacherRepository -> Teacheri: compareTeacherAcronymAndNifInList (t1:Teacher)
activate Teacheri
Teacheri --> TeacherRepository: Acronym and NIF are not in the list
deactivate Teacheri

end



TeacherRepository -> TeacherRepository: add (t1:Teacher)

TeacherRepository --> Test: Teacher registered
deactivate TeacherRepository

@enduml
