@startuml
actor ASC
participant ":ProgrammeList" as PL #lightgreen

ASC -> PL : I want to change Programme Director (Programme, Teacher)
activate PL
create ":Programme" as PG #yellow
PL -> PG : Change Programme Director (Programme, Teacher)
activate PG
PG -> PG : validate()
PG --> PL : Changed Programme Director
deactivate PG
PL --> ASC : Change Successful
deactivate PL
@enduml
