@startuml

autonumber

title Query database for enrolments matching courseEditionID

participant "sgRepo:StudentGradeRepositorySpringData" as R #lightblue
participant "JPA: Spring Data / EntityManager" as JPA #lightblue
database "Database" as DB #lightblue

R -> JPA ++ #lightblue: hasThisCourseEditionID(courseEditionID)
JPA -> DB ++ #lightblue: SELECT * FROM student_grade \nWHERE course_edition_id = :courseEditionID
DB --> JPA --: ResultSet with matching enrolments
JPA --> R --: List<StudentGrade>

@enduml