@startuml

autonumber

participant "<<Component>>\n:Router" as RT #lightpink
participant "<<Component>>\n:TeacherRestController" as C #lightgreen
participant "<<Component>>\n:TeacherRegistrationService" as S #lightblue
participant "<<Component>>\n:TeacherRepository" as R #lightyellow
participant "<<Component>>\n:Drivers" as Drivers #strategy

-> RT ++: **GET** /teachers
RT -> C ++: getAllTeachers()
C -> S ++: getAllTeachers()
S -> R ++: findAll()
R -> Drivers ++: findAll()
Drivers -> : **SELECT** findAll()
Drivers <-- : List<Teachers>
Drivers --> R --: List<Teachers>
R --> S --: List<Teachers>
S --> C --: List<Teachers>
C --> RT --: List<Teachers>
<-- RT --: (OK, 200) List<Teachers>

@enduml