@startuml

autonumber

title As an ASC I want to register a Programme \n (Process View Level 2)

actor ASC as Admin
participant "<<Container>> \n:Frontend" as FE #lightblue
participant "<<Container>> \n:Backend" as BE #lightgreen
participant "<<Container>> \n:Database" as BD #lightyellow

activate Admin
Admin -> FE ++: I want to register a Programme \nin the System
FE -> BE ++: **GET** /degreetypes
BE -> BD ++: **SELECT** retrieveAllDegreeTypes()
BD --> BE --: List<DegreeTypes>
BE --> FE --: (OK, 200) List<DegreeTypes>

FE -> BE ++: **GET** /departments
BE -> BD ++: **SELECT** retrieveAllDepartments()
BD --> BE --: List<Departments>
BE --> FE --: (OK, 200) List<Departments>


FE -> BE ++: **GET** /teachers
BE -> BD ++: **SELECT** retrieveAllTeachers()
BD --> BE --: List<Teachers>
BE --> FE --: (OK, 200) List<Teachers>
FE --> Admin --: Display form with: \n Degree types, Departments, Teachers (dropdown) \n and Name, Acronym (inputs)

Admin -> FE ++: Submit filled form \n(Degree Type, Department, Teacher, Name, Acronym)
FE -> BE ++: **POST** /programmes (programmeDTO)
BE -> BD ++: **SELECT EXISTS** isDepartmentRegistered (id)
BD --> BE --: True
BE -> BD ++: **SELECT EXISTS** isTeacherRegistered (id)
BD --> BE --: True
BE -> BD ++: **SELECT** getDegreeTypeById (id)
BD --> BE --: degreeType
BE -> BD ++: **SELECT EXISTS** isProgrammeRegistered (acronym)
BD --> BE --: False
BE -> BD ++: **INSERT** save (programmeDataModel)
BD --> BE --: programme
BE --> FE --: (201, Created) + body {programmeIDDTO + hypermedia}
FE --> Admin --: Programme registered successfully! \n(Display Programme details)

@enduml