@startuml

autonumber

participant "<<Component>>\n:Router" as RT #lightpink
participant "<<Component>>\n:ProgrammeRestController" as C #lightgreen
participant "<<Component>>\n:ProgrammeService" as PS #lightblue
participant "<<Component>>\n:DegreeTypeService" as DTS #lightblue
participant "<<Component>>\n:ProgrammeRepository" as PR #lightyellow
participant "<<Component>>\n:DegreeTypeRepository" as DTR #lightyellow
participant "<<Component>>\n:Domain" as D #lightpink
participant "Programme1:Programme" as P
participant "<<Component>>\n:Drivers" as Drivers #lightyellow

[o-> RT ++: **POST** /programmes

RT -> C ++: registerProgramme (ProgrammeDTO)
C -> PS ++: registerProgramme (ProgrammeVOsDTO)

PS -> D ++: registerProgramme (name, acronym, maxECTS, \nquantSemesters, degreeType, department, programmeDirector)
D -> P** : newProgramme (name, acronym, maxECTS, \nquantSemesters, degreeType, department, programmeDirector)
activate P
P --> D: Programme1
deactivate P
D --> PS --: Programme1

PS -> DTS ++: getDegreeTypeByID(degreeTypeID)
DTS -> DTR ++: ofIdentity(degreeTypeID)
DTR -> Drivers ++: ofIdentity(degreeTypeID)
Drivers ->o] : ofIdentity(degreeTypeID)
Drivers <--o] : degreeType
DTR <-- Drivers --: degreeType
DTS <-- DTR --: degreeType
PS <-- DTS --: degreeType

PS -> PS : areQtyOfSemesterAndDegreeTypeAligned(quantityOfSemesters, degreeType)

PS -> PR ++: isNameAlreadyRegistered (name)
PR -> Drivers ++: existsByName (name)
Drivers ->o] : existsByName (name)
Drivers <--o] : False
Drivers --> PR --: False
PR --> PS --: False

PS -> PR ++: isAcronymAlreadyRegistered (acronym)
PR -> Drivers ++: existsByAcronym (name)
Drivers ->o] : existsByAcronym (name)
Drivers <--o] : False
Drivers --> PR --: False
PR --> PS --: False

PS -> PR ++: save(Programme1)
PR -> Drivers ++: save(Programme1)
Drivers ->o] : save(Programme1)
Drivers <--o] : Programme1
Drivers --> PR --: Programme1
PR --> PS --: Programme1

PS --> C --: Programme1
C --> RT --: (201, Created) + body {programmeIDDTO + hypermedia}
[o<-- RT --: (201, Created) + body {programmeIDDTO + hypermedia}
@enduml