@startuml

autonumber

title As an ASC I want to register a Programme \n (Process View Level 2)

actor ASC as Admin
participant "<<Container>> \n:Frontend" as FE #lightblue
participant "<<Container>> \n:Backend" as BE #lightgreen
participant "<<Container>> \n:Database" as BD #lightyellow

activate Admin
Admin -> FE ++: I want to register a Programme \nin the System
FE -> BE ++: (GET) Request Degree Types
BE -> BD ++: (SELECT) Retrieve all Degree Types
BD --> BE --: List of Degree Types
BE --> FE --: (OK, 200) List of Degree Types
FE --> Admin --: Choose a Degree Type
Admin -> FE ++: Degree Type

FE -> BE ++: (GET) Request Departments
BE -> BD ++: (SELECT) Retrieve all Departments
BD --> BE --: List of Departments
BE --> FE --: (OK, 200) List of Departments
FE --> Admin --: Choose a Department
Admin -> FE ++: Department

FE -> BE ++: (GET) Request Teachers
BE -> BD ++: (SELECT) Retrieve all Teachers
BD --> BE --: List of Teachers
BE --> FE --: (OK, 200) List of Teachers
FE --> Admin --: Choose a Programme Director
Admin -> FE ++: Programme Director

FE --> Admin --: Name, Acronym, Quantity Semesters?
Admin -> FE ++: name, acronym, quantSemesters
FE -> BE ++: (POST) Request register a Programme \n(name, acronym, maxECTS, quantSemesters, \ndegreeType, department, programmeDirector)
BE -> BD ++: (INSERT) Persist Programme to Database (Programme)
BD --> BE --: Programme
BE --> FE --: (201, Created) Registered Programme
FE --> Admin --: Programme registered successfully!

@enduml