@startuml

autonumber

title As an ASC I want to register a Programme \n (Process View Level 3)



participant "<<Component>>\nController" as C #lightgreen
participant "<<Component>>\nService" as S #lightblue
participant "<<Component>>\nRepository" as R #lightyellow
participant "<<Component>>\nDomain" as D #lightpink
participant "<<Component>>\nDatabase" as BD #lightyellow


 -> C ++: (GET) Request Degree Types
C -> S ++: Get Degree Types
S -> R ++: Get Degree Types
R -> BD ++: Retrieve all Degree Types
BD --> R --: List of Degree Types
R --> S --: List of Degree Types
S --> C --: List of Degree Types
 <-- C --: (OK, 200) List of Degree Types


 -> C ++: (GET) Request Departments
C -> S ++: Get Departments
S -> R ++: Get Departments
R -> BD ++: Retrieve all Departments
BD --> R --: List of Departments
R --> S --: List of Departments
S --> C --: List of Departments
<-- C --: (OK, 200) List of Departments

-> C ++: (GET) Request Teachers
C -> S ++: Get Teachers
S -> R ++: Get Teachers
R -> BD ++: Retrieve all Teachers
BD --> R --: List of Teachers
R --> S --: List of Teachers
S --> C --: List of Teachers
<-- C --: (OK, 200) List of Teachers

-> C ++: (POST) Request register a Programme \n(name, acronym, maxECTS, quantSemesters, \ndegreeType, department, programmeDirector)


C -> S ++: Register Programme \n(name, acronym, maxECTS, quantSemesters, \ndegreeType, department, programmeDirector)

S -> D ++: Create Programme \n(name, acronym, maxECTS, quantSemesters, \ndegreeType, department, programmeDirector)
D --> S --: Programme

S -> R ++: Check if Programme exists (Programme)
R -> BD ++: Check if Programme exists (Programme)
BD --> R --: Programme does not exist
R --> S --: Programme does not exist

S -> R ++: Save Programme (Programme)
R -> BD ++: Save Programme (Programme)
BD --> R --: Registered Programme
R --> S --: Registered Programme

S --> C --: Registered Programme
<-- C --: (201, Created) Registered Programme

@enduml
