@startuml

title Get all Programme Editions\n (Process View - Level 3 Backend)

skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

participant ":Router" as router <<Component>>
participant ":RESTController" as controller <<Component>>
participant ":Service" as service <<Component>>
participant ":Domain" as domain <<Component>>
participant ":Repository" as repository <<Component>>

-> router: GET /programmeEditions + body {}
activate router #E1F5FE

note over router: The conversion from JSON to DTO is done\n automatically through the Spring Boot Framework

router -> controller :getAllProgrammeEditions()
activate controller#E1F5FE

controller -> service : getAllProgrammeEditions()
activate service#E1F5FE

service -> repository: findAllProgrammeEditions()
activate repository #E1F5FE

repository --> service:List<ProgrammeEdition> programmeEditions
deactivate repository

service --> controller : List<ProgrammeEdition> programmeEditions
deactivate service

controller --> router: 200 + body {List<CountStudentsDTO> + hypermedia}
deactivate controller#E1F5FE

note over router: The conversion from DTO to JSON is done\n automatically through the Spring Boot Framework


<-- router: 200 + body {List<CountStudentsDTO> + hypermedia}
deactivate router #E1F5FE

@enduml
