@startuml
'https://plantuml.com/sequence-diagram
title US21: As an ASC, I want to get the number of students enrolled in a programme edition\n(Process View - Level 3 Granularity)

autonumber
skinparam defaultTextAlignment center
skinparam shadowing true
skinparam sequence {
    ActorBorderColor black
    ParticipantBorderColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor #ffffff
}



actor ASC as ASC #orange

participant "Router" as router <<Component>> #fffacd
participant "RESTController" as controller <<Component>> #dcf9ff
participant "Service" as service <<Component>> #d0f0c0
participant "Repository" as repo <<Component>> #f4cccc
database "DB" as db <<Component>> #eeeeee

ASC -> router: Request list of programme editions
activate router
router -> controller: (GET) List of Programme Editions
activate controller
controller -> service: getAllProgrammeEditions()
activate service
service -> repo: fetchAllProgrammeEditions()
activate repo
repo -> db: SELECT * FROM ProgrammeEdition
activate db
db --> repo: List<ProgrammeEditionDataModel>
deactivate db
repo --> service: List<ProgrammeEdition>
deactivate repo
service --> controller: List<ProgrammeEditionDTO>
deactivate service
controller --> router: List<ProgrammeEditionDTO>
deactivate controller
router --> ASC: List<ProgrammeEditionDTO>
deactivate router

ASC -> router: Select ProgrammeEdition!
activate router
router -> controller: getNumberOfStudents(ProgrammeEditionDTO)
activate controller
controller -> service: getNumberOfStudents(ProgrammeEditionDTO)
activate service
service -> repo: countStudentsByProgrammeEditionID(ProgrammeEditionID)
activate repo
repo -> db: SELECT * FROM ProgrammeEditionEnrolment WHERE ProgrammeEditionID = ProgrammeEditionIDDataModel
activate db
db --> repo: List<ProgrammeEditionEnrolment>
deactivate db
repo --> service: programmeEditionsEnrolments.size()
deactivate repo
service --> controller: int
deactivate service
controller --> router: int
deactivate controller
router --> ASC: Display NumberOfStudents()
deactivate router
@enduml

