@startuml

title:US21: As an ASC, I want to get the number of students enrolled in a programme edition\n(Process View - Level 1 Granularity)
autonumber

actor ASC #lightyellow
participant SystemPAI as SystemPAI <<Component>> #lightyellow
ASC -> SystemPAI:  I want to get the number of students enrolled in a programme edition!
SystemPAI --> ASC -- : Which programme edition?
ASC -> SystemPAI: This programme edition!
SystemPAI --> ASC -- : Number of Students!

@enduml