@startuml

title US21: As an ASC, I want to get the number of students enrolled in a programme edition\n(Process View - Level 2 Granularity)

autonumber

actor ASC #lightblue
participant Frontend as ":Frontend\n<<Container>>" #lightblue
participant Backend as ":Backend\n<<Container>>" #lightgreen
database DB as ":Database\n<<Container>>" #lightyellow

ASC -> Frontend: I want to get the number of students in a programme edition!
Frontend -> Backend: GET /programmeeditions
Backend -> DB: SELECT * FROM ProgrammeEdition
DB --> Backend: List<ProgrammeEdition>
Backend --> Frontend: List<ProgrammeEdition>
Frontend --> ASC: Please select a programme edition
ASC -> Frontend: Select programme edition
Frontend --> ASC: Confirm selection?
ASC -> Frontend: Yes!
Frontend -> Backend: GET /programmeeditions/{id}/students
Backend -> DB: SELECT * FROM ProgrammeEditionEnrolment WHERE programmeEditionID = programmeEditionID
DB --> Backend: List<ProgrammeEditionEnrolment>programmeeditionEnrolments
Backend --> Frontend: int totalNumberOfStudents
Frontend --> ASC: Number of enrolled students: [count]

@enduml
