@startuml
actor admin

admin -> UI ++ #application : I want to configure access method
UI --> admin -- : access method name?
admin -> UI ++ #application :(name)
UI -> ":ConfigureAccessMethodController" as ConfigureAccessMethodController ++ #application : configureAccessMethod (name)

ConfigureAccessMethodController -> ":AccessMethodRepository" as AccessMethodRepository ++ #application : createAccessMethod(name)

create ":AccessMethod" as AccessMethod
AccessMethodRepository -> AccessMethod ++ #application  : <create>(accessMethodName)
AccessMethod -> AccessMethod : isAccessMethodNameValid(accessMethodName);

AccessMethod --> AccessMethodRepository -- : :ac1
AccessMethodRepository -> AccessMethodRepository : isAccessMethodRegistered (ac1)
AccessMethodRepository -> AccessMethodRepository : registerAccessMethod (accessMethodName)

AccessMethodRepository --> ConfigureAccessMethodController --: :ac1

ConfigureAccessMethodController --> UI --: true
UI --> admin --: true
@enduml