@startuml
'left to right direction
skinparam ranksep 60
skinparam nodesep 60

class TeacherRestController {
    +updateTeacherCategoryInTeacherCareerProgression(UpdateTeacherCategoryRequestDTO request)
}

class TeacherCareerProgressionService {
    +TeacherCareerProgressionService(teacherCareerProgressionRepository: ITeacherCareerProgressionRepository,\n teacherCareerProgressionFactory: ITeacherCareerProgressionFactory)
    +updateTeachersCategoryInTeacherCareerProgression(dateVO: DateVO,\n teacherCategoryIDVO: TeacherCategoryIDVO, teacherIDVO: TeacherIDVO)
}

class updateTeacherCategoryRequestDTO {
    -date: String
    -teacherID: String
    -teacherCategoryID :String
    +updateTeacherCategoryRequestDTO(date: String, teacherID: String, teacherCategoryID :String)
}

interface ITeacherCareerAssembler {
  + toCommand(dto: UpdateTeacherCategoryRequestDTO): UpdateTeacherCategoryCommand
  + toResponseDTO(domain: TeacherCareerProgression): UpdateTeacherCategoryResponseDTO
}

class TeacherCareerAssemblerImpl {
  + toCommand(dto: UpdateTeacherCategoryRequestDTO): UpdateTeacherCategoryCommand
  + toResponseDTO(domain: TeacherCareerProgression): UpdateTeacherCategoryResponseDTO
}

class UpdateTeacherCategoryResponseDTO {
  - teacherID: String
  - date: String
  - teacherCategoryID: String
  - workingPercentage: int
}

' Commands
class UpdateTeacherCategoryCommand {
  - teacherID: TeacherID
  - date: Date
  - teacherCategoryID: TeacherCategoryID
}

interface ITeacherCareerProgressionService {
    +updateTeachersCategoryInTeacherCareerProgression(dateVO: DateVO,\n teacherCategoryIDVO: TeacherCategoryIDVO, teacherIDVO: TeacherIDVO)
}

interface ITeacherRepository {
  + containsOfIdentity(teacherID: TeacherID): boolean
}

interface ITeacherCategoryRepository {
  + containsOfIdentity(categoryID: TeacherCategoryID): boolean
}

package "Teacher Aggregate" {
    entity "<<Root>>\n <<Entity>>\n Teacher" {
    +contains()
    }
}

class "<<Value Object>>\n TeacherIDVO" {
}

class "<<Value Object>>\n TeacherAcronymVO" {
    -String: TeacherAcronym
}

package "TeacherCareerProgression Aggregate" {
    entity "<<Root>>\n <<Entity>>\nTeacherCareerProgression" {
        +TeacherCareerProgression(dateVO: DateVO, workingPercentageVO: WorkingPercentageVO)
        +isLastDateEqualOrBeforeNewDate(dateVO: DateVO)
        +getTeacherCategoryID()
        +getWorkingPercentage()
        +getDate()
        +isDateAfter()
    }
}

    class "<<Value Object>>\n TeacherCareerProgressionIDVO" {
          -ID: UUID
    }

    class "<<Value Object>>\n DateVO" {
          -date: LocalDate
    }

    class "<<Value Object>>\n WorkingPercentageVO" {
              -workingPercentage: int
   }

class TeacherCareerProgressionRepository {
    +TeacherCareerProgressionRepository\n(teacherCareerProgressionMapper : TeacherCareerProgressionMapper)
    +findLastTCPFromTeacherID(teacherIDVO: TeacherIDVO)
}

class TeacherRepository {
    +containsOfIdentity()
}

class TeacherCategoryRepository {
    +containsOfIdentity()
}

package "TeacherCategory Aggregate" {
    entity "<<Root>>\n <<Entity>>\nTeacherCategory" {
    }
}

interface ITeacherCareerProgressionRepository {
    +findLastTCPFromTeacherID(teacherIDVO: TeacherIDVO)
}


interface ITeacherRepository {
    +containsOfIdentity()
}

class "<<Value Object>>\n TeacherCategoryIDVO" {
                -id: UUID
}

class TeacherCareerProgressionFactoryImpl {
    +createTeacherCareerProgression(dateVO: DateVO, workingPercentageVO: WorkingPercentageVO,\nteacherCategoryIDVO: TeacherCategoryIDVO, teacherIDVO: TeacherIDVO)

    +createTeacherCareerProgressionFromDataModel(teacherCareerProgressionIDVO: TeacherCareerProgressionIDVO\n ,dateVO: DateVO, workingPercentageVO: WorkingPercentageVO,\nteacherCategoryIDVO: TeacherCategoryIDVO, teacherIDVO: TeacherIDVO)
}

interface ITeacherCareerProgressionFactory {
    +createTeacherCareerProgression(dateVO: DateVO, workingPercentageVO: WorkingPercentageVO,\nteacherCategoryIDVO: TeacherCategoryIDVO, teacherIDVO: TeacherIDVO)

    +createTeacherCareerProgressionFromDataModel(teacherCareerProgressionIDVO: TeacherCareerProgressionIDVO\n ,dateVO: DateVO, workingPercentageVO: WorkingPercentageVO,\nteacherCategoryIDVO: TeacherCategoryIDVO, teacherIDVO: TeacherIDVO)
}

class TeacherCareerProgressionMapper {
    +toDomain(teacherCareerProgressionDataModel :TeacherCareerProgressionDataModel)
    +toDataModel(teacherCareerProgression :TeacherCareerProgression)
}

interface ITeacherCareerProgressionMapper {
    +toDomain(teacherCareerProgressionDataModel :TeacherCareerProgressionDataModel)
    +toDataModel(teacherCareerProgression :TeacherCareerProgression)
}

class TeacherCareerProgressionIDMapper {
    +toDomain(teacherCareerProgressionIDDataModel :TeacherCareerProgressionIDDataModel)
    +toDataModel(teacherCareerProgressionID :TeacherCareerProgressionID)
}

interface ITeacherCareerProgressionIDMapper {
    +toDomain(teacherCareerProgressionIDDataModel :TeacherCareerProgressionIDDataModel)
    +toDataModel(teacherCareerProgressionID :TeacherCareerProgressionID)
}

class TeacherCareerProgressionIDDataModel {
    -UUID id
    +getIdValue()
}

class TeacherCareerProgressionDataModel {
    -teacherCareerProgressionID : UUID
    -date : localDate
    -teacherCategoryID : UUID
    -workingPercentage : int
    -teacherAcronym : String
    -NIF : String
    -Country : String
}


interface ITeacherCareerProgressionRepositorySpringData {
    +save()
    +findTopByTeacherIDOrderByDateDesc()
}

TeacherRestController "1" ..> "_teacherCareerProgressionService \n 1" ITeacherCareerProgressionService
TeacherRestController "1" ..> updateTeacherCategoryRequestDTO
TeacherRestController "1" ..> ITeacherCareerAssembler
TeacherCareerAssemblerImpl ..|> ITeacherCareerAssembler
TeacherCareerAssemblerImpl ..> updateTeacherCategoryRequestDTO
TeacherCareerAssemblerImpl ..>UpdateTeacherCategoryCommand
TeacherCareerAssemblerImpl ..> UpdateTeacherCategoryResponseDTO
TeacherCareerProgressionService ..> ITeacherRepository
TeacherCareerProgressionService ..> ITeacherCategoryRepository
TeacherCategoryRepository ..|> ITeacherCategoryRepository



ITeacherCareerProgressionService "1" <|.. "1" TeacherCareerProgressionService
TeacherCareerProgressionService "1" ..> "1" ITeacherCareerProgressionFactory
TeacherCareerProgressionService "1" ...> "_teacherCareerProgressionRepository \n 1" ITeacherCareerProgressionRepository
TeacherCareerProgressionMapper "1" .u-> "_teacherCareerProgressionFactory \n1" ITeacherCareerProgressionFactory
TeacherCareerProgressionRepository "1" ..> "_teacherCareerProgressionMapper \n1" ITeacherCareerProgressionMapper
ITeacherCareerProgressionMapper "1" <|.. "1" TeacherCareerProgressionMapper
TeacherCareerProgressionMapper "1" ..> "1" TeacherCareerProgressionDataModel
TeacherCareerProgressionMapper "1" ..> "_teacherCareerProgressionIDMapper\n1" ITeacherCareerProgressionIDMapper
ITeacherCareerProgressionIDMapper "1" <|.. "1" TeacherCareerProgressionIDMapper
TeacherCareerProgressionIDDataModel "1" <.. "1" TeacherCareerProgressionIDMapper
"<<Value Object>>\n TeacherIDVO" "1  " <-- "\n 1..*     " "<<Root>>\n <<Entity>>\nTeacherCareerProgression"
TeacherCareerProgressionFactoryImpl "1" ..> "   \n        1..*" "<<Root>>\n <<Entity>>\nTeacherCareerProgression"
TeacherCareerProgressionFactoryImpl .l.|> ITeacherCareerProgressionFactory
"<<Root>>\n <<Entity>>\n Teacher" "1" --> "1" "<<Value Object>>\n TeacherIDVO"
"<<Value Object>>\n TeacherAcronymVO" "1" <-- "1" "<<Value Object>>\n TeacherIDVO"
"<<Root>>\n <<Entity>>\nTeacherCareerProgression" "1" --> "1" "<<Value Object>>\n TeacherCareerProgressionIDVO"
"<<Root>>\n <<Entity>>\nTeacherCareerProgression" "1" --> "1" "<<Value Object>>\n DateVO"
"<<Root>>\n <<Entity>>\nTeacherCareerProgression" "1" --> "1" "<<Value Object>>\n WorkingPercentageVO"
"<<Root>>\n <<Entity>>\nTeacherCareerProgression" "1" --> "1" "<<Value Object>>\n TeacherCategoryIDVO"
"<<Value Object>>\n TeacherCategoryIDVO" "1" <-u- "1" "<<Root>>\n <<Entity>>\nTeacherCategory"
ITeacherCareerProgressionRepository "1" <|.r. "1"  TeacherCareerProgressionRepository
ITeacherRepository "1"  <|.. "1" TeacherRepository
ITeacherCareerProgressionRepositorySpringData "1" <.. "1" TeacherCareerProgressionRepository
@enduml