@startuml

title US01: As an Administrator, I want to configure teacher categories in the system \n (Scenario View - Level 4 - Backend)

skinparam defaultTextAlignment center
skinparam shadowing true

autonumber

participant ":Router" as router
[o-> router: **POST** /teacher-categories + body {"name": "Assistant"}
activate router #E1F5FE

participant ":TeacherCategoryRESTController" as Controller
router -> Controller: configureTeacherCategory (tcRequestDTO)
activate Controller #E1F5FE

ref over Controller
   SD Convert tcRequestDTO to NameVO
end

participant ":ITeacherCategoryService" as service
Controller -> service: configureTeacherCategory (nameVO)
activate service #E1F5FE

participant ":ITeacherCategoryFactory" as Factory
service -> Factory: createTeacherCategory (nameVO)
activate Factory #E1F5FE

create "tcID:TeacherCategoryID"
Factory -> "tcID:TeacherCategoryID": create ()

create "tc:TeacherCategory"
Factory -> "tc:TeacherCategory": create (tcID, nameVO)

Factory --> service: tc
deactivate Factory

participant ":ITeacherCategoryRepository" as Repository
service -> Repository: existsByName (nameVO)
activate Repository #E1F5FE
Repository --> service: false
deactivate Repository

service -> Repository: save (tc)
activate Repository #E1F5FE

ref over Repository
    SD Convert teacherCategory to DataModel
end

participant ":ITeacherCategoryRepositorySpringData" as springDataRepository
Repository -> springDataRepository: save (tcDataModel)
activate springDataRepository #E1F5FE

springDataRepository ->o]: **INSERT INTO** teacherCategory (id, name) \n VALUES ('123e4567-e89b-12d3-a456-426614174000', 'Assistant')

springDataRepository <--o]: teacherCategorySavedDataModel

springDataRepository --> Repository : tcDataModelSaved
deactivate springDataRepository

ref over Repository
    SD Convert tcDataModelSaved to Domain
end

Repository --> service: tcSaved
deactivate Repository

ref over service
    SD Convert tcSaved to DTO
end

service --> Controller: tcSavedDTO
deactivate service

ref over Controller
    SD Convert tcSavedDTO to tcSavedResponseDTO
end

participant ":ITeacherCategoryHateoasAssembler" as hateoasAssembler
Controller -> hateoasAssembler: toModel (tcSavedResponseDTO)
activate hateoasAssembler #E1F5FE

hateoasAssembler --> Controller: EntityModel<TeacherCategoryResponseDTO>
deactivate hateoasAssembler

Controller --> router: 201 + body {EntityModel<TeacherCategoryResponseDTO>}
deactivate Controller

[o<-- router: 201 + body {EntityModel<TeacherCategoryResponseDTO>}
deactivate router

@enduml