@startuml
title: US19: As an ASC, I want to create a course edition\n(Process View - Level 2)
autonumber

skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam sequence {
    LifeLineBorderColor Grey
    LifeLineBackgroundColor HoneyDew
}
skinparam defaultTextAlignment center
skinparam shadowing true

actor ASC  #LightBlue/White
participant "<<Container>>\nFrontend" as Frontend #E1F5FE
participant "<<Container>>\nBackend" as Backend #E1F5FE
database "<<Container>>\nDatabase" as Database #E1F5FE



ASC -> Frontend: I want create\n course edition
activate Frontend
Frontend -> Backend: POST /course-editions + body {...}

activate Backend
Backend -> Database: INSERT INTO course_editions (...)
activate Database
Database --> Backend: courseEdition created
deactivate Database
Backend --> Frontend: 201 Created + body {courseEditionResponseDTO + hypermedia}

deactivate Backend
Frontend --> ASC: Course edition\n created successfully!
deactivate Frontend
@enduml
