@startuml
title: US19: As an ASC, I want to create a course edition\n(Process View - Level 3 - Backend)
autonumber

skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam sequence {
    LifeLineBorderColor Grey
    LifeLineBackgroundColor HoneyDew
}
skinparam defaultTextAlignment center
skinparam shadowing true

participant "<<component>>\n:Router" as Router #E1F5FE
participant "<<component>>\n:Controller" as Controller #E1F5FE
participant "<<component>>\n:Service" as Service #E1F5FE
participant "<<component>>\n:Domain" as Domain #E1F5FE
participant "<<component>>\n:Repository" as Repository #E1F5FE

database DB as DB #E1F5FE

-> Router: POST /courseeditions (JSON)
activate Router
note over Router #EEEEEE
Spring converts JSON into
CourseEditionRequestDTO
end note
Router -> Controller: createCourseEdition(requestDTO)
activate Controller

note over Controller #EEEEEE
Controller calls assembler.toCommand()
to convert to CreateCourseEditionCommand
end note



Controller -> Service: createCourseEditionForRestApi(command)
activate Service


Service -> Domain: createCourseEditionToDomain\n(courseInStudyPlanID,\n programmeEditionID)
activate Domain
Domain --> Service: CourseEdition
deactivate Domain
Service -> Domain: identity()
activate Domain
Domain --> Service: courseEditionID
deactivate Domain

Service -> Repository: containsOfIdentity(courseEditionID)
activate Repository
Repository --> Service: false
deactivate Repository

Service -> Repository: save(courseEdition)
activate Repository

Repository -> DB: INSERT course_edition
activate DB
DB --> Repository: success
deactivate DB

Repository --> Service: saved CourseEdition
deactivate Repository




    Service --> Controller: responseIDDTO
    deactivate Service


    Controller --> Router: 201 Created + ResponseEntity(responseModel)



deactivate Controller

<-- Router: Reponse
deactivate Router
@enduml