@startuml
title: US19: As an ASC, I want to create a course edition\n(Process View - Level 2)
autonumber

skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam sequence {
    LifeLineBorderColor Grey
    LifeLineBackgroundColor HoneyDew
}
skinparam defaultTextAlignment center
skinparam shadowing true

actor ASC  #LightBlue/White
participant "<<Container>>\nFrontend" as Frontend #E1F5FE
participant "<<Container>>\nBackend" as Backend #E1F5FE
database "<<Container>>\nDatabase" as Database #E1F5FE



ASC -> Frontend: I want create course edition
activate Frontend
Frontend -> Backend: POST /course-editions + body {...}
note over Frontend, Backend #HoneyDew
Request body (JSON):
{
  programmeName: "...",
  programmeAcronym: "...",
  schoolYearID: "...",
  courseAcronym: "...",
  courseName: "...",
  studyPlanImplementationDate: "..."
}
end note
activate Backend
Backend -> Database: INSERT INTO course_editions (id, programme_name, programme_acronym, school_year_id, course_acronym, course_name, study_plan_implementation_date) \nVALUES (NEW_ID, programmeName, programmeAcronym, schoolYearID, courseAcronym, courseName, studyPlanImplementationDate)
activate Database
Database --> Backend: courseEditionDataModel
deactivate Database
Backend --> Frontend: 201 Created + body {courseEditionResponseDTO + hypermedia}
note over Backend, Frontend #HoneyDew
Response body (JSON):
{
  courseEditionID: NEW COURSE EDITION ID,
  programmeName: "...",
  programmeAcronym: "...",
  ...
}
end note
deactivate Backend
Frontend --> ASC: Ok!
deactivate Frontend
@enduml
