@startuml
title: US19: As an ASC, I want to create a course edition\n(Process View - Level 2)
autonumber

skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam sequence {
    LifeLineBorderColor Grey
    LifeLineBackgroundColor HoneyDew
}
skinparam defaultTextAlignment center
skinparam shadowing true

actor ASC  #LightBlue/White
participant "<<Container>>\nFrontend" as Frontend #E1F5FE
participant "<<Container>>\nBackend" as Backend #E1F5FE
database "<<Container>>\nDatabase" as Database #E1F5FE



ASC -> Frontend: I want create course edition
activate Frontend
Frontend -> Backend: POST /courseeditions (...)
note over Frontend, Backend #HoneyDew
Request body (JSON):
{
  programmeName: "...",
  programmeAcronym: "...",
  schoolYearID: "...",
  courseAcronym: "...",
  courseName: "...",
  studyPlanImplementationDate: "..."
}
end note
activate Backend
Backend -> Database: INSERT INTO course_editions (data)
activate Database
Database --> Backend: Confirmation + new courseEditionID
deactivate Database
Backend --> Frontend: 201 Created + course edition data + ID
note over Backend, Frontend #HoneyDew
Response body (JSON):
{
  courseEditionID: NEW COURSE EDITION ID,
  programmeName: "...",
  programmeAcronym: "...",
  ...
}
end note
deactivate Backend
Frontend --> ASC: Course edition created successfully!
deactivate Frontend
@enduml
