@startuml

title As an ASC I want to remove the enrolment of a student in a course edition using a WEB UI \n (Process View Level 3 - Backend - removeStudentFromCourseEdition)


skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue

participant ":Router" as RT <<Component>> #lightpink
participant "CERC:StudentRestController " as C <<Component>> #motivation
participant "CEES:CourseEditionEnrolmentService" as S <<Component>> #business
participant "CEER:CourseEditionEnrolmentRepository" as RP <<Component>> #lightgreen
participant ":Drivers" as D <<Component>> #technology

 [o-> RT ++: **PATCH**  \nstudents/{studentId}/course-editions/{courseEditionGeneratedUUID} \t
 RT -> C ++: removeStudentEnrolmentFromACourseEdition\n(studentUniqueNumber, courseEditionGeneratedUUID)
 C -> S ++: removeCourseEditionEnrolment(studentID, courseEditionID)
 S -> RP ++: findCourseEditionByGeneratedID(courseEditionGeneratedID)
 RP -> D ++: findCourseEditionByGeneratedId \n (courseEditionGeneratedIDDataModel)
 D ->o] : **SELECT** CourseEditionGeneratedIDDataModel \n (courseEditionGeneratedIDDataModel)

 D <--o]  : courseEditionDataModel
 D --> RP --: courseEditionDataModel
 RP --> S --: courseEdition
 S --> C --: courseEditionID
 |||
 C -> S ++ : removeCourseEditionEnrolment(studentID, courseEditionID)
 S -> RP ++ : findByStudentAndEdition(studentID, courseEditionID)
 RP -> D ++ : findById_StudentIDAndId_CourseEditionID \n (studentIDDataModel, courseEditionIDDataModel)
 D ->o] : **SELECT** findById_StudentIDAndId_CourseEditionID \n (studentIDDataModel, courseEditionIDDataModel)
 D <--o] : courseEditionEnrolmentDataModel
 D --> RP -- : courseEditionEnrolmentDataModel
 RP --> S -- : courseEditionEnrolment
 S --> C -- : True!
 C --> RT --: (ACCEPTED, 202) \n + body {"Successfully removed the enrolment from course edition."}
  [o<-- RT --: (**ACCEPTED, 202**) \n + body {"Successfully removed the enrolment from course edition."}
@enduml