@startuml
autonumber

title As an ASC I want to remove the enrolment of a student \n in a course edition (Process View Level 1)
skinparam sequenceLifeLineBackgroundColor #lightblue

actor ASC as Admin
participant "<<System>>\n:SystemPAI" as System

activate Admin
Admin -> System : I want to remove a student's enrolment from a Course Edition
activate System
System --> Admin : Select a student's enrolment.
deactivate System

Admin -> System : Enrolment!
activate System
System --> Admin : Enrolment removed successfully!
deactivate System

@enduml