@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title As an ASC I want to remove the enrolment of a student in a course edition using a WEB UI \n (Process View Level 3 - getAllCourseEditions)

participant ":Router" as Router <<Component>> #lightpink
participant ":CourseEditionRestController" as Controller <<Component>> #motivation
participant ":CreateCourseEditionServiceImpl" as Service <<Component>> #business
participant ":CourseEditionRepository" as Repository <<Component>> #lightgreen
participant ":Drivers" as D <<Component>> #technology

-> Router : **GET** /course-editions/
activate Router
Router -> Controller : findAllCourseEditions()
activate Controller
Controller -> Service : findAll()
activate Service
Service -> Repository : findAll()
activate Repository
Repository -> D ++: findAll()
D -> : **SELECT** findAll()
D <-- : List<CourseEditionDataModel>
Repository <-- D -- : List<CourseEditionDataModel>
Repository --> Service : List<CourseEdition>
deactivate Repository
Service --> Controller : List<CourseEditions>
deactivate Service
Controller --> Router : List<CourseEditionResponseDTO>
deactivate Controller
<-- Router : (200, OK) List<CourseEditionResponseDTO>
deactivate Router


@enduml