@startuml
autonumber
title As an ASC I want to remove the enrolment of a student \n in a course edition (Process View Level 2)
skinparam sequenceLifeLineBackgroundColor lightblue
skinparam sequenceMessageAlign center

actor ASC
participant "<<Component>> \nFrontend" as FE #lightblue
participant "<<Component>> \nBackend" as BE #lightgreen
participant "<<Component>> \nDatabase" as DB #lightyellow

activate ASC
ASC -> FE : I want to remove \nthe enrolment of a student.
activate FE
FE -> BE : **GET** /students/{studentId}/enrolled-course-editions/
activate BE
BE -> DB : **SELECT** enrolledCourseEditionsForStudent()
activate DB
DB --> BE : List<EnrolledCourseDetails>
deactivate DB
BE --> FE : (OK,200) List<EnrolledCourseDetails>
deactivate BE
FE --> ASC : Which student's course edition?
deactivate FE

ASC -> FE : Student's course edition!
activate FE
FE -> BE : **PATCH** /students/{studentId}/course-editions/{courseEditionGeneratedUUID}
activate BE
BE -> DB : **SELECT** removeStudentEnrolment
activate DB
DB --> BE : (OK,200) "Enrolment removed"
deactivate DB
BE --> FE : (OK,200) "Enrolment removed"
deactivate BE
FE --> ASC : Student [StudentID] has been removed.
deactivate FE

@enduml
