@startuml
autonumber

title As an ASC, I want to change a programme director in the system.

actor ASC as Admin

participant ":UI" as UI #lightyellow
participant "pCtrl:ProgrammeRestController" as C #implementation
participant "pService:ProgrammeService" as PS #physical
participant "P1:Programme" as P #lightpink
participant "pRepo:ProgrammeRepository" as PR #lightcyan

activate Admin
Admin -> UI ++: I want to change a programme director in the System

UI -> C ++: getAllProgrammes()

ref over C
          Get Programmes List
end ref

C --> UI --: List<ProgrammeDTO>

UI --> Admin --: Choose a Programme from the list

Admin -> UI ++: Programme

UI -> C ++: getAllTeachers()

ref over C
          Get Teachers List
end ref

C --> UI --: List<TeacherDTO>

UI --> Admin --: Choose a Teacher from the list

Admin -> UI ++: teacher

UI -> C ++: changeAProgrammeDirectorInTheSystem \n(ProgrammeRequestDTO)

ref over C
    Convert ProgrammeRequestDTO
    to ProgrammeVOsDTO
end ref

C -> PS ++: changeProgrammeDirector(programmeIDVO, teacherIDVO)

PS -> P ++: newProgrammeDirector(programmeIDVO, teacherIDVO)

P -> PS --: PD1

PS -> PR ++: saveProgrammeDirector(PD1)

ref over PR
    Save in Database
    Convert domain object to DataModel and persist using JPA
end ref

PR --> PS --: PD1

PS --> C --: PD1

ref over C
    Convert PD1 to ProgrammeResponseDTO
end ref

C --> UI --: ProgrammeResponseDTO

UI --> Admin --: Programme Director updated successfully!

@enduml