@startuml
'https://plantuml.com/class-diagram

class US24_KnowTheNumberOfStudentsEnroledInACourseEditionController {
+US24_KnowTheNumberOfStudentsEnroledInACourseEditionController ()
+IWantToKnowNumberOfStudentsEnrolledInCourseEdition(CourseEdition courseEdition)
}

class CourseEditionEnrolmentRepository {
    -_courseEditionEnrolments: ArrayList<CourseEditionEnrolment>
    +CourseEditionEnrolmentRepository ()
    +enrollStudentInACourseEdition (student: Student, courseEdition: CourseEdition,
    enrollmentDate: LocalDate)
    +isStudentEnrolledInCourseEdition (student: Student, courseEdition: CourseEdition)
    +findByStudentAndEdition (student: Student, courseEdition: CourseEdition)
    +numberOfStudentsEnrolledInCourseEdition (courseEdition: CourseEdition)
    +enrollStudentInProgrammeCourseEditions(student :Student, courseEditions : List<CourseEdition>)
}

class CourseEditionEnrolment {
    -_enrollmentDate: LocalDate
    +CourseEditionEnrolment(student:Student, courseEdition: CourseEdition,
     enrollmentDate: LocalDate)
    +equals (obj: Object)
    +findStudentInCourseEditionEnrolment ()
    +findCourseEditionInEnrolment ()
    +knowStudent ()
    +knowCourseEdition ()
}

US24_KnowTheNumberOfStudentsEnroledInACourseEditionController "1" ---> "_courseEditionEnrolmentRepository 1"CourseEditionEnrolmentRepository
CourseEditionEnrolmentRepository "1 " ---> " * "CourseEditionEnrolment


@enduml