@startuml
'https://plantuml.com/sequence-diagram

actor AcademicServiceCollaborator as ASC #Purple/White
participant ":UI" as UI #application
participant ":Controller" as C #application
participant "cee[i]:CourseEditionEnrollementRepository" as CEER #application

ASC -> UI : I want to get the number of students enrolled in CourseEdition1
activate UI #application
UI -> C  : IWantToKnowNumberOfStudentsEnrolledInCourseEdition1
activate C #application
C -> CEER : IWantToKnowNumberOfStudentsEnrolledInCourseEdition(CourseEdition1)
activate CEER #application

note right of CEER : Validate if CourseEdition1 is null

loop cce[i] < _courseEditionEnrollments.size()
    CEER -> CEER : numberOfStudentsEnrolledInCourseEdition(CourseEdition1)
end loop

C <-- CEER : numberOfStudents
deactivate CEER #application
UI <-- C : numberOfStudents
deactivate C #application
ASC <-- UI : numberOfStudents
deactivate UI #application

@enduml