@startuml
'https://plantuml.com/class-diagram

!pragma layout smetana
'left to right direction'

class US24_IWantToKnowTheNumberOfStudentsEnrolledInACourseEditionController {
+US24_IWantToKnowTheNumberOfStudentsEnrolledInACourseEditionController ()
+IWantToKnowNumberOfStudentsEnrolledInCourseEdition(CourseEdition courseEdition)
}

class CourseEditionEnrolmentRepository {
    -_courseEditionEnrolments: ArrayList<CourseEditionEnrolment>
    +CourseEditionEnrolmentRepository ()
    +enrollStudentInACourseEdition (student: Student, courseEdition: CourseEdition,
    enrollmentDate: LocalDate)
    +isStudentEnrolledInCourseEdition (student: Student, courseEdition: CourseEdition)
    +findByStudentAndEdition (student: Student, courseEdition: CourseEdition)
    +numberOfStudentsEnrolledInCourseEdition (courseEdition: CourseEdition)
    +enrollStudentInProgrammeCourseEditions(student :Student, courseEditions : List<CourseEdition>)
}

class CourseEditionEnrolment {
    -_enrollmentDate: LocalDate
    +CourseEditionEnrolment(student:Student, courseEdition: CourseEdition,
     enrollmentDate: LocalDate)
    +equals (obj: Object)
    +findStudentInCourseEditionEnrolment ()
    +findCourseEditionInEnrolment ()
    +knowStudent ()
    +knowCourseEdition ()
}

class CourseEditionEnrolmentFactory {
createCourseEditionEnrollment(Student, CourseEdition)
}

class ICourseEditionEnrolmentFactory {
CourseEditionEnrolment createCourseEditionEnrollment(Student, CourseEdition)
}

US24_IWantToKnowTheNumberOfStudentsEnrolledInACourseEditionController "1  " ---> "1  "CourseEditionEnrolmentRepository
CourseEditionEnrolment "<<creates>> " <...  CourseEditionEnrolmentFactory
CourseEditionEnrolmentFactory  ...|>  ICourseEditionEnrolmentFactory
CourseEditionEnrolmentRepository "List<CourseEditionEnrolment>   " o--- "1..*" CourseEditionEnrolment
CourseEditionEnrolmentFactory <-- CourseEditionEnrolmentRepository
@enduml