@startuml
title: US19_CREATE A COURSE EDITION_SEQUENCE SYSTEM DIAGRAM
autonumber

actor ASC
participant SYSTEM
ASC -> SYSTEM:  I want to create a Course Edition
SYSTEM --> ASC -- : which programme edition??
ASC -> SYSTEM: programme edition!
SYSTEM --> ASC -- : which course?
ASC -> SYSTEM: course!
SYSTEM --> ASC --: Success


@enduml