@startuml
autonumber

title US13: As a HRC, I want to register a new teacher in the system, including all relevant data.

actor HRC
participant "Frontend" as FE
participant "Backend" as BE
database DB #lightgray/gray

HRC -> FE ++: I want to register a new teacher\nincluding all relevant data.

FE -> BE ++: (GET) Request list of categories
BE -> DB ++: Fetch all categories
DB --> BE --: List of categories
BE --> FE --: List of categories

FE -> BE ++: (GET) Request list of departments
BE -> DB ++: Fetch all department
DB --> BE --: List of department
BE --> FE --: List of department

FE --> HRC --: What are the Teacher's attributes?

HRC -> FE ++: acronym, name, email, NIF, phoneNumber, \n academicBackground, street, postalCode,\nlocation, country, department, category



FE -> BE ++: (POST) Create Teacher and Career Progression

BE -> DB ++: Insert into teacher
DB --> BE --: Insert confirmed

BE -> DB ++: Insert into\nteacher category
DB --> BE --: Insert confirmed

BE --> FE --: (201 OK) Created successfuly
FE --> HRC --: Teacher and Career Progression\nregistered successfully!

@enduml
