@startuml
autonumber

title US13: As a HRC, I want to register a new teacher in the system, including all relevant data.

actor HRC
participant ":System" as System #lightgrey

HRC -> System: I want to register a new teacher including all relevant data.\t
activate System #silver
System --> HRC: What are the Teacher's attributes?
HRC -> System: acronym, name, email, NIF, phoneNumber, \n academicBackground, street, postalCode,\nlocation, country, department, teacherCategory

System --> HRC: Teacher with Career Progression registered successfully!
deactivate System


Note Right HRC #lightgray/White
    **teacherCategory** = A Teacher Category already in system
    **department** = A Department already in system
End Note
@enduml