@startuml
title US30 As an ASC, I want to add a course to a programme using a Web UI. \n (Process View - Level 4 Granularity)

autonumber

participant ":Router" as router <<component>> <<Router>> #lightblue
participant ":RESTController" as restController <<component>> <<RESTController>> #teal
participant ":Service" as service <<component>> <<Service>> #lightgreen
participant ":Domain" as domain <<component>> <<Domain>> #orange
participant ":Repository" as repository <<component>> <<Repository>> #grey

note over router: JSON payload includes the following attributes:\n semester, curricularYear, courseID, studyPlanID,\n durationOfCourse, quantityOfCreditsEcts


-> router: addCourseToProgramme (JSON)
activate router #E1F5FE

note over router: The conversion from JSON to DTO is done automatically through the Spring Boot Framework

router -> restController: addCourseToProgramme (DTO)
activate restController #E1F5FE

ref over restController
    Convert addCourseToProgrammeRequestDTO to addCourseToProgrammeRequestVO
end

restController -> service: addCourseToProgramme (VO)
activate service #E1F5FE

service -> domain: addCourseToProgramme (VO)
activate domain #E1F5FE

domain --> service: courseInStudyPlanVO
deactivate domain

service -> repository: save(courseInStudyPlanVO)
activate repository

repository --> service: courseInStudyPlanVO
deactivate repository

ref over restController
    Convert courseInStudyPlanVO to courseInStudyPlanDTO
end

service --> restController: courseInStudyPlanVO
deactivate service

restController --> router: (201, Created) courseInStudyPlanDTO
deactivate restController

<-- router: (201, Created) courseInStudyPlanJSON

note over router: The conversion from DTO to JSON is done automatically through the Spring Boot Framework

@enduml