@startuml


title "PAI \n (Implementation View - Level 1)"

skinparam rectangle {
  BorderColor Orange
  BackgroundColor White
}

  component "<system>\nPAI" as PAI {
    portin " " as p1
    portin " " as p2
    portin " " as p3
  }

  interface "UI" as UI
  interface "REST API" as API
  interface "File I/O" as FileIO


  p1 -up- UI
  p2 -up- API
  p3 -up-( FileIO
}

@enduml
