@startuml
title Convert defineRucRequestDTO to Domain

skinparam defaultFontName "Verdana"
skinparam defaultTextAlignment center
skinparam shadowing true
skinparam participantBackgroundColor #lightblue/white

autonumber

participant ":CourseEditionRestController" as Controller
participant ":DefineRucRequestDTO" as DTO
participant ":CourseEditionAssembler" as Assembler

== Get TeacherID from DTO ==

-> Controller: defineRucForCourseEdition(defineRucRequestDTO)
activate Controller #E1F5FE
Controller -> DTO : getTeacherID()
activate DTO #E1F5FE
DTO --> Controller : "teacherID"
deactivate DTO

== Create TeacherID ==
Controller -> Assembler : createTeacherID("teacherID")
activate Assembler #E1F5FE
Assembler -> ":TeacherAcronym"** : new TeacherAcronym(teacherID)
Assembler -> ":TeacherID" ** : new TeacherID(teacherAcronym)
deactivate Assembler



deactivate Assembler

@enduml
