@startuml
!pragma layout smetana
left to right direction

class Department {
    -_acronym:String
    -_name:String
    +Department(departmentAcronym: String, departmentName: String)
    +Department(departmentAcronym: String, departmentName: String,director: Teacher)
    +hasSameAcronym(department: Department)
    +hasSameName(department: Department)
    +changeDirector(furtherDirector: Teacher)
}

class DepartmentRepository {
    -_departments: List<Department>
    +departmentRepository()
    +registerDepartment(departmentAcronym: String, departmentName: String)
}


class Facility

class TeacherCategory {
    -_name:String
}

class Programme {
     - name: string
     - acronym: string
     - quantityOfEcts: int
     - quantityOfSemesters: int
     -_programmeEnrolment: List<Enrolment>

     + Equals()
     + addCourse(): boolean
     + newProgrammeDirector(): boolean
     + isSameProgrammeDirector(): boolean
     +enrolStudentInProgramme(Student: student, accessMethod: AccessMethod, amr: AccessMethodRepository)
 }

class DegreeType {
    - name: string
    - maxEcts: int
    + nameIsInvalid(): boolean
    + maxEctsIsInvalid(): boolean
}

class Teacher {
     -_acronym:String
     -_name:String
     -_email:String
     -_nif:String
     -_phoneNumber:String
     +Teacher(acronym: String, name:String, email: String, nif: String, phoneNumber:String,
     address: Address, teacherCategory: TeacherCategory, department: Department)
     +hasSameAcronym(teacher: Teacher)
     +hasSameNif(teacher: Teacher)
     +isInDepartment(department: Department)
}

class TeacherRepository {
    -_teachers: List<Teacher>
    +teacherRepository()
    +registerTeacher(acronym: String, name:String, email: String, nif: String, phoneNumber:String,
                          address: Address, teacherCategory: TeacherCategory, department: Department)
}


class SchoolYear {
    -_description:String
    -_startData:String
    -_endDate:String
    +SchoolYear(description: String, StartDate: String, EndDate: String)
    +getSchoolYear(description: String, StartDate: String, EndDate: String)
    +isSameSchoolYear(otherSchoolYear: SchoolYear)
}

class SchoolYearRepository {
    -_schoolYearList: List<SchoolYear>
    +schoolYearRepository()
    +addSchoolYear(description: String, StartDate: String, EndDate: String)
}

class Enrolment {
    -_student: Student
    -_accessMethod: AccessMethod
    +Enrolment(student: Student, accessMethod: AccessMethod)
    +isSameStudent(student: Student)
}

class Student {
    -_uniqueNumber:int
    -_name:String
    -_NIF:String
    -_phone:String
    -_email:String
    +Student(uniqueNumber: int, name: String, NIF: String, phone: String, email: String, address: Address)
    +isStudentRepeated(students: List<Student>)
    +hasSameUniqueNumber(Student student)
}

class StudentRepository {
    -_students: List<Student>
    +registerStudent(uniqueNumber: int, name: String, NIF: String, phone: String, email: String, address: Address)
}

class AccessMethod {
    -_type:String
}

class Address {
     -_street:String
     -_postalCode: String
     -_location: String
     -_country: String
     +Address(street: String, postalCode: String, location: String, country: String)
}

class Course {
    -_name: String
    -_acronym: String
    -_ECTS: int
}

Department "1" -- "1..*" Facility : aggregates
Teacher "1" --> "1" Address: has
Student "1" --> "1" Address: has
Programme "1..*" --> "1" Teacher : has a Programme Director
Teacher "1" -- "*" TeacherCategory: has
Teacher "1..*" -- "*" Course: Teach
Course "*" -- "1..*" Semester: is associated to
Course  "1..*" <-- "1" Programme: has
Programme "1" -- "1..*" Semester: has
Programme "*" -up-> "1*" Department: Assigned to
DegreeType "1" <-- "*" Programme
Enrolment "*" --> "1" AccessMethod: is registered
Programme "1"  -u-> "*" Enrolment: has
Student "1" <-- "*" Enrolment: enrolls
StudentRepository "1" --> "*" Student
SchoolYearRepository "1" --> "*" SchoolYear
Teacher "1" -r- "1" Department: is Department Director
Teacher "1..*" -- "1" Department: aggregates
Teacher "1..*" -- "1" TeacherRepository
Department "1..*" -- "1" DepartmentRepository
@enduml
