@startuml
title Register a Programme, including Study Plan (Granularity 2)


actor ASC
participant Frontend
participant Backend
database Database

activate Frontend
ASC -> Frontend: Fill and submit programme \nform with study plan

Frontend -> Backend: POST /programmes/studyplans
activate Backend
note right Frontend
  Sent as JSON format,
  Converted to
   ProgrammeStudyPlanDTO
end note

Backend -> Database: Save(programmeDM)
activate Database
Database --> Backend: OK
deactivate Database
|||
Backend -> Database: Save(studyPlanDM)
activate Database
Database --> Backend: OK
deactivate Database

Backend --> Frontend: 201 Created \n\t+ \nProgrammeStudyPlanResponseDTO\t
deactivate Backend
note right Frontend
  Sent as
  ProgrammeStudyPlanResponseDTO,
  Converted to JSON
end note

Frontend --> ASC: Confirmation \n\t+ \ncreated programme details
@enduml