@startuml
title Register a Programme, including the Study Plan (Granularity 1)
actor ASC
participant ":System" as system

ASC -> system: **requestProgrammeRegistration**()
activate system
system --> ASC: **provideRequiredDataFields**()
deactivate system
|||
ASC -> system: **getAvailableDegreeTypes**()
activate system
system --> ASC: degreeTypesList
deactivate system
|||
ASC -> system: **getAvailableDepartments**()
activate system
system --> ASC: departmentsList
deactivate system
|||
ASC -> system: **getAvailableTeachers**()
activate system
system --> ASC: teachersList
deactivate system
|||
ASC -> system: **selectIncludeStudyPlanOption**(yes)
activate system
system --> ASC: **provideStudyPlanDataFields**()
deactivate system
|||
ASC -> system: **submitProgrammeDataWithStudyPlan**(name, acronym, ects, semesters, \ndegreeType, department, programmeDirector, studyPlanStartingDate)
activate system
system --> ASC: **registrationConfirmation**(createdProgramme)
deactivate system

@enduml