@startuml
title Register a Programme, including Study Plan (System - Granularity 2)
skinparam sequenceLifeLineBackgroundColor lightblue
skinparam sequenceMessageAlign center
autonumber

actor ASC #F5B041
participant Frontend <<container>> #D7BDE2
participant Backend <<container>> #A2D9CE
database Database <<container>> #F9E79F

activate ASC
ASC -> Frontend++: **requestProgrammeRegistration**()
Frontend --> ASC--: **provideRequiredDataFields**()
|||
ASC -> Frontend++: **getAvailableDegreeTypes**()
Frontend -> Backend: **(GET) getAllDegreeTypes**()
activate Backend
Backend -> Database: **findAll**()
activate Database
Database --> Backend: degreeTypesDMList
deactivate Database
Backend --> Frontend: degreeTypesList
deactivate Backend
Frontend --> ASC--: degreeTypesList
|||
ASC -> Frontend++: **getAvailableDepartments**()
Frontend -> Backend: **(GET) getAllDepartments**()
activate Backend
Backend -> Database: **findAll**()
activate Database
Database --> Backend: departmentsDMList
deactivate Database
Backend --> Frontend: departmentsList
deactivate Backend
Frontend --> ASC--: departmentsList
|||
ASC -> Frontend++: **getAvailableTeachers**()
Frontend -> Backend: **(GET) getAllTeachers**()
activate Backend
Backend -> Database: **findAll**()
activate Database
Database --> Backend: teachersDMList
deactivate Database
Backend --> Frontend: teachersList
deactivate Backend
Frontend --> ASC--: teachersList
|||
ASC -> Frontend++: **submitProgrammeData**(name, acronym, ects, semesters, \ndegreeType, department, programmeDirector)
Frontend -> Backend: **(POST) registerProgramme**\n(ProgrammeStudyPlanDTO)
activate Backend
note right Frontend
  Receive as JSON format,
  Converted to
  ProgrammeDTO
end note

Backend -> Database: **save**(programmeDM)
activate Database
Database --> Backend: True
deactivate Database
Backend --> Frontend: 201 Created \n+ \nprogrammeResponseDTO
deactivate Backend
note right Frontend
  Receive as programmeDTO,
  converted to JSON
end note
|||
Frontend --> ASC--: Confirmation \n+ \ncreatedProgramme
|||
ASC -> Frontend++: **selectIncludeStudyPlanOption**(yes)
Frontend --> ASC--: **provideStudyPlanDataFields**()
ASC --> Frontend++: **submitStudyPlanData**(programmeName, \nprogrammeAcronym, startDate)

Frontend -> Backend++: **(POST) registerStudyPlan**(programmeName, \nprogrammeAcronym, startDate)
Backend -> Database++: **findById**(programmeIDDM)
Database --> Backend--: programme
|||
Backend -> Database: **findById**(degreeTypeIdDM)
activate Database
Backend <-- Database: degreeTypeId
deactivate Database
|||
Backend -> Database: **save**(studyPlanDM)
activate Database
Database --> Backend: studyPlan
deactivate Database

Backend --> Frontend: 201 Created \n+ \nStudyPlanResponseDTO\t
deactivate Backend
note right Frontend
  Send as StudyPlanResponseDTO,
  Converted to JSON
end note

Frontend --> ASC--: Confirmation \n+ \ncreatedStudyPlan
@enduml