@startuml
title Register Study Plan (Backend - Granularity 3)
skinparam sequenceLifeLineBackgroundColor lightblue
skinparam sequenceMessageAlign center
autonumber

participant ":Router" as Router <<component>> #ADD8E6
participant ":ProgrammeRestController" as RestController <<controller>> #82CFFD
participant ":StudyPlanService" as Service <<service>> #F6CBA5
participant ":Domain" as Domain <<domain>> #C4E29A
participant ":ProgrammeSpringDataRepository" as ProgrammeRepository <<repository>> #DDD5F2
participant ":DegreeTypeSpringDataRepository" as DegreeTypeRepository <<repository>> #E6D3A3
participant ":StudyPlanSpringDataRepository" as Repository <<repository>> #CFE2F3

-> Router: **(POST)** \n /programmes/{id}/studyPlans
activate Router
Router -> RestController: registerStudyPlan (acronym, startDate)
activate RestController
RestController -> Service: **registerStudyPlan**(studyPlanCommand)
activate Service
Service -> ProgrammeRepository ++: **ofIdentity**(programmeID)
ProgrammeRepository -> : **findById**(programmeIDDM)
ProgrammeRepository <-- : programmeDM
ProgrammeRepository --> Service --: programme

Service -> DegreeTypeRepository ++: **ofIdentity**(degreeTypeId)
DegreeTypeRepository -> : **findById**(degreeTypeIdDM)
DegreeTypeRepository <-- : degreeTypeDM
DegreeTypeRepository --> Service --: degreeType
|||
Service -> Domain ++: **programme.getQuantSemesters**()
Domain --> Service --: quantityOfSemesters
|||
Service -> Domain ++: **degreeType.getMaxEcts()**
Domain --> Service --: maxEcts
|||
Service -> Domain: createStudyPlan(programmeID, startDate,\ndurationInYears, maxEcts)
activate Domain
Domain --> Service: studyPlan
deactivate Domain
|||
Service -> Repository: save(studyPlan)
activate Repository
Repository -> : save(studyPlanDM)
Repository <-- : True
Repository --> Service: studyPlan
deactivate Repository
Service --> RestController: StudyPlanDTO
deactivate Service
|||
Router <-- RestController: 201 Created \n+ \nStudyPlanResponseDTO\t
deactivate RestController
 <-- Router : 201 Created \n+ \nStudyPlanResponseDTO\t
 note left Router
   Send as
   StudyPlanResponseDTO,
   Converted to JSON
 end note
deactivate Router
@enduml