@startuml
title Register a Programme, including the Study Plan (Granularity 1)
skinparam sequenceLifeLineBackgroundColor lightblue

actor ASC #F5B041
participant "PAI" as system <<System>> #ABEBA1

activate system
ASC -> system: **requestProgrammeRegistration**()
system --> ASC: **provideRequiredDataFields**()
|||
ASC -> system: **getAvailableDegreeTypes**()
system --> ASC: degreeTypesList
|||
ASC -> system: **getAvailableDepartments**()
system --> ASC: departmentsList
|||
ASC -> system: **getAvailableTeachers**()
system --> ASC: teachersList
|||
ASC -> system: **selectIncludeStudyPlanOption**(yes)
system --> ASC: **provideStudyPlanDataFields**()
|||
ASC -> system: **submitProgrammeDataWithStudyPlan**(name, acronym, ects, semesters, \ndegreeType, department, programmeDirector, studyPlanStartingDate)
system --> ASC: **registrationConfirmation**(createdProgramme)

@enduml