@startuml
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title: I want to know the approval percentage of a Course Edition \n (Process View Level 1)
actor ProgrammeDirector
participant ":System" as System #lightblue

ProgrammeDirector -> System  : I want to know the approval percentage of a Course Edition
activate System
System --> ProgrammeDirector  : Which Course Edition?
deactivate System
ProgrammeDirector -> System  : Course Edition!
activate System
System --> ProgrammeDirector  : Confirm?
deactivate System
ProgrammeDirector -> System  : Yes!
activate System
System --> ProgrammeDirector  : Success!
deactivate System
@enduml