@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title: I want to know the approval percentage of a Course Edition \n (Process View Level 2)
actor ProgrammeDirector as ProgrammeDirector #lightgrey

participant "<<Component>> \nFrontend" as FE #application
participant "<<Component>> \nBackend" as BE #strategy
participant "<<Component>> \nDataBase" as Database #strategy


ProgrammeDirector -> FE : Find the approval percentage of a Course Edition
activate FE
FE -> BE : (GET) \n Retrieve all Course Editions
activate BE
BE --> Database : (GET) \n Retrieve all Course Editions
activate Database
Database --> BE : All Course Editions
deactivate Database
BE --> FE : All Course Editions
deactivate BE
FE --> ProgrammeDirector : Which Course Edition?
deactivate FE

ProgrammeDirector -> FE: Course Edition!
activate FE
FE -> BE : (GET) \n Approval rate of Course Edition
activate BE
BE --> Database : (GET) \n Calculate approval rate
activate Database
Database --> BE :Approval rate
deactivate Database
BE --> FE : Approval rate
deactivate BE
FE --> ProgrammeDirector : Approval rate
deactivate FE


@enduml