@startuml

autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title I want to know the approval percentage of a Course Edition \n (Process View Level 3)
skinparam sequencemessagealign center

actor ProgrammeDirector
participant ":Router" as Router <<Component>> #application
participant ":Controller" as Controller <<Component>> #motivation
participant ":Service" as Service <<Component>> #business
participant ":Repository" as Repository <<Component>> #technology
participant ":Domain" as Domain <<Component>> #physical

ProgrammeDirector -> Router : Find approval rate in a **CourseEdition**
activate Router
Router -> Controller : **(GET)** Retrieve all Course Editions
activate Controller
Controller -> Service : Retrieve all Course Editions
activate Service
Service -> Repository : Retrieve all Course Editions
activate Repository
Repository ->  : Retrieve all Course Editions
Repository <--  : All Course Editions
Repository --> Service : All Course Editions
deactivate Repository
Service --> Controller : All Course Editions
deactivate Service
Controller --> Router : All Course Editions
deactivate Controller


Router --> ProgrammeDirector : Choose a Course Edition
ProgrammeDirector -> Router : Course Edition!


Router -> Controller : **(POST)** Calculate approval rate

activate Controller
Controller -> Service : Calculate approval rate

activate Service
Service -> Repository : Retrieve students' grades.
activate Repository
Repository --> Service : Students' grades
deactivate Repository

Service --> Controller : Approval rate
deactivate Service

Controller --> Router : Approval rate
deactivate Controller

Router --> ProgrammeDirector : Approval rate!
deactivate Router

@enduml