@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title: I want to know the approval percentage of a Course Edition \n (Process View Level 2)
actor ProgrammeDirector as ProgrammeDirector #lightgrey

participant "<<Component>> \nFrontend" as FE #application
participant "<<Component>> \nBackend" as BE #strategy
participant "<<Component>> \nDataBase" as Database #strategy

activate ProgrammeDirector
ProgrammeDirector -> FE : Find the approval percentage of a Course Edition
activate FE
FE -> BE : GET /course-editions/
activate BE
BE -> Database : findAll()
activate Database
Database --> BE : All Course Editions
deactivate Database
BE --> FE : All Course Editions
deactivate BE
FE --> ProgrammeDirector : Which Course Edition?
deactivate FE

ProgrammeDirector -> FE: Course Edition!
activate FE
FE -> BE : GET /approval-rate (programmeAcronym,\n schoolYearId, courseAcronym, \n courseName,studyPlanDate)

activate BE
BE -> Database : getCourseEditionApprovalRate(CourseEditionID)
activate Database
Database --> BE : ApprovalRateResponseDTO
deactivate Database
BE --> FE : ApprovalRateResponseDTO
deactivate BE
FE --> ProgrammeDirector : Approval rate
deactivate FE
deactivate ProgrammeDirector

@enduml