@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title I want to know the approval percentage of a Course Edition - Get Course Editions \n (Process View Level 3)
skinparam sequencemessagealign center

participant ":Router" as Router <<Component>> #application
participant ":CourseEditionRestController" as Controller <<Component>> #motivation
participant ":CreateCourseEditionServiceImpl" as Service <<Component>> #business
participant ":CourseEditionRepository" as Repository <<Component>> #technology
participant ":Domain" as Domain <<Component>> #physical

-> Router : GET /courseeditions/
activate Router
Router -> Controller : findAllCourseEditions()
activate Controller
Controller -> Service : findAll()
activate Service
Service -> Repository : findAll()
activate Repository
Repository ->  : findAll()
Repository <--  : All Course Editions
Repository --> Service : All Course Editions
deactivate Repository
Service --> Controller : All Course Editions
deactivate Service
Controller --> Router : All Course Editions
deactivate Controller
<-- Router : (200, OK) All Course Editions
deactivate Router


@enduml