@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title I want to know the approval percentage of a Course Edition  \n (Process View Level 3 - Backend (Get Course Editions))
skinparam sequencemessagealign center

participant ":Router" as Router <<Component>> #application
participant ":CourseEditionRestController" as Controller <<Component>> #motivation
participant ":CreateCourseEditionServiceImpl" as Service <<Component>> #business
participant ":CourseEditionRepository" as Repository <<Component>> #technology

-> Router : GET /course-editions/
activate Router
Router -> Controller : findAllCourseEditions()
activate Controller
Controller -> Service : findAll()
activate Service
Service -> Repository : findAll()
activate Repository
Repository ->  : findAll()

Repository <--  : Iterable<CourseEdition>
Repository --> Service : Iterable<CourseEdition>
deactivate Repository
Service --> Controller : Iterable<CourseEdition>
deactivate Service
Controller --> Router : List<CourseEditionResponseDTO>
deactivate Controller
<-- Router : (200 OK) List<CourseEditionResponseDTO>
deactivate Router


@enduml