@startuml
autonumber
title As an HRC, I want to Update a Teacher's Working Percentage in the System\n(Process View Level 2)

actor HRC
participant "Frontend" as FE
participant "Backend" as BE
database "Database" as DB

activate HRC #application
HRC -> FE ++#application: POST /career-progressions\nBody: { acronym, workingPercentage, date }
FE -> BE ++#application: Create TeacherCareerProgression DTO
BE -> BE: Validate input and map to domain
BE -> DB ++#application: Persist TeacherCareerProgression
DB --> BE --: TeacherCareerProgression saved
BE --> FE --: (201 Created) Successfully updated!
FE --> HRC --: Successfully updated!

@enduml
