@startuml

title UC: Update Teacher Working Percentage\n(Process View Level 3)
autonumber

participant ":Router" as RT
participant ":RESTController" as RC
participant ":Service" as S
participant ":Repository" as R
participant ":Domain" as D

[o-->RT #application : POST /career-progressions\nBody: { acronym, workingPercentage, date }
activate RT #application
RT -> RC: updateTeacherWorkingPercentage\n(UpdateTeacherWorkingPercentageRequestDTO request)
activate RC #application

RC -> S: updateTeacherWorkingPercentage\n(teacherIdVO, workingPercentageVO, dateVO)
activate S #application

S -> R: Check if Teacher Exists
activate R #application
R --> S: Teacher found
deactivate R

S -> R: Get Last Career Progression
activate R #application
R --> S: lastTCP (Domain object)
deactivate R

S -> D: Create new TeacherCareerProgression
activate D #application
D --> S: newTCP
deactivate D

S -> D: Validate Business Rules (newTCP, lastTCP)
activate D #application
D --> S: Validation OK
deactivate D

S -> R: Check for Duplicates
activate R #application
R --> S: No duplicate found
deactivate R

S -> R: Save Career Progression
activate R #application
R --> S: newTCP saved
deactivate R

S --> RC: newTCP saved
deactivate S
RC--> RT: newTCP saved
deactivate RC
[o<--RT #application : Response(201 Created)
deactivate R
deactivate RT

@enduml
