@startuml
autonumber
title As an HRC, I want to Update a Teacher's Working Percentage\n(Process View Level 1 - Clean)

actor HRC
participant ":System" as System

HRC -> System ++#application: Request to update teacher's working percentage
System --> HRC --: System requests teacher acronym, working percentage and date
HRC -> System ++#application: Provides acronym, percentage and date
System --> HRC --: Teacher’s working percentage updated successfully

@enduml
