@startuml

autonumber

title As an ASC, I want to know the number of students enrolled in a Course Edition

participant ":Router" as UI #lightblue
participant "CECtrl:CourseEditionRestController" as ceC #lightgreen
participant "ceService:CourseEditionEnrolmentService" as S #lightblue
participant "ceRepo:CourseEditionEnrolmentRepository" as R #lightpink

[o-> UI ++: **GET** /course-editions

UI -> ceC ++: getAllCourseEditions()

ref over ceC
    Get CourseEditions List
end ref

ceC --> UI --: List<CourseEditionDTO>
[o<-- UI --: List<CourseEditionDTO>

[o-> UI ++ : **GET** /course-editions/{id}/student-count

UI -> ceC ++ : getNumberOfStudentsInCourseEdition\n(selectedCourseEditionIdDTO)

ref over ceC
    Convert DTO to CourseEditionIDVO
end ref

ceC -> S ++ : numberOfStudentsEnrolledInCourseEdition(courseEditionID)

S -> R ++ : numberOfStudentsEnrolledInCourseEdition\n(courseEditionID)

ref over R
    Count enrolments matching courseEditionID
end ref

R --> S --: studentCount
S --> ceC --: studentCount

ref over ceC
    Convert studentCount to studentCountDTO
end ref

ceC --> UI --: studentCountDTO
[o<-- UI --: studentCountDTO

@enduml