@startuml
skinparam sequenceMessageAlign center

title US15: I want to update a teacher's working percentage
actor HRC
participant ":System" as System

HRC -> System: I want to update Teacher's working percentage
System --> HRC: What Teacher?
HRC -> System: This Teacher!
System --> HRC: What working percentage?
HRC -> System: This working percentage!
System --> HRC: What date?
HRC -> System: This date!
System --> HRC: Ok!

@enduml