@startuml
actor ASC as Admin

participant ":UI" as UI #lightblue
participant ":ControllerUS27" as C #lightblue
participant ":ProgrammeList" as PL #lightblue


Admin -> UI ++ #application : I Want to register a Programme in the System,\n including a Study Plan.
UI --> Admin -- : Name? Acronym? quantityOfEcts? quantityOfSemesters?  DegreeType? \n Department? Programme Director?
Admin -> UI ++ #application : Name! Acronym! quantityOfEcts! quantityOfSemesters!  DegreeType! \n Department! Programme Director!
UI -> C ++ #application : registerProgrammeInTheSystemIncludingStudyPlan(Name, Acronym, quantityOfEcts, \n quantityOfSemesters,  DegreeType,  Department, Programme Director)
C -> PL ++ #application : registerProgramme(name, acronym, quantityOfEcts, quantityOfSemesters, degreeType, \n department, programmeDirector)

create ":Programme" as P #lightblue
PL -> P ++ #application : <Create> (name, acronym, quantityOfEcts, quantityOfSemesters, \n degreeType, department, programmeDirector)
P -> P : isNameInvalid()
P -> P : isAcronymInvalid()
P -> P : isQuantityOfEctsInvalid()
P -> P : isQuantityOfSemestersInvalid()

create ":StudyPlan" as SP #lightblue
P -> SP ++ #application : StudyPlan()
SP --> P -- : List<CourseInStudyPlan> SP1

P --> PL -- : P1

PL -> PL : contains(P1)
PL -> PL : add(P1)

PL --> C -- : True
C --> UI -- : True
UI --> Admin -- : Success!

ref over Admin
US03_AddCourseToAProgramme.


end ref

Admin -> UI ++ #application : I want to add a Course to StudyPlan
UI --> Admin -- : semester? curricularYear? course? programme?
Admin -> UI ++ #application : semester! curricularYear! course! P1!
UI -> C ++ #application : addCourseToStudyPlan(semester, curricularYear, course, P1)
C -> SP ++ #application : P1.getStudyPlan().addCourseToStudyPlan(semester, curricularYear, course, P1)
SP -> SP : isCourseOrProgrammeInvalid(course, p1)
SP -> SP : isCourseInStudyPlan(course, p1)

create ":CourseInStudyPlan" as CSP #lightblue

SP -> CSP ++ #application : CourseInStudyPlan(semester, curricularYear, course, P1)
CSP -> CSP : isSemesterInvalid
CSP -> CSP : IsCurricularYearInvalid

CSP --> SP -- : CSP1

SP -> SP : IsECTSLimitExceeded(semester, curricularYear, CSP1)
SP -> SP : addCourseToStudyPlan(CSP1)

SP --> C -- : True
C --> UI -- : True

UI --> Admin -- : Success

@enduml