@startuml
!pragma layout smetana
left to right direction
skinparam packageStyle rectangle

title US30 As an ASC, I want to add a course to a programme using a Web UI. \n (Scenario View - Level 1)

actor "Administrator" as admin

rectangle "PAI System" {
    usecase "I want to add a course to a programme." as UC30
}

admin --> UC30

@enduml