@startuml
skinparam linetype ortho
skinparam ranksep 150
skinparam nodesep 120
skinparam packageBorderColor #F0B0B0
skinparam arrowThickness 2
top to bottom direction


title US05: "As an Administrator, I want to Register a Department in the System"\nLogical View Level 5

package US05 {
'--- Controller ---
package controller {
  class DepartmentRestController <<restController>> {
    + getDepartmentById(String): ResponseEntity<?>
    + registerDepartment(RegisterDepartmentRequest): ResponseEntity<?>
    + updateDepartmentDirector(DepartmentWithDirectorRequest): ResponseEntity<?>
    + allDepartments(): ResponseEntity<?>
  }
}

'--- Assembler ---
package assembler {
interface IDepartmentAssembler << interface >> {
  + fromStringToDepartmentID(String): DepartmentID
  + toRegisterDepartmentRequestVOs(RegisterDepartmentRequest): RegisterDepartmentRequestVOs
  + toDWDDTO(Department): DepartmentWithDirectorDTO
  + fromRequestToCommand(DepartmentWithDirectorRequest): DepartmentWithDirectorCommand
  + toDWDDTOs(Iterable<Department>): Iterable<DepartmentWithDirectorDTO>
  + toDTO(Department): DepartmentDTO
  + toDTOs(Iterable<Department>): Iterable<DepartmentDTO>
}

class DepartmentAssemblerImpl {
  + toDWDDTO(Department): DepartmentWithDirectorDTO
  + toRegisterDepartmentRequestVOs(RegisterDepartmentRequest): RegisterDepartmentRequestVOs
  + fromStringToDepartmentID(String): DepartmentID
  + toDTOs(Iterable<Department>): Iterable<DepartmentDTO>
  + fromRequestToCommand(DepartmentWithDirectorRequest): DepartmentWithDirectorCommand
  + toDWDDTOs(Iterable<Department>): Iterable<DepartmentWithDirectorDTO>
  + toDTO(Department): DepartmentDTO
}

class DepartmentHateoasAssemblerImpl {
  + toModel(DepartmentDTO): EntityModel<DepartmentDTO>
}
interface IDepartmentHateoasAssembler << interface >> {
  + toModel(DepartmentDTO): EntityModel<DepartmentDTO>
}
}

package dto {
entity DepartmentDTO << record >> {
  + name(): String
  + id(): String
  + acronym(): String
}
entity RegisterDepartmentRequest << record >> {
  + name(): String
  + acronym(): String
}
entity RegisterDepartmentRequestVOs << record >> {
  + acronym(): DepartmentAcronym
  + name(): Name
}

}
}
'--- Services & Interfaces ---
package Service {
    'skinparam PackageBorderColor White
    interface IDepartmentRegistrationService << interface >> {
      + createAndSaveDepartment(RegisterDepartmentRequestVOs): Department
      + getDepartmentById(DepartmentID): Optional<Department>
       allDepartments: Iterable<Department>
    }
    class DepartmentRegistrationServiceImpl {
      + createAndSaveDepartment(RegisterDepartmentRequestVOs): Department
      + getDepartmentById(DepartmentID): Optional<Department>
       allDepartments: Iterable<Department>
    }
}

'--- DOMAIN ---
package Domain {

'--- Factories & Interfaces ---
package Factory {
    together{
    interface IDepartmentFactory << interface >> {
      + newDepartment(DepartmentAcronym, Name, TeacherID): Department
      + newDepartment(DepartmentAcronym, Name): Department
    }

    class DepartmentFactoryImpl {
      + newDepartment(DepartmentAcronym, Name, TeacherID): Department
      + newDepartment(DepartmentAcronym, Name): Department
    }
    }
}
'--- Department Aggregate ---
package Department {
class Department <<root>> {
  + equals(Object): boolean
  + changeDirector(TeacherID): boolean
  + identity(): DepartmentID
  + hashCode(): int
  + sameAs(Object): boolean
   name: Name
   acronym: DepartmentAcronym
   departmentID: DepartmentID
   directorID: TeacherID
}

class DepartmentAcronym << valueObject >> {
  + equals(Object): boolean
  + hashCode(): int
   acronym: String
}
class DepartmentID << valueObject >>{
  + hashCode(): int
  + equals(Object): boolean
   acronym: DepartmentAcronym
}
class TeacherID << valueObject >>{
  + hashCode(): int
  + equals(Object): boolean
   teacherID: String
}
class Name << valueObject >>{
  + hashCode(): int
  + equals(Object): boolean
  - isNameValid(String): boolean
   name: String
}

'--- Repository IREPO---
package Repository {
  interface IDepartmentRepository << interface >> {
    + findDepartmentByID(DepartmentID): Optional<Department>
    + containsOfIdentity(DepartmentID): boolean
    + save(Department): Department
    + findAll(): List<Department>
    + ofIdentity(DepartmentID): Optional<Department>
     departmentIDs: Set<DepartmentID>
  }
  }
}
package Persistence {
  '--- Mappers ---
  package Mapper {
    interface IDepartmentIDMapper << interface >> {
      + toDataModel(DepartmentID): DepartmentIDDataModel
      + toDomainModel(DepartmentIDDataModel): DepartmentID
    }
    class DepartmentIDMapperImpl {
      + toDataModel(DepartmentID): DepartmentIDDataModel
      + toDomainModel(DepartmentIDDataModel): DepartmentID
    }

    interface IDepartmentMapper << interface >> {
      + toDomain(DepartmentDataModel): Department
      + toDataModel(Department): DepartmentDataModel
    }
    class DepartmentMapperImpl {
      + toDomain(DepartmentDataModel): Department
      + toDataModel(Department): DepartmentDataModel
       departmentFactory: IDepartmentFactory
    }
  }

    '--- Data Models ---
    package DataModel {
    class DepartmentDataModel <<dataModel>> {
      - id: DepartmentIDDataModel
      - directorId: TeacherIDDataModel
      - name: String
      - acronym: String
      + equals(Object): boolean
      + hashCode(): int
       name: String
       id: DepartmentIDDataModel
       acronym: String
       directorId: TeacherIDDataModel
    }


    class DepartmentIDDataModel <<dataModel>>{
      - departmentID: String
      + equals(Object): boolean
      + hashCode(): int
       departmentID: String
    }
    }
package RepositorySpringData {
  interface IDepartmentRepositorySpringData << interface >> {
    + save(DepartmentDataModel): DepartmentDataModel
    + findAll(): List<DepartmentDataModel>
    + existsById(DepartmentIDDataModel): boolean
    + findById(DepartmentIDDataModel): Optional<DepartmentDataModel>
  }
  class DepartmentRepositorySpringDataImpl {
    + save(Department): Department
    + findAll(): List<Department>
    + containsOfIdentity(DepartmentID): boolean
    + findDepartmentByID(DepartmentID): Optional<Department>
    + ofIdentity(DepartmentID): Optional<Department>
     departmentIDs: Set<DepartmentID>
  }
}




DepartmentRestController "1" *-[#595959,plain]-> "departmentAssembler\n1" IDepartmentAssembler
DepartmentRestController "1" *-[#595959,plain]-> "departmentHateoasAssembler\n1" IDepartmentHateoasAssembler
DepartmentRestController "1" *-[#595959,plain]-> "departmentRegistrationService\n1" IDepartmentRegistrationService

DepartmentAssemblerImpl -[dashed]-> DepartmentAcronym : "«create»"
DepartmentAssemblerImpl -[dashed]-> DepartmentDTO : "«create»"
DepartmentAssemblerImpl -[dashed]-> DepartmentID : "«create»"
DepartmentAssemblerImpl -[#008200,dashed]-|>  IDepartmentAssembler
DepartmentAssemblerImpl -[dashed]-> Name : "«create»"
DepartmentAssemblerImpl -[dashed]-> RegisterDepartmentRequestVOs : "«create»"

DepartmentHateoasAssemblerImpl -[#008200,dashed]-|> IDepartmentHateoasAssembler

RegisterDepartmentRequestVOs "1" *-[#595959,plain]-> "name\n1" Name
RegisterDepartmentRequestVOs "1" *-[#595959,plain]-> "_departmentAcronym\n1" acronym

DepartmentRegistrationServiceImpl "1" *-[#595959,plain]-> "departmentFactory\n1" IDepartmentFactory
DepartmentRegistrationServiceImpl -[#008200,dashed]-|>  IDepartmentRegistrationService
DepartmentRegistrationServiceImpl "1" *-[#595959,plain]-> "departmentRepository\n1" IDepartmentRepository

DepartmentFactoryImpl -[dashed]-> Department : "«create»"
DepartmentFactoryImpl -[#008200,dashed]-|> IDepartmentFactory

Department -[dashed]->  DepartmentID: "«create»"
Department "1" *-[#595959,plain]-> "_departmentId\n1" DepartmentID
Department "1" *-[#595959,plain]-> "_departmentName\n1" Name
DepartmentID "1" *-[#595959,plain]-> "_departmentAcronym\n1" DepartmentAcronym

DepartmentDataModel "1" *-[#595959,plain]-> "id\n1" DepartmentIDDataModel
DepartmentDataModel -[dashed]-> DepartmentIDDataModel: "«create»"

DepartmentRepositorySpringDataImpl "1" *-[#595959,plain]-> "idMapper\n1" IDepartmentIDMapper
DepartmentRepositorySpringDataImpl "1" *-[#595959,plain]-> "departmentMapper\n1" IDepartmentMapper
DepartmentRepositorySpringDataImpl -[#008200,dashed]-|>  IDepartmentRepository
DepartmentRepositorySpringDataImpl "1" *-[#595959,plain]-> "jpaRepo\n1" IDepartmentRepositorySpringData

DepartmentIDMapperImpl -[dashed]-> DepartmentAcronym : "«create»"
DepartmentIDMapperImpl -[dashed]-> DepartmentID : "«create»"
DepartmentIDMapperImpl -[dashed]-> DepartmentIDDataModel : "«create»"
DepartmentIDMapperImpl -[#008200,dashed]-|> IDepartmentIDMapper

DepartmentMapperImpl -[dashed]-> DepartmentAcronym : "«create»"
DepartmentMapperImpl -[dashed]-> DepartmentDataModel : "«create»"
DepartmentMapperImpl "1" *-[#595959,plain]-> "departmentFactory\n1" IDepartmentFactory
DepartmentMapperImpl -[#008200,dashed]-|> IDepartmentMapper
DepartmentMapperImpl -[dashed]-> Name : "«create»"

@enduml
